{ buildGoApplication, version }:

buildGoApplication {
  pname = "elo-web-service";
  inherit version;

  src = ../elo-web-service;

  # gomod2nix.toml is generated by running `gomod2nix generate` in elo-web-service/
  # and must be committed alongside go.mod and go.sum.
  modules = ../elo-web-service/gomod2nix.toml;
}
