// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arenas.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

const clearArenaStale = `-- name: ClearArenaStale :exec
UPDATE arenas
SET stale_at = NULL, recalc_from = NULL
WHERE id = $1 AND stale_at = $2
`

type ClearArenaStaleParams struct {
	ID      id.ID              `json:"id"`
	StaleAt pgtype.Timestamptz `json:"stale_at"`
}

// Conditional clear: stale_at must still be the mark the recalculation
// started from; a re-mark during the run leaves the arena stale (staleness
// cancellation, ADR-24).
func (q *Queries) ClearArenaStale(ctx context.Context, arg ClearArenaStaleParams) error {
	_, err := q.db.Exec(ctx, clearArenaStale, arg.ID, arg.StaleAt)
	return err
}

const countPlayerMatchesInArenaInPeriod = `-- name: CountPlayerMatchesInArenaInPeriod :one
SELECT COUNT(*)::int AS count
FROM matches m
JOIN match_scores ms ON ms.match_id = m.id
JOIN arenas a ON a.id = $1
JOIN match_filters f ON f.id = a.match_filter_id
WHERE ms.player_id = $2
  AND m.date >= $3::timestamptz
  AND m.date <= $4::timestamptz
  AND (f.date_from IS NULL OR m.date >= f.date_from)
  AND (f.date_to IS NULL OR m.date <= f.date_to)
  AND (
      (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
      OR f.game_ids @> ARRAY[m.game_id]
      OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
  )
  AND (f.tournament_id IS NULL OR EXISTS (
      SELECT 1 FROM match_tournament mt
      WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
  ))
`

type CountPlayerMatchesInArenaInPeriodParams struct {
	ArenaID  id.ID     `json:"arena_id"`
	PlayerID id.ID     `json:"player_id"`
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
}

// Matches of one player inside the arena (filter applied) within
// [date_from, date_to] — the elite promotion counters.
func (q *Queries) CountPlayerMatchesInArenaInPeriod(ctx context.Context, arg CountPlayerMatchesInArenaInPeriodParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPlayerMatchesInArenaInPeriod,
		arg.ArenaID,
		arg.PlayerID,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createArena = `-- name: CreateArena :one
INSERT INTO arenas (id, name, match_filter_id, settings, settings_schema_version, game_id, tournament_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, match_filter_id, settings, settings_schema_version, game_id, tournament_id, recalc_from, stale_at
`

type CreateArenaParams struct {
	ID                    id.ID           `json:"id"`
	Name                  string          `json:"name"`
	MatchFilterID         id.ID           `json:"match_filter_id"`
	Settings              json.RawMessage `json:"settings"`
	SettingsSchemaVersion int32           `json:"settings_schema_version"`
	GameID                *id.ID          `json:"game_id"`
	TournamentID          *id.ID          `json:"tournament_id"`
}

func (q *Queries) CreateArena(ctx context.Context, arg CreateArenaParams) (Arena, error) {
	row := q.db.QueryRow(ctx, createArena,
		arg.ID,
		arg.Name,
		arg.MatchFilterID,
		arg.Settings,
		arg.SettingsSchemaVersion,
		arg.GameID,
		arg.TournamentID,
	)
	var i Arena
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MatchFilterID,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
	)
	return i, err
}

const createMatchFilter = `-- name: CreateMatchFilter :one
INSERT INTO match_filters (id, date_from, date_to, game_ids, tag_ids, tournament_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateMatchFilterParams struct {
	ID           id.ID              `json:"id"`
	DateFrom     pgtype.Timestamptz `json:"date_from"`
	DateTo       pgtype.Timestamptz `json:"date_to"`
	GameIds      []id.ID            `json:"game_ids"`
	TagIds       []id.ID            `json:"tag_ids"`
	TournamentID *id.ID             `json:"tournament_id"`
}

func (q *Queries) CreateMatchFilter(ctx context.Context, arg CreateMatchFilterParams) (id.ID, error) {
	row := q.db.QueryRow(ctx, createMatchFilter,
		arg.ID,
		arg.DateFrom,
		arg.DateTo,
		arg.GameIds,
		arg.TagIds,
		arg.TournamentID,
	)
	var id id.ID
	err := row.Scan(&id)
	return id, err
}

const deleteArena = `-- name: DeleteArena :one
DELETE FROM arenas WHERE id = $1
RETURNING id, name
`

type DeleteArenaRow struct {
	ID   id.ID  `json:"id"`
	Name string `json:"name"`
}

// Returns the deleted row so the audit trail can capture the name.
func (q *Queries) DeleteArena(ctx context.Context, argID id.ID) (DeleteArenaRow, error) {
	row := q.db.QueryRow(ctx, deleteArena, argID)
	var i DeleteArenaRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteArenaStats = `-- name: DeleteArenaStats :exec

DELETE FROM arena_player_stats WHERE arena_id = $1
`

// ---------------------------------------------------------------------------
// Precalculated stats
// ---------------------------------------------------------------------------
func (q *Queries) DeleteArenaStats(ctx context.Context, arenaID id.ID) error {
	_, err := q.db.Exec(ctx, deleteArenaStats, arenaID)
	return err
}

const getArena = `-- name: GetArena :one

SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.id = $1
`

type GetArenaRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

// Arena queries (ADR-24). The reusable match-filter condition is repeated in
// the queries that evaluate it — the canonical definition lives here:
//
//	A match m meets filter f iff ALL present conditions hold (NULL = absent):
//	  date range:   f.date_from <= m.date <= f.date_to
//	  game OR tag:  m.game_id listed in f.game_ids, or m's game carries one of
//	                f.tag_ids; both empty (NULL or []) → any game
//	  tournament:   m attached to f.tournament_id via match_tournament
//
// Do not change one copy without the others.
func (q *Queries) GetArena(ctx context.Context, argID id.ID) (GetArenaRow, error) {
	row := q.db.QueryRow(ctx, getArena, argID)
	var i GetArenaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
		&i.DateFrom,
		&i.DateTo,
		&i.FilterGameIds,
		&i.FilterTagIds,
		&i.FilterTournamentID,
	)
	return i, err
}

const getArenaByGame = `-- name: GetArenaByGame :one
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.game_id = $1
`

type GetArenaByGameRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

func (q *Queries) GetArenaByGame(ctx context.Context, gameID *id.ID) (GetArenaByGameRow, error) {
	row := q.db.QueryRow(ctx, getArenaByGame, gameID)
	var i GetArenaByGameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
		&i.DateFrom,
		&i.DateTo,
		&i.FilterGameIds,
		&i.FilterTagIds,
		&i.FilterTournamentID,
	)
	return i, err
}

const getArenaByTournament = `-- name: GetArenaByTournament :one
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.tournament_id = $1
`

type GetArenaByTournamentRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

func (q *Queries) GetArenaByTournament(ctx context.Context, tournamentID *id.ID) (GetArenaByTournamentRow, error) {
	row := q.db.QueryRow(ctx, getArenaByTournament, tournamentID)
	var i GetArenaByTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
		&i.DateFrom,
		&i.DateTo,
		&i.FilterGameIds,
		&i.FilterTagIds,
		&i.FilterTournamentID,
	)
	return i, err
}

const getArenaForUpdate = `-- name: GetArenaForUpdate :one
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.id = $1
FOR UPDATE OF a
`

type GetArenaForUpdateRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

// Row-locked variant used by the recalculation updater: concurrent dirty marks
// queue behind the lock and apply after the recalculation commits.
func (q *Queries) GetArenaForUpdate(ctx context.Context, argID id.ID) (GetArenaForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getArenaForUpdate, argID)
	var i GetArenaForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
		&i.DateFrom,
		&i.DateTo,
		&i.FilterGameIds,
		&i.FilterTagIds,
		&i.FilterTournamentID,
	)
	return i, err
}

const insertArenaStats = `-- name: InsertArenaStats :exec
INSERT INTO arena_player_stats (arena_id, player_id, matches_count,
                                first_count, second_count, third_count, fourth_count)
SELECT $1, r.player_id, COUNT(*)::int,
       COUNT(*) FILTER (WHERE r.place = 1)::int,
       COUNT(*) FILTER (WHERE r.place = 2)::int,
       COUNT(*) FILTER (WHERE r.place = 3)::int,
       COUNT(*) FILTER (WHERE r.place = 4)::int
FROM (
    SELECT ms.player_id,
           RANK() OVER (PARTITION BY ms.match_id ORDER BY ms.score DESC) AS place
    FROM match_scores ms
    WHERE ms.match_id IN (
        SELECT m.id
        FROM arenas a
        JOIN match_filters f ON f.id = a.match_filter_id
        CROSS JOIN matches m
        WHERE a.id = $1
          AND (f.date_from IS NULL OR m.date >= f.date_from)
          AND (f.date_to IS NULL OR m.date <= f.date_to)
          AND (
              (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
              OR f.game_ids @> ARRAY[m.game_id]
              OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
          )
          AND (f.tournament_id IS NULL OR EXISTS (
              SELECT 1 FROM match_tournament mt
              WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
          ))
    )
) r
GROUP BY r.player_id
`

// Recompute places 1..4 per match (RANK over the match's scores, tournament
// stats semantics) for every match meeting the arena's filter.
func (q *Queries) InsertArenaStats(ctx context.Context, arenaID id.ID) error {
	_, err := q.db.Exec(ctx, insertArenaStats, arenaID)
	return err
}

const listArenaMatchesPaginated = `-- name: ListArenaMatchesPaginated :many
WITH paginated_matches AS (
    SELECT DISTINCT m.id, m.date, m.game_id, m.calculator_kind
    FROM arenas a
    JOIN match_filters f ON f.id = a.match_filter_id
    CROSS JOIN matches m
    JOIN match_scores ms ON ms.match_id = m.id
    WHERE a.id = $1
      AND (f.date_from IS NULL OR m.date >= f.date_from)
      AND (f.date_to IS NULL OR m.date <= f.date_to)
      AND (
          (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
          OR f.game_ids @> ARRAY[m.game_id]
          OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
      )
      AND (f.tournament_id IS NULL OR EXISTS (
          SELECT 1 FROM match_tournament mt
          WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
      ))
      AND (
          $2::timestamptz IS NULL
          OR m.date < $2::timestamptz
      )
      AND (
          $3::uuid IS NULL OR ms.player_id = $3::uuid
      )
      AND (
          $4::uuid IS NULL
          OR EXISTS (
              SELECT 1 FROM player_club_membership pcm
              WHERE pcm.club_id = $4::uuid
                AND pcm.player_id = ms.player_id
          )
      )
      AND (
          $5::uuid IS NULL OR m.game_id = $5::uuid
      )
    ORDER BY m.date DESC, m.id DESC
    LIMIT $6::int4
)
SELECT
    pm.id AS match_id,
    pm.date,
    g.id AS game_id,
    g.name AS game_name,
    pm.calculator_kind AS calculator_kind,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    ars.rating_staked,
    ars.rating_earned,
    CASE WHEN ars.rating_after IS NULL THEN NULL ELSE ars.rating_after END AS rating_after,
    CASE WHEN prev_rating.rating_after IS NULL THEN NULL ELSE prev_rating.rating_after END AS prev_rating,
    EXISTS(SELECT 1 FROM markets WHERE resolution_match_id = pm.id) AS has_markets
FROM paginated_matches pm
JOIN games g ON g.id = pm.game_id
JOIN match_scores s ON s.match_id = pm.id
JOIN players p ON p.id = s.player_id
LEFT JOIN arena_settlements ars ON ars.arena_id = $1
    AND ars.match_id = s.match_id AND ars.player_id = s.player_id AND ars.discriminator = 'match'
LEFT JOIN LATERAL (
    SELECT ars2.rating_after
    FROM arena_settlements ars2
    WHERE ars2.arena_id = $1 AND ars2.player_id = p.id AND ars2.date < pm.date
    ORDER BY ars2.date DESC, ars2.id DESC
    LIMIT 1
) prev_rating ON true
ORDER BY pm.date DESC, pm.id DESC, s.score DESC
`

type ListArenaMatchesPaginatedParams struct {
	ArenaID    id.ID              `json:"arena_id"`
	CursorDate pgtype.Timestamptz `json:"cursor_date"`
	PlayerID   *id.ID             `json:"player_id"`
	ClubID     *id.ID             `json:"club_id"`
	GameID     *id.ID             `json:"game_id"`
	Limit      int32              `json:"limit"`
}

type ListArenaMatchesPaginatedRow struct {
	MatchID        id.ID              `json:"match_id"`
	Date           pgtype.Timestamptz `json:"date"`
	GameID         id.ID              `json:"game_id"`
	GameName       string             `json:"game_name"`
	CalculatorKind pgtype.Text        `json:"calculator_kind"`
	PlayerID       id.ID              `json:"player_id"`
	PlayerName     string             `json:"player_name"`
	Score          float64            `json:"score"`
	RatingStaked   pgtype.Float8      `json:"rating_staked"`
	RatingEarned   pgtype.Float8      `json:"rating_earned"`
	RatingAfter    interface{}        `json:"rating_after"`
	PrevRating     interface{}        `json:"prev_rating"`
	HasMarkets     bool               `json:"has_markets"`
}

// Cursor-paginated match list of one arena, same envelope as /matches.
// Optional player/club/game filters mirror /matches; the cursor token carries
// them, so continuation requests pass only the token.
func (q *Queries) ListArenaMatchesPaginated(ctx context.Context, arg ListArenaMatchesPaginatedParams) ([]ListArenaMatchesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listArenaMatchesPaginated,
		arg.ArenaID,
		arg.CursorDate,
		arg.PlayerID,
		arg.ClubID,
		arg.GameID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaMatchesPaginatedRow{}
	for rows.Next() {
		var i ListArenaMatchesPaginatedRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameID,
			&i.GameName,
			&i.CalculatorKind,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.RatingStaked,
			&i.RatingEarned,
			&i.RatingAfter,
			&i.PrevRating,
			&i.HasMarkets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenaPlayers = `-- name: ListArenaPlayers :many

SELECT p.id AS player_id, p.name AS player_name,
       -- CASE forces sqlc to infer a nullable type: a player whose latest
       -- settlement is after  (or who has none yet) yields a NULL row.
       CASE WHEN latest.rating_after IS NULL THEN NULL ELSE latest.rating_after END AS rating_after,
       CASE WHEN latest.elo_after IS NULL THEN NULL ELSE latest.elo_after END AS elo_after,
       latest.league,
       st.matches_count, st.first_count, st.second_count, st.third_count, st.fourth_count
FROM arena_player_stats st
JOIN players p ON p.id = st.player_id
LEFT JOIN LATERAL (
    SELECT s.rating_after, s.elo_after, s.league
    FROM arena_settlements s
    WHERE s.arena_id = st.arena_id AND s.player_id = st.player_id
    ORDER BY s.date DESC, s.id DESC
    LIMIT 1
) latest ON true
WHERE st.arena_id = $1
ORDER BY p.name
`

type ListArenaPlayersRow struct {
	PlayerID     id.ID       `json:"player_id"`
	PlayerName   string      `json:"player_name"`
	RatingAfter  interface{} `json:"rating_after"`
	EloAfter     interface{} `json:"elo_after"`
	League       pgtype.Text `json:"league"`
	MatchesCount int32       `json:"matches_count"`
	FirstCount   int32       `json:"first_count"`
	SecondCount  int32       `json:"second_count"`
	ThirdCount   int32       `json:"third_count"`
	FourthCount  int32       `json:"fourth_count"`
}

// ---------------------------------------------------------------------------
// Arena page reads
// ---------------------------------------------------------------------------
// Latest settlement state joined with the precalculated stats. Final ranking
// (league priority, then rating) is applied by the service.
func (q *Queries) ListArenaPlayers(ctx context.Context, arenaID id.ID) ([]ListArenaPlayersRow, error) {
	rows, err := q.db.Query(ctx, listArenaPlayers, arenaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaPlayersRow{}
	for rows.Next() {
		var i ListArenaPlayersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.RatingAfter,
			&i.EloAfter,
			&i.League,
			&i.MatchesCount,
			&i.FirstCount,
			&i.SecondCount,
			&i.ThirdCount,
			&i.FourthCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenaPlayersAt = `-- name: ListArenaPlayersAt :many
SELECT p.id AS player_id, p.name AS player_name,
       -- CASE forces sqlc to infer a nullable type: a player whose latest
       -- settlement is after @at (or who has none yet) yields a NULL row.
       CASE WHEN latest.rating_after IS NULL THEN NULL ELSE latest.rating_after END AS rating_after,
       CASE WHEN latest.elo_after IS NULL THEN NULL ELSE latest.elo_after END AS elo_after,
       latest.league,
       COALESCE(cnt60.cnt, 0) AS cnt_60, COALESCE(cnt180.cnt, 0) AS cnt_180
FROM players p
JOIN LATERAL (
    SELECT 1 FROM arena_settlements s WHERE s.arena_id = $1 AND s.player_id = p.id LIMIT 1
) has_settlement ON true
LEFT JOIN LATERAL (
    SELECT s.rating_after, s.elo_after, s.league
    FROM arena_settlements s
    WHERE s.arena_id = $1 AND s.player_id = p.id AND s.date <= $2
    ORDER BY s.date DESC, s.id DESC
    LIMIT 1
) latest ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS cnt
    FROM matches m
    JOIN match_scores ms ON ms.match_id = m.id
    JOIN arenas a ON a.id = $1
    JOIN match_filters f ON f.id = a.match_filter_id
    WHERE ms.player_id = p.id
      AND m.date >= ($2 - interval '60 days') AND m.date <= $2
      AND (f.date_from IS NULL OR m.date >= f.date_from)
      AND (f.date_to IS NULL OR m.date <= f.date_to)
      AND (
          (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
          OR f.game_ids @> ARRAY[m.game_id]
          OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
      )
      AND (f.tournament_id IS NULL OR EXISTS (
          SELECT 1 FROM match_tournament mt
          WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
      ))
) cnt60 ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS cnt
    FROM matches m
    JOIN match_scores ms ON ms.match_id = m.id
    JOIN arenas a ON a.id = $1
    JOIN match_filters f ON f.id = a.match_filter_id
    WHERE ms.player_id = p.id
      AND m.date >= ($2 - interval '180 days') AND m.date <= $2
      AND (f.date_from IS NULL OR m.date >= f.date_from)
      AND (f.date_to IS NULL OR m.date <= f.date_to)
      AND (
          (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
          OR f.game_ids @> ARRAY[m.game_id]
          OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
      )
      AND (f.tournament_id IS NULL OR EXISTS (
          SELECT 1 FROM match_tournament mt
          WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
      ))
) cnt180 ON true
ORDER BY p.name
`

type ListArenaPlayersAtParams struct {
	ArenaID id.ID              `json:"arena_id"`
	Date    pgtype.Timestamptz `json:"date"`
}

type ListArenaPlayersAtRow struct {
	PlayerID    id.ID       `json:"player_id"`
	PlayerName  string      `json:"player_name"`
	RatingAfter interface{} `json:"rating_after"`
	EloAfter    interface{} `json:"elo_after"`
	League      pgtype.Text `json:"league"`
	Cnt60       int32       `json:"cnt_60"`
	Cnt180      int32       `json:"cnt_180"`
}

// Point-in-time standings of one arena (for rank-change history): the latest
// settlement at or before @at, plus the arena-filtered match counts the elite
// staleness check needs. Lists players with at least one settlement.
func (q *Queries) ListArenaPlayersAt(ctx context.Context, arg ListArenaPlayersAtParams) ([]ListArenaPlayersAtRow, error) {
	rows, err := q.db.Query(ctx, listArenaPlayersAt, arg.ArenaID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaPlayersAtRow{}
	for rows.Next() {
		var i ListArenaPlayersAtRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.RatingAfter,
			&i.EloAfter,
			&i.League,
			&i.Cnt60,
			&i.Cnt180,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenas = `-- name: ListArenas :many
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id,
       (
           SELECT COUNT(*) FROM matches m
           WHERE (f.date_from IS NULL OR m.date >= f.date_from)
             AND (f.date_to IS NULL OR m.date <= f.date_to)
             AND (
                 (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
                 OR f.game_ids @> ARRAY[m.game_id]
                 OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
             )
             AND (f.tournament_id IS NULL OR EXISTS (
                 SELECT 1 FROM match_tournament mt
                 WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
             ))
       ) AS matches_count
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE (
    $1::text IS NULL
    OR ($1::text = 'tournaments' AND a.tournament_id IS NOT NULL)
    OR ($1::text = 'games' AND a.tournament_id IS NULL
        AND a.id <> 'a2ea0000-0000-0000-0000-000000000001'
        AND NOT (
            coalesce(cardinality(f.game_ids), 0) = 0
            AND coalesce(cardinality(f.tag_ids), 0) = 0
            AND f.tournament_id IS NULL
            AND f.date_from IS NULL
            AND f.date_to IS NULL
        ))
)
ORDER BY a.name
`

type ListArenasRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
	MatchesCount          int64              `json:"matches_count"`
}

// kind narrows the list for the /arenas page tabs: 'games' returns every
// non-tournament arena except the global one (which is the main page, not a
// list entry); 'tournaments' returns only the tournament arenas.
func (q *Queries) ListArenas(ctx context.Context, kind pgtype.Text) ([]ListArenasRow, error) {
	rows, err := q.db.Query(ctx, listArenas, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenasRow{}
	for rows.Next() {
		var i ListArenasRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Settings,
			&i.SettingsSchemaVersion,
			&i.GameID,
			&i.TournamentID,
			&i.RecalcFrom,
			&i.StaleAt,
			&i.DateFrom,
			&i.DateTo,
			&i.FilterGameIds,
			&i.FilterTagIds,
			&i.FilterTournamentID,
			&i.MatchesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenasForGame = `-- name: ListArenasForGame :many
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.game_id = $1
   OR (
       coalesce(cardinality(f.game_ids), 0) = 0
       AND coalesce(cardinality(f.tag_ids), 0) = 0
       AND f.tournament_id IS NULL
       AND f.date_from IS NULL
       AND f.date_to IS NULL
   )
   OR f.game_ids @> ARRAY[$1]
   OR EXISTS (
       SELECT 1 FROM game_tag gt
       WHERE gt.game_id = $1 AND gt.tag_id = ANY(f.tag_ids)
   )
ORDER BY a.name
`

type ListArenasForGameRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

// Arenas whose filter includes game @game_id or one of its tags, plus
// unconditional (global) arenas — the /games page arena list.
func (q *Queries) ListArenasForGame(ctx context.Context, gameID *id.ID) ([]ListArenasForGameRow, error) {
	rows, err := q.db.Query(ctx, listArenasForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenasForGameRow{}
	for rows.Next() {
		var i ListArenasForGameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Settings,
			&i.SettingsSchemaVersion,
			&i.GameID,
			&i.TournamentID,
			&i.RecalcFrom,
			&i.StaleAt,
			&i.DateFrom,
			&i.DateTo,
			&i.FilterGameIds,
			&i.FilterTagIds,
			&i.FilterTournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenasMatchingMatch = `-- name: ListArenasMatchingMatch :many
SELECT a.id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
JOIN matches m ON m.id = $1
WHERE (f.date_from IS NULL OR m.date >= f.date_from)
  AND (f.date_to IS NULL OR m.date <= f.date_to)
  AND (
      (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
      OR f.game_ids @> ARRAY[m.game_id]
      OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
  )
  AND (f.tournament_id IS NULL OR EXISTS (
      SELECT 1 FROM match_tournament mt
      WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
  ))
`

// Arena ids whose filter matches the given match — the synchronous-drain
// affected set on match writes. Joining the single match row gives the
// condition its m.* values.
func (q *Queries) ListArenasMatchingMatch(ctx context.Context, matchID id.ID) ([]id.ID, error) {
	rows, err := q.db.Query(ctx, listArenasMatchingMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var id id.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForArenaReplay = `-- name: ListMatchesForArenaReplay :many
SELECT m.id, m.date, m.game_id, m.calculator_kind, m.calculator_schema_version, m.calculator_data
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
CROSS JOIN matches m
WHERE a.id = $1
  AND m.date >= $2
  AND (f.date_from IS NULL OR m.date >= f.date_from)
  AND (f.date_to IS NULL OR m.date <= f.date_to)
  AND (
      (coalesce(cardinality(f.game_ids), 0) = 0 AND coalesce(cardinality(f.tag_ids), 0) = 0)
      OR f.game_ids @> ARRAY[m.game_id]
      OR EXISTS (SELECT 1 FROM game_tag gt WHERE gt.game_id = m.game_id AND gt.tag_id = ANY(f.tag_ids))
  )
  AND (f.tournament_id IS NULL OR EXISTS (
      SELECT 1 FROM match_tournament mt
      WHERE mt.match_id = m.id AND mt.tournament_id = f.tournament_id
  ))
ORDER BY m.date ASC, m.id ASC
`

type ListMatchesForArenaReplayParams struct {
	ID   id.ID              `json:"id"`
	Date pgtype.Timestamptz `json:"date"`
}

// Filtered matches of the arena from @from_date on, in event order — the
// updater's replay input.
func (q *Queries) ListMatchesForArenaReplay(ctx context.Context, arg ListMatchesForArenaReplayParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesForArenaReplay, arg.ID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.GameID,
			&i.CalculatorKind,
			&i.CalculatorSchemaVersion,
			&i.CalculatorData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleArenas = `-- name: ListStaleArenas :many
SELECT a.id, a.name, a.settings, a.settings_schema_version,
       a.game_id, a.tournament_id, a.recalc_from, a.stale_at,
       f.date_from, f.date_to,
       f.game_ids AS filter_game_ids, f.tag_ids AS filter_tag_ids,
       f.tournament_id AS filter_tournament_id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE a.stale_at IS NOT NULL AND a.stale_at <= $1::timestamptz
ORDER BY a.stale_at
`

type ListStaleArenasRow struct {
	ID                    id.ID              `json:"id"`
	Name                  string             `json:"name"`
	Settings              json.RawMessage    `json:"settings"`
	SettingsSchemaVersion int32              `json:"settings_schema_version"`
	GameID                *id.ID             `json:"game_id"`
	TournamentID          *id.ID             `json:"tournament_id"`
	RecalcFrom            pgtype.Timestamptz `json:"recalc_from"`
	StaleAt               pgtype.Timestamptz `json:"stale_at"`
	DateFrom              pgtype.Timestamptz `json:"date_from"`
	DateTo                pgtype.Timestamptz `json:"date_to"`
	FilterGameIds         []id.ID            `json:"filter_game_ids"`
	FilterTagIds          []id.ID            `json:"filter_tag_ids"`
	FilterTournamentID    *id.ID             `json:"filter_tournament_id"`
}

func (q *Queries) ListStaleArenas(ctx context.Context, dueBefore time.Time) ([]ListStaleArenasRow, error) {
	rows, err := q.db.Query(ctx, listStaleArenas, dueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleArenasRow{}
	for rows.Next() {
		var i ListStaleArenasRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Settings,
			&i.SettingsSchemaVersion,
			&i.GameID,
			&i.TournamentID,
			&i.RecalcFrom,
			&i.StaleAt,
			&i.DateFrom,
			&i.DateTo,
			&i.FilterGameIds,
			&i.FilterTagIds,
			&i.FilterTournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagFilteredArenaIds = `-- name: ListTagFilteredArenaIds :many
SELECT a.id
FROM arenas a
JOIN match_filters f ON f.id = a.match_filter_id
WHERE coalesce(cardinality(f.tag_ids), 0) > 0
`

// Arenas whose filter has a game-tag condition — the conservative mark set
// when any game's tags change (a tag toggle can flip any of them).
func (q *Queries) ListTagFilteredArenaIds(ctx context.Context) ([]id.ID, error) {
	rows, err := q.db.Query(ctx, listTagFilteredArenaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var id id.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArenasStaleFromDate = `-- name: MarkArenasStaleFromDate :exec
UPDATE arenas
SET stale_at = NOW(),
    recalc_from = CASE
        WHEN arenas.stale_at IS NOT NULL AND arenas.recalc_from IS NULL THEN NULL
        WHEN arenas.recalc_from IS NULL THEN $1::timestamptz
        ELSE least(arenas.recalc_from, $1::timestamptz)
    END
WHERE id = ANY($2::uuid[])
`

type MarkArenasStaleFromDateParams struct {
	FromDate time.Time `json:"from_date"`
	ArenaIds []id.ID   `json:"arena_ids"`
}

// Incremental mark: widen the pending replay window to include @from_date.
// A pending full recalc (recalc_from IS NULL while stale) wins over dates.
func (q *Queries) MarkArenasStaleFromDate(ctx context.Context, arg MarkArenasStaleFromDateParams) error {
	_, err := q.db.Exec(ctx, markArenasStaleFromDate, arg.FromDate, arg.ArenaIds)
	return err
}

const markArenasStaleFull = `-- name: MarkArenasStaleFull :exec

UPDATE arenas
SET stale_at = NOW(), recalc_from = NULL
WHERE id = ANY($1::uuid[])
`

// ---------------------------------------------------------------------------
// Dirty queue
// ---------------------------------------------------------------------------
func (q *Queries) MarkArenasStaleFull(ctx context.Context, arenaIds []id.ID) error {
	_, err := q.db.Exec(ctx, markArenasStaleFull, arenaIds)
	return err
}

const updateArena = `-- name: UpdateArena :one
UPDATE arenas
SET name = $2, match_filter_id = $3, settings = $4, settings_schema_version = $5
WHERE id = $1
RETURNING id, name, match_filter_id, settings, settings_schema_version, game_id, tournament_id, recalc_from, stale_at
`

type UpdateArenaParams struct {
	ID                    id.ID           `json:"id"`
	Name                  string          `json:"name"`
	MatchFilterID         id.ID           `json:"match_filter_id"`
	Settings              json.RawMessage `json:"settings"`
	SettingsSchemaVersion int32           `json:"settings_schema_version"`
}

func (q *Queries) UpdateArena(ctx context.Context, arg UpdateArenaParams) (Arena, error) {
	row := q.db.QueryRow(ctx, updateArena,
		arg.ID,
		arg.Name,
		arg.MatchFilterID,
		arg.Settings,
		arg.SettingsSchemaVersion,
	)
	var i Arena
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MatchFilterID,
		&i.Settings,
		&i.SettingsSchemaVersion,
		&i.GameID,
		&i.TournamentID,
		&i.RecalcFrom,
		&i.StaleAt,
	)
	return i, err
}

const updateArenaName = `-- name: UpdateArenaName :exec
UPDATE arenas SET name = $2 WHERE id = $1
`

type UpdateArenaNameParams struct {
	ID   id.ID  `json:"id"`
	Name string `json:"name"`
}

// Name sync for auto-managed arenas when their game/tournament is renamed.
func (q *Queries) UpdateArenaName(ctx context.Context, arg UpdateArenaNameParams) error {
	_, err := q.db.Exec(ctx, updateArenaName, arg.ID, arg.Name)
	return err
}
