// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: camp_matches.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

const addCampMatch = `-- name: AddCampMatch :exec

INSERT INTO camp_matches (arena_id, match_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCampMatchParams struct {
	ArenaID id.ID `json:"arena_id"`
	MatchID id.ID `json:"match_id"`
}

// Camp arena link queries (ADR-27). Camp membership is the explicit
// camp_matches link, written when a match is created with camp_arena_ids and
// never altered afterwards (editing a match cannot change its camps).
func (q *Queries) AddCampMatch(ctx context.Context, arg AddCampMatchParams) error {
	_, err := q.db.Exec(ctx, addCampMatch, arg.ArenaID, arg.MatchID)
	return err
}

const deleteCampMatch = `-- name: DeleteCampMatch :exec
DELETE FROM camp_matches
WHERE arena_id = $1 AND match_id = $2
`

type DeleteCampMatchParams struct {
	ArenaID id.ID `json:"arena_id"`
	MatchID id.ID `json:"match_id"`
}

// Detach a match from a camp arena (the edit-form desired-set diff, ADR-27):
// the camp is stale-marked by the caller and the replay rewrites its
// settlements and medal stats.
func (q *Queries) DeleteCampMatch(ctx context.Context, arg DeleteCampMatchParams) error {
	_, err := q.db.Exec(ctx, deleteCampMatch, arg.ArenaID, arg.MatchID)
	return err
}

const getCampMatchDateRange = `-- name: GetCampMatchDateRange :one
SELECT
    MIN(m.date)::timestamptz AS min_date,
    MAX(m.date)::timestamptz AS max_date
FROM camp_matches cm
JOIN matches m ON m.id = cm.match_id
WHERE cm.arena_id = $1
HAVING COUNT(*) > 0
`

type GetCampMatchDateRangeRow struct {
	MinDate time.Time `json:"min_date"`
	MaxDate time.Time `json:"max_date"`
}

// HAVING guards the aggregate: with no linked matches it returns zero rows
// (ErrNoRows) instead of a (NULL, NULL) row that can't scan into the
// non-nullable time.Time. The camp date-narrowing guard reads this.
func (q *Queries) GetCampMatchDateRange(ctx context.Context, arenaID id.ID) (GetCampMatchDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getCampMatchDateRange, arenaID)
	var i GetCampMatchDateRangeRow
	err := row.Scan(&i.MinDate, &i.MaxDate)
	return i, err
}

const listCampArenasByMatchIDs = `-- name: ListCampArenasByMatchIDs :many
SELECT
    cm.match_id,
    a.id   AS arena_id,
    a.name AS arena_name
FROM camp_matches cm
JOIN arenas a ON a.id = cm.arena_id
WHERE cm.match_id = ANY($1::uuid[])
ORDER BY a.name
`

type ListCampArenasByMatchIDsRow struct {
	MatchID   id.ID  `json:"match_id"`
	ArenaID   id.ID  `json:"arena_id"`
	ArenaName string `json:"arena_name"`
}

// The camps of a set of matches — the [{id, name}] payload of the match
// response (the old match.tournaments shape).
func (q *Queries) ListCampArenasByMatchIDs(ctx context.Context, matchIds []id.ID) ([]ListCampArenasByMatchIDsRow, error) {
	rows, err := q.db.Query(ctx, listCampArenasByMatchIDs, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampArenasByMatchIDsRow{}
	for rows.Next() {
		var i ListCampArenasByMatchIDsRow
		if err := rows.Scan(&i.MatchID, &i.ArenaID, &i.ArenaName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForCampReplay = `-- name: ListMatchesForCampReplay :many
SELECT m.id, m.date, m.game_id, m.calculator_kind, m.calculator_schema_version, m.calculator_data
FROM camp_matches cm
JOIN matches m ON m.id = cm.match_id
WHERE cm.arena_id = $1
  AND m.date >= $2
ORDER BY m.date ASC, m.id ASC
`

type ListMatchesForCampReplayParams struct {
	ArenaID id.ID              `json:"arena_id"`
	Date    pgtype.Timestamptz `json:"date"`
}

// Linked matches of the camp arena from @from_date on, in event order — the
// updater's replay input for camp arenas (replaces filter evaluation).
func (q *Queries) ListMatchesForCampReplay(ctx context.Context, arg ListMatchesForCampReplayParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesForCampReplay, arg.ArenaID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.GameID,
			&i.CalculatorKind,
			&i.CalculatorSchemaVersion,
			&i.CalculatorData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
