// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clubs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClubMember = `-- name: AddClubMember :exec
INSERT INTO player_club_membership (club_id, player_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddClubMemberParams struct {
	ClubID   string `json:"club_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) AddClubMember(ctx context.Context, arg AddClubMemberParams) error {
	_, err := q.db.Exec(ctx, addClubMember, arg.ClubID, arg.PlayerID)
	return err
}

const createClub = `-- name: CreateClub :one
INSERT INTO clubs (id, name)
VALUES ($1, $2)
RETURNING id, name, geologist_name, icon_svg
`

type CreateClubParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub, arg.ID, arg.Name)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.IconSvg,
	)
	return i, err
}

const deleteClub = `-- name: DeleteClub :one
DELETE FROM clubs
WHERE id = $1
RETURNING id, name, geologist_name, icon_svg
`

func (q *Queries) DeleteClub(ctx context.Context, id string) (Club, error) {
	row := q.db.QueryRow(ctx, deleteClub, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.IconSvg,
	)
	return i, err
}

const getClub = `-- name: GetClub :many
SELECT
    c.id AS club_id,
    c.name AS club_name,
    c.geologist_name AS club_geologist_name,
    c.icon_svg AS club_icon_svg,
    pcm.player_id AS player_id
FROM clubs c
LEFT JOIN player_club_membership pcm ON pcm.club_id = c.id
WHERE c.id = $1
`

type GetClubRow struct {
	ClubID            string      `json:"club_id"`
	ClubName          string      `json:"club_name"`
	ClubGeologistName pgtype.Text `json:"club_geologist_name"`
	ClubIconSvg       pgtype.Text `json:"club_icon_svg"`
	PlayerID          *string     `json:"player_id"`
}

func (q *Queries) GetClub(ctx context.Context, id string) ([]GetClubRow, error) {
	rows, err := q.db.Query(ctx, getClub, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClubRow{}
	for rows.Next() {
		var i GetClubRow
		if err := rows.Scan(
			&i.ClubID,
			&i.ClubName,
			&i.ClubGeologistName,
			&i.ClubIconSvg,
			&i.PlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubs = `-- name: ListClubs :many
SELECT
    c.id AS club_id,
    c.name AS club_name,
    c.geologist_name AS club_geologist_name,
    c.icon_svg AS club_icon_svg,
    pcm.player_id AS player_id
FROM clubs c
LEFT JOIN player_club_membership pcm ON pcm.club_id = c.id
`

type ListClubsRow struct {
	ClubID            string      `json:"club_id"`
	ClubName          string      `json:"club_name"`
	ClubGeologistName pgtype.Text `json:"club_geologist_name"`
	ClubIconSvg       pgtype.Text `json:"club_icon_svg"`
	PlayerID          *string     `json:"player_id"`
}

func (q *Queries) ListClubs(ctx context.Context) ([]ListClubsRow, error) {
	rows, err := q.db.Query(ctx, listClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubsRow{}
	for rows.Next() {
		var i ListClubsRow
		if err := rows.Scan(
			&i.ClubID,
			&i.ClubName,
			&i.ClubGeologistName,
			&i.ClubIconSvg,
			&i.PlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClubMember = `-- name: RemoveClubMember :exec
DELETE FROM player_club_membership
WHERE club_id = $1 AND player_id = $2
`

type RemoveClubMemberParams struct {
	ClubID   string `json:"club_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) RemoveClubMember(ctx context.Context, arg RemoveClubMemberParams) error {
	_, err := q.db.Exec(ctx, removeClubMember, arg.ClubID, arg.PlayerID)
	return err
}

const updateClubIcon = `-- name: UpdateClubIcon :one
UPDATE clubs
SET icon_svg = $2
WHERE id = $1
RETURNING id, name, geologist_name, icon_svg
`

type UpdateClubIconParams struct {
	ID      string      `json:"id"`
	IconSvg pgtype.Text `json:"icon_svg"`
}

func (q *Queries) UpdateClubIcon(ctx context.Context, arg UpdateClubIconParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClubIcon, arg.ID, arg.IconSvg)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.IconSvg,
	)
	return i, err
}

const updateClubName = `-- name: UpdateClubName :one
UPDATE clubs
SET name = $2
WHERE id = $1
RETURNING id, name, geologist_name, icon_svg
`

type UpdateClubNameParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateClubName(ctx context.Context, arg UpdateClubNameParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClubName, arg.ID, arg.Name)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.IconSvg,
	)
	return i, err
}
