// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corrections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

const countCorrectionsFromDate = `-- name: CountCorrectionsFromDate :one
SELECT COUNT(*) AS count
FROM corrections
WHERE date >= $1
`

func (q *Queries) CountCorrectionsFromDate(ctx context.Context, date pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countCorrectionsFromDate, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCorrection = `-- name: CreateCorrection :one
INSERT INTO corrections (id, player_id, discriminator, diff)
VALUES ($1, $2, $3, $4) RETURNING id, player_id, discriminator, diff, date
`

type CreateCorrectionParams struct {
	ID            id.ID   `json:"id"`
	PlayerID      id.ID   `json:"player_id"`
	Discriminator string  `json:"discriminator"`
	Diff          float64 `json:"diff"`
}

func (q *Queries) CreateCorrection(ctx context.Context, arg CreateCorrectionParams) (Correction, error) {
	row := q.db.QueryRow(ctx, createCorrection,
		arg.ID,
		arg.PlayerID,
		arg.Discriminator,
		arg.Diff,
	)
	var i Correction
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Discriminator,
		&i.Diff,
		&i.Date,
	)
	return i, err
}

const deleteGlobalSettlementsFromDate = `-- name: DeleteGlobalSettlementsFromDate :exec
DELETE FROM arena_settlements
WHERE arena_id = 'a2ea0000-0000-0000-0000-000000000001' AND date >= $1
`

// Single delete covering match, market, AND correction settlements of the
// global arena (corrections touch only the global arena; «Синие люди»'s
// markets settle there too since it is their club's main arena — ADR-36).
// Other clubs' market rows are removed by the per-market deletes in
// UnsettleMarketsFromDate, in each market's own arena.
// Called at the start of RecalculateFrom.
func (q *Queries) DeleteGlobalSettlementsFromDate(ctx context.Context, date pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteGlobalSettlementsFromDate, date)
	return err
}

const getCorrectionsFromDate = `-- name: GetCorrectionsFromDate :many
SELECT id, player_id, discriminator, diff, date FROM corrections WHERE date >= $1 ORDER BY date ASC, id ASC
`

func (q *Queries) GetCorrectionsFromDate(ctx context.Context, date pgtype.Timestamptz) ([]Correction, error) {
	rows, err := q.db.Query(ctx, getCorrectionsFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correction{}
	for rows.Next() {
		var i Correction
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Discriminator,
			&i.Diff,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerLatestArenaStateBeforeCorrection = `-- name: GetPlayerLatestArenaStateBeforeCorrection :one
SELECT gas.rating_after AS rating, gas.elo_after AS elo, gas.league
FROM arena_settlements gas
WHERE gas.arena_id = $1
  AND gas.player_id = $2
  AND (gas.date < $3
       OR (gas.date = $3 AND gas.discriminator != 'correction')
       OR (gas.date = $3 AND gas.discriminator = 'correction' AND gas.correction_id < $4))
ORDER BY gas.date DESC, gas.id DESC
LIMIT 1
`

type GetPlayerLatestArenaStateBeforeCorrectionParams struct {
	ArenaID      id.ID              `json:"arena_id"`
	PlayerID     id.ID              `json:"player_id"`
	Date         pgtype.Timestamptz `json:"date"`
	CorrectionID *id.ID             `json:"correction_id"`
}

type GetPlayerLatestArenaStateBeforeCorrectionRow struct {
	Rating float64     `json:"rating"`
	Elo    float64     `json:"elo"`
	League pgtype.Text `json:"league"`
}

// Picks the latest settlement before correction $4 for player $2 at date $3
// in arena $1. Same-date matches/markets (discriminator != 'correction') come
// before corrections. Earlier same-date corrections (correction_id < $4) are
// also included.
func (q *Queries) GetPlayerLatestArenaStateBeforeCorrection(ctx context.Context, arg GetPlayerLatestArenaStateBeforeCorrectionParams) (GetPlayerLatestArenaStateBeforeCorrectionRow, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestArenaStateBeforeCorrection,
		arg.ArenaID,
		arg.PlayerID,
		arg.Date,
		arg.CorrectionID,
	)
	var i GetPlayerLatestArenaStateBeforeCorrectionRow
	err := row.Scan(&i.Rating, &i.Elo, &i.League)
	return i, err
}

const listCorrectionsByIDs = `-- name: ListCorrectionsByIDs :many
SELECT c.id, c.player_id, c.diff, c.date, p.name AS player_name
FROM corrections c
JOIN players p ON p.id = c.player_id
WHERE c.id = ANY($1::uuid[])
`

type ListCorrectionsByIDsRow struct {
	ID         id.ID              `json:"id"`
	PlayerID   id.ID              `json:"player_id"`
	Diff       float64            `json:"diff"`
	Date       pgtype.Timestamptz `json:"date"`
	PlayerName string             `json:"player_name"`
}

// Payload rows for the feed's correction events (ADR-32), for an explicit id
// set selected by ListArenaFeedEvents.
func (q *Queries) ListCorrectionsByIDs(ctx context.Context, ids []id.ID) ([]ListCorrectionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listCorrectionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCorrectionsByIDsRow{}
	for rows.Next() {
		var i ListCorrectionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Diff,
			&i.Date,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArenaSettlementByCorrection = `-- name: UpsertArenaSettlementByCorrection :exec
INSERT INTO arena_settlements
    (id, arena_id, player_id, date, rating_after, elo_after, discriminator, correction_id,
     elo_staked, elo_earned, rating_staked, rating_earned, league)
VALUES ($1, $2, $3, $4, $5, $6, 'correction', $7, 0, 0, $8, $9, $10)
ON CONFLICT (arena_id, correction_id, player_id) WHERE correction_id IS NOT NULL
DO UPDATE SET rating_after  = EXCLUDED.rating_after,
              elo_after     = EXCLUDED.elo_after,
              date          = EXCLUDED.date,
              rating_staked = EXCLUDED.rating_staked,
              rating_earned = EXCLUDED.rating_earned,
              league        = EXCLUDED.league
`

type UpsertArenaSettlementByCorrectionParams struct {
	ID           id.ID              `json:"id"`
	ArenaID      id.ID              `json:"arena_id"`
	PlayerID     id.ID              `json:"player_id"`
	Date         pgtype.Timestamptz `json:"date"`
	RatingAfter  float64            `json:"rating_after"`
	EloAfter     float64            `json:"elo_after"`
	CorrectionID *id.ID             `json:"correction_id"`
	RatingStaked float64            `json:"rating_staked"`
	RatingEarned float64            `json:"rating_earned"`
	League       pgtype.Text        `json:"league"`
}

func (q *Queries) UpsertArenaSettlementByCorrection(ctx context.Context, arg UpsertArenaSettlementByCorrectionParams) error {
	_, err := q.db.Exec(ctx, upsertArenaSettlementByCorrection,
		arg.ID,
		arg.ArenaID,
		arg.PlayerID,
		arg.Date,
		arg.RatingAfter,
		arg.EloAfter,
		arg.CorrectionID,
		arg.RatingStaked,
		arg.RatingEarned,
		arg.League,
	)
	return err
}
