// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corrections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCorrection = `-- name: CreateCorrection :one
INSERT INTO corrections (player_id, discriminator, diff)
VALUES ($1, $2, $3) RETURNING id, player_id, discriminator, diff, date
`

type CreateCorrectionParams struct {
	PlayerID      int32   `json:"player_id"`
	Discriminator string  `json:"discriminator"`
	Diff          float64 `json:"diff"`
}

func (q *Queries) CreateCorrection(ctx context.Context, arg CreateCorrectionParams) (Correction, error) {
	row := q.db.QueryRow(ctx, createCorrection, arg.PlayerID, arg.Discriminator, arg.Diff)
	var i Correction
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Discriminator,
		&i.Diff,
		&i.Date,
	)
	return i, err
}

const deleteAllSettlementsFromDate = `-- name: DeleteAllSettlementsFromDate :exec
DELETE FROM global_arena_settlement WHERE date >= $1
`

// Single delete covering match, market, AND correction settlements.
// Called at the start of RecalculateFrom so per-market deletes in
// UnsettleMarketsFromDate become harmless no-ops.
func (q *Queries) DeleteAllSettlementsFromDate(ctx context.Context, date pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAllSettlementsFromDate, date)
	return err
}

const getCorrectionsFromDate = `-- name: GetCorrectionsFromDate :many
SELECT id, player_id, discriminator, diff, date FROM corrections WHERE date >= $1 ORDER BY date ASC, id ASC
`

func (q *Queries) GetCorrectionsFromDate(ctx context.Context, date pgtype.Timestamptz) ([]Correction, error) {
	rows, err := q.db.Query(ctx, getCorrectionsFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correction{}
	for rows.Next() {
		var i Correction
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Discriminator,
			&i.Diff,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerLatestGlobalStateBeforeCorrection = `-- name: GetPlayerLatestGlobalStateBeforeCorrection :one
SELECT gas.new_rating AS rating, gas.new_elo AS elo, gas.league
FROM global_arena_settlement gas
WHERE gas.player_id = $1
  AND (gas.date < $2
       OR (gas.date = $2 AND gas.discriminator != 'correction')
       OR (gas.date = $2 AND gas.discriminator = 'correction' AND gas.correction_id < $3))
ORDER BY gas.date DESC, gas.id DESC
LIMIT 1
`

type GetPlayerLatestGlobalStateBeforeCorrectionParams struct {
	PlayerID     int32              `json:"player_id"`
	Date         pgtype.Timestamptz `json:"date"`
	CorrectionID pgtype.Int4        `json:"correction_id"`
}

type GetPlayerLatestGlobalStateBeforeCorrectionRow struct {
	Rating float64 `json:"rating"`
	Elo    float64 `json:"elo"`
	League string  `json:"league"`
}

// Picks the latest settlement before correction $3 for player $1 at date $2.
// Same-date matches/markets (discriminator != 'correction') come before corrections.
// Earlier same-date corrections (correction_id < $3) are also included.
func (q *Queries) GetPlayerLatestGlobalStateBeforeCorrection(ctx context.Context, arg GetPlayerLatestGlobalStateBeforeCorrectionParams) (GetPlayerLatestGlobalStateBeforeCorrectionRow, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestGlobalStateBeforeCorrection, arg.PlayerID, arg.Date, arg.CorrectionID)
	var i GetPlayerLatestGlobalStateBeforeCorrectionRow
	err := row.Scan(&i.Rating, &i.Elo, &i.League)
	return i, err
}

const upsertGlobalArenaSettlementByCorrection = `-- name: UpsertGlobalArenaSettlementByCorrection :exec
INSERT INTO global_arena_settlement
    (player_id, date, new_rating, new_elo, discriminator, correction_id,
     elo_staked, elo_earned, rating_staked, rating_earned, league)
VALUES ($1, $2, $3, $4, 'correction', $5, 0, 0, $6, $7, $8)
ON CONFLICT (correction_id, player_id) WHERE correction_id IS NOT NULL
DO UPDATE SET new_rating    = EXCLUDED.new_rating,
              new_elo       = EXCLUDED.new_elo,
              date          = EXCLUDED.date,
              rating_staked = EXCLUDED.rating_staked,
              rating_earned = EXCLUDED.rating_earned,
              league        = EXCLUDED.league
`

type UpsertGlobalArenaSettlementByCorrectionParams struct {
	PlayerID     int32              `json:"player_id"`
	Date         pgtype.Timestamptz `json:"date"`
	NewRating    float64            `json:"new_rating"`
	NewElo       float64            `json:"new_elo"`
	CorrectionID pgtype.Int4        `json:"correction_id"`
	RatingStaked float64            `json:"rating_staked"`
	RatingEarned float64            `json:"rating_earned"`
	League       string             `json:"league"`
}

func (q *Queries) UpsertGlobalArenaSettlementByCorrection(ctx context.Context, arg UpsertGlobalArenaSettlementByCorrectionParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalArenaSettlementByCorrection,
		arg.PlayerID,
		arg.Date,
		arg.NewRating,
		arg.NewElo,
		arg.CorrectionID,
		arg.RatingStaked,
		arg.RatingEarned,
		arg.League,
	)
	return err
}
