// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

const addGame = `-- name: AddGame :one
INSERT INTO games (id, name_en, name_ru, alias, bgg_id, tesera_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, name_en, name_ru, alias, bgg_id, tesera_id, name
`

type AddGameParams struct {
	ID       id.ID       `json:"id"`
	NameEn   pgtype.Text `json:"name_en"`
	NameRu   pgtype.Text `json:"name_ru"`
	Alias    pgtype.Text `json:"alias"`
	BggID    pgtype.Int4 `json:"bgg_id"`
	TeseraID pgtype.Int4 `json:"tesera_id"`
}

func (q *Queries) AddGame(ctx context.Context, arg AddGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, addGame,
		arg.ID,
		arg.NameEn,
		arg.NameRu,
		arg.Alias,
		arg.BggID,
		arg.TeseraID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameRu,
		&i.Alias,
		&i.BggID,
		&i.TeseraID,
		&i.Name,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :one
DELETE FROM games
WHERE id = $1
RETURNING id, name_en, name_ru, alias, bgg_id, tesera_id, name
`

func (q *Queries) DeleteGame(ctx context.Context, argID id.ID) (Game, error) {
	row := q.db.QueryRow(ctx, deleteGame, argID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameRu,
		&i.Alias,
		&i.BggID,
		&i.TeseraID,
		&i.Name,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, name_en, name_ru, alias, bgg_id, tesera_id, name FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, argID id.ID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, argID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameRu,
		&i.Alias,
		&i.BggID,
		&i.TeseraID,
		&i.Name,
	)
	return i, err
}

const getGameByName = `-- name: GetGameByName :one
SELECT id, name_en, name_ru, alias, bgg_id, tesera_id, name FROM games
WHERE name = $1
`

func (q *Queries) GetGameByName(ctx context.Context, name string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByName, name)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameRu,
		&i.Alias,
		&i.BggID,
		&i.TeseraID,
		&i.Name,
	)
	return i, err
}

const listGamesOrderedByLastPlayed = `-- name: ListGamesOrderedByLastPlayed :many
SELECT
	g.id AS id,
	g.name AS name,
	g.name_en AS name_en,
	g.name_ru AS name_ru,
	g.alias AS alias,
	g.bgg_id AS bgg_id,
	g.tesera_id AS tesera_id,
	COUNT(m.id) AS total_matches
FROM games g
LEFT JOIN matches m ON m.game_id = g.id
GROUP BY g.id, g.name, g.name_en, g.name_ru, g.alias, g.bgg_id, g.tesera_id
ORDER BY MAX(m.date) DESC
`

type ListGamesOrderedByLastPlayedRow struct {
	ID           id.ID       `json:"id"`
	Name         string      `json:"name"`
	NameEn       pgtype.Text `json:"name_en"`
	NameRu       pgtype.Text `json:"name_ru"`
	Alias        pgtype.Text `json:"alias"`
	BggID        pgtype.Int4 `json:"bgg_id"`
	TeseraID     pgtype.Int4 `json:"tesera_id"`
	TotalMatches int64       `json:"total_matches"`
}

func (q *Queries) ListGamesOrderedByLastPlayed(ctx context.Context) ([]ListGamesOrderedByLastPlayedRow, error) {
	rows, err := q.db.Query(ctx, listGamesOrderedByLastPlayed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesOrderedByLastPlayedRow{}
	for rows.Next() {
		var i ListGamesOrderedByLastPlayedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEn,
			&i.NameRu,
			&i.Alias,
			&i.BggID,
			&i.TeseraID,
			&i.TotalMatches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesWithoutTeseraRef = `-- name: ListGamesWithoutTeseraRef :many
SELECT id, name_en, name_ru, alias, bgg_id, tesera_id, name FROM games
WHERE tesera_id IS NULL
ORDER BY name
`

func (q *Queries) ListGamesWithoutTeseraRef(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesWithoutTeseraRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameRu,
			&i.Alias,
			&i.BggID,
			&i.TeseraID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET	name_en = $2,
	name_ru = $3,
	alias = $4,
	bgg_id = $5,
	tesera_id = $6
WHERE id = $1
RETURNING id, name_en, name_ru, alias, bgg_id, tesera_id, name
`

type UpdateGameParams struct {
	ID       id.ID       `json:"id"`
	NameEn   pgtype.Text `json:"name_en"`
	NameRu   pgtype.Text `json:"name_ru"`
	Alias    pgtype.Text `json:"alias"`
	BggID    pgtype.Int4 `json:"bgg_id"`
	TeseraID pgtype.Int4 `json:"tesera_id"`
}

// `name` is generated (migration 063) and follows the three source names.
func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.NameEn,
		arg.NameRu,
		arg.Alias,
		arg.BggID,
		arg.TeseraID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameRu,
		&i.Alias,
		&i.BggID,
		&i.TeseraID,
		&i.Name,
	)
	return i, err
}
