// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"
)

const addGamesIfNotExists = `-- name: AddGamesIfNotExists :many
INSERT INTO games (name)
SELECT unnest($1::text[]) AS name
ON CONFLICT (name) DO NOTHING
RETURNING id, name
`

func (q *Queries) AddGamesIfNotExists(ctx context.Context, dollar_1 []string) ([]Game, error) {
	rows, err := q.db.Query(ctx, addGamesIfNotExists, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesOrderedByLastPlayed = `-- name: ListGamesOrderedByLastPlayed :many
SELECT
	g.id AS id,
	g.name AS name,
	COUNT(m.id) AS total_matches
FROM games g
LEFT JOIN matches m ON m.game_id = g.id
GROUP BY g.id, g.name
ORDER BY MAX(m.date) DESC
`

type ListGamesOrderedByLastPlayedRow struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	TotalMatches int64  `json:"total_matches"`
}

func (q *Queries) ListGamesOrderedByLastPlayed(ctx context.Context) ([]ListGamesOrderedByLastPlayedRow, error) {
	rows, err := q.db.Query(ctx, listGamesOrderedByLastPlayed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesOrderedByLastPlayedRow{}
	for rows.Next() {
		var i ListGamesOrderedByLastPlayedRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalMatches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
