// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (id, market_type, starts_at, closes_at, created_by, liquidity_b)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, market_type, status, starts_at, closes_at, created_by, created_at, resolved_at, resolution_match_id, resolution_outcome, betting_closed_at, liquidity_b
`

type CreateMarketParams struct {
	ID         string             `json:"id"`
	MarketType string             `json:"market_type"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	ClosesAt   pgtype.Timestamptz `json:"closes_at"`
	CreatedBy  string             `json:"created_by"`
	LiquidityB float64            `json:"liquidity_b"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error) {
	row := q.db.QueryRow(ctx, createMarket,
		arg.ID,
		arg.MarketType,
		arg.StartsAt,
		arg.ClosesAt,
		arg.CreatedBy,
		arg.LiquidityB,
	)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.MarketType,
		&i.Status,
		&i.StartsAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolutionMatchID,
		&i.ResolutionOutcome,
		&i.BettingClosedAt,
		&i.LiquidityB,
	)
	return i, err
}

const createMarketGuarantors = `-- name: CreateMarketGuarantors :exec
INSERT INTO market_guarantors (market_id, player_id)
SELECT $1, t.player_id FROM unnest($2::uuid[]) AS t(player_id)
`

type CreateMarketGuarantorsParams struct {
	MarketID  string   `json:"market_id"`
	PlayerIds []string `json:"player_ids"`
}

// Bulk-inserts the market's guarantor players (zero-sum counterparties).
func (q *Queries) CreateMarketGuarantors(ctx context.Context, arg CreateMarketGuarantorsParams) error {
	_, err := q.db.Exec(ctx, createMarketGuarantors, arg.MarketID, arg.PlayerIds)
	return err
}

const createMatchWinnerParams = `-- name: CreateMatchWinnerParams :exec
INSERT INTO market_match_winner_params (market_id, target_player_ids, allow_other_players, game_ids)
VALUES ($1, $2, $3, $4)
`

type CreateMatchWinnerParamsParams struct {
	MarketID          string   `json:"market_id"`
	TargetPlayerIds   []string `json:"target_player_ids"`
	AllowOtherPlayers bool     `json:"allow_other_players"`
	GameIds           []string `json:"game_ids"`
}

func (q *Queries) CreateMatchWinnerParams(ctx context.Context, arg CreateMatchWinnerParamsParams) error {
	_, err := q.db.Exec(ctx, createMatchWinnerParams,
		arg.MarketID,
		arg.TargetPlayerIds,
		arg.AllowOtherPlayers,
		arg.GameIds,
	)
	return err
}

const createOtherOutcome = `-- name: CreateOtherOutcome :exec
INSERT INTO market_outcomes (market_id, kind, player_id) VALUES ($1, 'other', NULL)
`

// The "other" outcome of a match_winner market: tie at first place or a
// non-target winner.
func (q *Queries) CreateOtherOutcome(ctx context.Context, marketID string) error {
	_, err := q.db.Exec(ctx, createOtherOutcome, marketID)
	return err
}

const createPlayerOutcomes = `-- name: CreatePlayerOutcomes :exec
INSERT INTO market_outcomes (market_id, kind, player_id)
SELECT $1, 'player', t.player_id
FROM unnest($2::uuid[]) AS t(player_id)
`

type CreatePlayerOutcomesParams struct {
	MarketID  string   `json:"market_id"`
	PlayerIds []string `json:"player_ids"`
}

// Bulk-inserts the per-target "player wins" outcomes of a match_winner market.
func (q *Queries) CreatePlayerOutcomes(ctx context.Context, arg CreatePlayerOutcomesParams) error {
	_, err := q.db.Exec(ctx, createPlayerOutcomes, arg.MarketID, arg.PlayerIds)
	return err
}

const createWinStreakParams = `-- name: CreateWinStreakParams :exec
INSERT INTO market_win_streak_params (market_id, target_player_id, game_ids, wins_required, max_losses)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWinStreakParamsParams struct {
	MarketID       string      `json:"market_id"`
	TargetPlayerID string      `json:"target_player_id"`
	GameIds        []string    `json:"game_ids"`
	WinsRequired   int32       `json:"wins_required"`
	MaxLosses      pgtype.Int4 `json:"max_losses"`
}

func (q *Queries) CreateWinStreakParams(ctx context.Context, arg CreateWinStreakParamsParams) error {
	_, err := q.db.Exec(ctx, createWinStreakParams,
		arg.MarketID,
		arg.TargetPlayerID,
		arg.GameIds,
		arg.WinsRequired,
		arg.MaxLosses,
	)
	return err
}

const createYesNoOutcomes = `-- name: CreateYesNoOutcomes :exec
INSERT INTO market_outcomes (market_id, kind, player_id) VALUES ($1, 'yes', NULL), ($1, 'no', NULL)
`

// The two fixed Да/Нет outcomes of a win_streak market.
func (q *Queries) CreateYesNoOutcomes(ctx context.Context, marketID string) error {
	_, err := q.db.Exec(ctx, createYesNoOutcomes, marketID)
	return err
}

const deleteGlobalArenaSettlementByMarket = `-- name: DeleteGlobalArenaSettlementByMarket :exec
DELETE FROM global_arena_settlement
WHERE market_id = $1 AND discriminator IN ('market', 'market_guarantor')
`

// Removes both buyer ('market') and guarantor ('market_guarantor') settlement
// rows for a market (used by unsettle/recalculation).
func (q *Queries) DeleteGlobalArenaSettlementByMarket(ctx context.Context, marketID *string) error {
	_, err := q.db.Exec(ctx, deleteGlobalArenaSettlementByMarket, marketID)
	return err
}

const deleteMarket = `-- name: DeleteMarket :exec
DELETE FROM markets WHERE id = $1
`

func (q *Queries) DeleteMarket(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMarket, id)
	return err
}

const getBetsAggregatedByOutcome = `-- name: GetBetsAggregatedByOutcome :many
SELECT player_id, outcome, SUM(cost)::float8 AS total_cost
FROM bets
WHERE market_id = $1
GROUP BY player_id, outcome
ORDER BY player_id, outcome
`

type GetBetsAggregatedByOutcomeRow struct {
	PlayerID  string  `json:"player_id"`
	Outcome   string  `json:"outcome"`
	TotalCost float64 `json:"total_cost"`
}

func (q *Queries) GetBetsAggregatedByOutcome(ctx context.Context, marketID string) ([]GetBetsAggregatedByOutcomeRow, error) {
	rows, err := q.db.Query(ctx, getBetsAggregatedByOutcome, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBetsAggregatedByOutcomeRow{}
	for rows.Next() {
		var i GetBetsAggregatedByOutcomeRow
		if err := rows.Scan(&i.PlayerID, &i.Outcome, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBetsForSettlement = `-- name: GetBetsForSettlement :many
SELECT player_id, outcome, cost, shares
FROM bets
WHERE market_id = $1
ORDER BY placed_at, id
`

type GetBetsForSettlementRow struct {
	PlayerID string  `json:"player_id"`
	Outcome  string  `json:"outcome"`
	Cost     float64 `json:"cost"`
	Shares   float64 `json:"shares"`
}

// Per-buy rows (each carries the shares bought) used by share settlement.
func (q *Queries) GetBetsForSettlement(ctx context.Context, marketID string) ([]GetBetsForSettlementRow, error) {
	rows, err := q.db.Query(ctx, getBetsForSettlement, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBetsForSettlementRow{}
	for rows.Next() {
		var i GetBetsForSettlementRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Outcome,
			&i.Cost,
			&i.Shares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBetsOnMarketPlacedBetween = `-- name: GetBetsOnMarketPlacedBetween :many
SELECT id, player_id, placed_at FROM bets
WHERE market_id = $1
  AND placed_at >= $2
  AND placed_at < $3
`

type GetBetsOnMarketPlacedBetweenParams struct {
	MarketID   string             `json:"market_id"`
	PlacedAt   pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2 pgtype.Timestamptz `json:"placed_at_2"`
}

type GetBetsOnMarketPlacedBetweenRow struct {
	ID       string             `json:"id"`
	PlayerID string             `json:"player_id"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) GetBetsOnMarketPlacedBetween(ctx context.Context, arg GetBetsOnMarketPlacedBetweenParams) ([]GetBetsOnMarketPlacedBetweenRow, error) {
	rows, err := q.db.Query(ctx, getBetsOnMarketPlacedBetween, arg.MarketID, arg.PlacedAt, arg.PlacedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBetsOnMarketPlacedBetweenRow{}
	for rows.Next() {
		var i GetBetsOnMarketPlacedBetweenRow
		if err := rows.Scan(&i.ID, &i.PlayerID, &i.PlacedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarket = `-- name: GetMarket :one
SELECT
    om.id, om.market_type, om.status, om.resolution_outcome, om.starts_at, om.closes_at,
    om.created_by, om.created_at, om.resolved_at, om.resolution_match_id, om.betting_closed_at,
    om.liquidity_b,
    mwp.target_player_ids,
    mwp.allow_other_players,
    mwp.game_ids AS mw_game_ids,
    wsp.target_player_id AS ws_target_player_id,
    wsp.game_ids AS ws_game_ids,
    wsp.wins_required,
    wsp.max_losses
FROM markets om
LEFT JOIN market_match_winner_params mwp ON mwp.market_id = om.id
LEFT JOIN market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.id = $1
`

type GetMarketRow struct {
	ID                string             `json:"id"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	ResolutionOutcome *string            `json:"resolution_outcome"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID *string            `json:"resolution_match_id"`
	BettingClosedAt   pgtype.Timestamptz `json:"betting_closed_at"`
	LiquidityB        float64            `json:"liquidity_b"`
	TargetPlayerIds   []string           `json:"target_player_ids"`
	AllowOtherPlayers pgtype.Bool        `json:"allow_other_players"`
	MwGameIds         []string           `json:"mw_game_ids"`
	WsTargetPlayerID  *string            `json:"ws_target_player_id"`
	WsGameIds         []string           `json:"ws_game_ids"`
	WinsRequired      pgtype.Int4        `json:"wins_required"`
	MaxLosses         pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) GetMarket(ctx context.Context, id string) (GetMarketRow, error) {
	row := q.db.QueryRow(ctx, getMarket, id)
	var i GetMarketRow
	err := row.Scan(
		&i.ID,
		&i.MarketType,
		&i.Status,
		&i.ResolutionOutcome,
		&i.StartsAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolutionMatchID,
		&i.BettingClosedAt,
		&i.LiquidityB,
		&i.TargetPlayerIds,
		&i.AllowOtherPlayers,
		&i.MwGameIds,
		&i.WsTargetPlayerID,
		&i.WsGameIds,
		&i.WinsRequired,
		&i.MaxLosses,
	)
	return i, err
}

const getMarketBetsForPriceHistory = `-- name: GetMarketBetsForPriceHistory :many
SELECT outcome, shares, placed_at
FROM bets
WHERE market_id = $1
ORDER BY placed_at, id
`

type GetMarketBetsForPriceHistoryRow struct {
	Outcome  string             `json:"outcome"`
	Shares   float64            `json:"shares"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

// Ordered bet stream used to reconstruct the market's price history by
// replaying the LMSR from its creation state q=0.
func (q *Queries) GetMarketBetsForPriceHistory(ctx context.Context, marketID string) ([]GetMarketBetsForPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMarketBetsForPriceHistory, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketBetsForPriceHistoryRow{}
	for rows.Next() {
		var i GetMarketBetsForPriceHistoryRow
		if err := rows.Scan(&i.Outcome, &i.Shares, &i.PlacedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketGuarantorPayouts = `-- name: GetMarketGuarantorPayouts :many
SELECT bsd.player_id, p.name AS player_name,
       (-bsd.elo_staked)::float8 AS staked, bsd.elo_earned AS earned
FROM market_guarantors g
JOIN global_arena_settlement bsd ON bsd.market_id = g.market_id AND bsd.player_id = g.player_id
JOIN players p ON p.id = g.player_id
WHERE g.market_id = $1 AND bsd.discriminator = 'market_guarantor'
ORDER BY (bsd.elo_earned + bsd.elo_staked) DESC
`

type GetMarketGuarantorPayoutsRow struct {
	PlayerID   string  `json:"player_id"`
	PlayerName string  `json:"player_name"`
	Staked     float64 `json:"staked"`
	Earned     float64 `json:"earned"`
}

// Guarantor-role settlement rows (discriminator 'market_guarantor') — the
// per-guarantor payout rollup. A player who is both buyer and guarantor has a
// separate buyer row (discriminator 'market'), so their entry here carries only
// the house result (ADR-10).
func (q *Queries) GetMarketGuarantorPayouts(ctx context.Context, marketID string) ([]GetMarketGuarantorPayoutsRow, error) {
	rows, err := q.db.Query(ctx, getMarketGuarantorPayouts, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketGuarantorPayoutsRow{}
	for rows.Next() {
		var i GetMarketGuarantorPayoutsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Staked,
			&i.Earned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketResolvedAt = `-- name: GetMarketResolvedAt :one
SELECT resolved_at FROM markets WHERE id = $1
`

func (q *Queries) GetMarketResolvedAt(ctx context.Context, id string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMarketResolvedAt, id)
	var resolved_at pgtype.Timestamptz
	err := row.Scan(&resolved_at)
	return resolved_at, err
}

const getMarketsForUnsettle = `-- name: GetMarketsForUnsettle :many
SELECT DISTINCT om.id
FROM markets om
WHERE om.status IN ('resolved', 'cancelled')
  AND om.resolved_at >= $1
`

func (q *Queries) GetMarketsForUnsettle(ctx context.Context, resolvedAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, getMarketsForUnsettle, resolvedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketsForUnsettleWithResolvedAt = `-- name: GetMarketsForUnsettleWithResolvedAt :many
SELECT id, resolved_at, betting_closed_at
FROM markets
WHERE status IN ('resolved', 'cancelled')
  AND resolved_at >= $1
`

type GetMarketsForUnsettleWithResolvedAtRow struct {
	ID              string             `json:"id"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	BettingClosedAt pgtype.Timestamptz `json:"betting_closed_at"`
}

// Returns resolved_at and betting_closed_at for the history conflict validation.
// betting_closed_at is a user event timestamp — preserved even after unsettling.
func (q *Queries) GetMarketsForUnsettleWithResolvedAt(ctx context.Context, resolvedAt pgtype.Timestamptz) ([]GetMarketsForUnsettleWithResolvedAtRow, error) {
	rows, err := q.db.Query(ctx, getMarketsForUnsettleWithResolvedAt, resolvedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketsForUnsettleWithResolvedAtRow{}
	for rows.Next() {
		var i GetMarketsForUnsettleWithResolvedAtRow
		if err := rows.Scan(&i.ID, &i.ResolvedAt, &i.BettingClosedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchWinnerParams = `-- name: GetMatchWinnerParams :one
SELECT market_id, game_ids, target_player_ids, allow_other_players FROM market_match_winner_params WHERE market_id = $1
`

func (q *Queries) GetMatchWinnerParams(ctx context.Context, marketID string) (MarketMatchWinnerParam, error) {
	row := q.db.QueryRow(ctx, getMatchWinnerParams, marketID)
	var i MarketMatchWinnerParam
	err := row.Scan(
		&i.MarketID,
		&i.GameIds,
		&i.TargetPlayerIds,
		&i.AllowOtherPlayers,
	)
	return i, err
}

const getNearestMarketExpiry = `-- name: GetNearestMarketExpiry :one
SELECT closes_at FROM markets
WHERE status IN ('open', 'betting_closed')
ORDER BY closes_at ASC
LIMIT 1
`

func (q *Queries) GetNearestMarketExpiry(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNearestMarketExpiry)
	var closes_at pgtype.Timestamptz
	err := row.Scan(&closes_at)
	return closes_at, err
}

const getPlayerBetLimit = `-- name: GetPlayerBetLimit :one
SELECT bet_limit FROM players WHERE id = $1
`

func (q *Queries) GetPlayerBetLimit(ctx context.Context, id string) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerBetLimit, id)
	var bet_limit float64
	err := row.Scan(&bet_limit)
	return bet_limit, err
}

const getPlayerBetsAggregatedForMarket = `-- name: GetPlayerBetsAggregatedForMarket :many
SELECT outcome, SUM(cost)::float8 AS total_cost
FROM bets
WHERE market_id = $1 AND player_id = $2
GROUP BY outcome
`

type GetPlayerBetsAggregatedForMarketParams struct {
	MarketID string `json:"market_id"`
	PlayerID string `json:"player_id"`
}

type GetPlayerBetsAggregatedForMarketRow struct {
	Outcome   string  `json:"outcome"`
	TotalCost float64 `json:"total_cost"`
}

func (q *Queries) GetPlayerBetsAggregatedForMarket(ctx context.Context, arg GetPlayerBetsAggregatedForMarketParams) ([]GetPlayerBetsAggregatedForMarketRow, error) {
	rows, err := q.db.Query(ctx, getPlayerBetsAggregatedForMarket, arg.MarketID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerBetsAggregatedForMarketRow{}
	for rows.Next() {
		var i GetPlayerBetsAggregatedForMarketRow
		if err := rows.Scan(&i.Outcome, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerBetsForMarket = `-- name: GetPlayerBetsForMarket :many
SELECT outcome, cost, shares
FROM bets
WHERE market_id = $1 AND player_id = $2
ORDER BY placed_at, id
`

type GetPlayerBetsForMarketParams struct {
	MarketID string `json:"market_id"`
	PlayerID string `json:"player_id"`
}

type GetPlayerBetsForMarketRow struct {
	Outcome string  `json:"outcome"`
	Cost    float64 `json:"cost"`
	Shares  float64 `json:"shares"`
}

// Per-buy rows for one player, used to show shares held / elo spent on the detail page.
func (q *Queries) GetPlayerBetsForMarket(ctx context.Context, arg GetPlayerBetsForMarketParams) ([]GetPlayerBetsForMarketRow, error) {
	rows, err := q.db.Query(ctx, getPlayerBetsForMarket, arg.MarketID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerBetsForMarketRow{}
	for rows.Next() {
		var i GetPlayerBetsForMarketRow
		if err := rows.Scan(&i.Outcome, &i.Cost, &i.Shares); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerReservedAmount = `-- name: GetPlayerReservedAmount :one
SELECT COALESCE(SUM(ob.cost), 0)::float8 AS reserved
FROM bets ob
JOIN markets om ON om.id = ob.market_id
WHERE ob.player_id = $1 AND om.status IN ('open', 'betting_closed')
`

func (q *Queries) GetPlayerReservedAmount(ctx context.Context, playerID string) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerReservedAmount, playerID)
	var reserved float64
	err := row.Scan(&reserved)
	return reserved, err
}

const getPlayerStreakStats = `-- name: GetPlayerStreakStats :one
SELECT
    COUNT(CASE WHEN ms.score = max_scores.max_score THEN 1 END)::int AS wins,
    COUNT(CASE WHEN ms.score < max_scores.max_score THEN 1 END)::int AS losses
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
JOIN (
    SELECT match_id, MAX(score) AS max_score
    FROM match_scores
    GROUP BY match_id
) max_scores ON max_scores.match_id = ms.match_id
WHERE ms.player_id = $1
    AND m.game_id = ANY($2::uuid[])
    AND m.date >= $3
    AND m.date <= $4
`

type GetPlayerStreakStatsParams struct {
	PlayerID string             `json:"player_id"`
	Column2  []string           `json:"column_2"`
	Date     pgtype.Timestamptz `json:"date"`
	Date_2   pgtype.Timestamptz `json:"date_2"`
}

type GetPlayerStreakStatsRow struct {
	Wins   int32 `json:"wins"`
	Losses int32 `json:"losses"`
}

func (q *Queries) GetPlayerStreakStats(ctx context.Context, arg GetPlayerStreakStatsParams) (GetPlayerStreakStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStreakStats,
		arg.PlayerID,
		arg.Column2,
		arg.Date,
		arg.Date_2,
	)
	var i GetPlayerStreakStatsRow
	err := row.Scan(&i.Wins, &i.Losses)
	return i, err
}

const getSettlementDetails = `-- name: GetSettlementDetails :many
SELECT bsd.player_id, p.name AS player_name,
       (-bsd.elo_staked)::float8 AS staked, bsd.elo_earned AS earned
FROM global_arena_settlement bsd
JOIN players p ON p.id = bsd.player_id
WHERE bsd.market_id = $1 AND bsd.discriminator = 'market'
ORDER BY (bsd.elo_earned + bsd.elo_staked) DESC
`

type GetSettlementDetailsRow struct {
	PlayerID   string  `json:"player_id"`
	PlayerName string  `json:"player_name"`
	Staked     float64 `json:"staked"`
	Earned     float64 `json:"earned"`
}

func (q *Queries) GetSettlementDetails(ctx context.Context, marketID *string) ([]GetSettlementDetailsRow, error) {
	rows, err := q.db.Query(ctx, getSettlementDetails, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSettlementDetailsRow{}
	for rows.Next() {
		var i GetSettlementDetailsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Staked,
			&i.Earned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWinStreakParams = `-- name: GetWinStreakParams :one
SELECT market_id, target_player_id, wins_required, max_losses, game_ids FROM market_win_streak_params WHERE market_id = $1
`

func (q *Queries) GetWinStreakParams(ctx context.Context, marketID string) (MarketWinStreakParam, error) {
	row := q.db.QueryRow(ctx, getWinStreakParams, marketID)
	var i MarketWinStreakParam
	err := row.Scan(
		&i.MarketID,
		&i.TargetPlayerID,
		&i.WinsRequired,
		&i.MaxLosses,
		&i.GameIds,
	)
	return i, err
}

const insertBet = `-- name: InsertBet :one
INSERT INTO bets (id, market_id, player_id, outcome, cost, shares)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, placed_at
`

type InsertBetParams struct {
	ID       string  `json:"id"`
	MarketID string  `json:"market_id"`
	PlayerID string  `json:"player_id"`
	Outcome  string  `json:"outcome"`
	Cost     float64 `json:"cost"`
	Shares   float64 `json:"shares"`
}

type InsertBetRow struct {
	ID       string             `json:"id"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (InsertBetRow, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.ID,
		arg.MarketID,
		arg.PlayerID,
		arg.Outcome,
		arg.Cost,
		arg.Shares,
	)
	var i InsertBetRow
	err := row.Scan(&i.ID, &i.PlacedAt)
	return i, err
}

const listAllMarketOutcomesWithPools = `-- name: ListAllMarketOutcomesWithPools :many
SELECT o.id, o.market_id, o.kind, o.player_id, p.name AS player_name, o.q,
       COALESCE(bp.pool, 0)::float8 AS pool
FROM market_outcomes o
LEFT JOIN players p ON p.id = o.player_id
LEFT JOIN (
    SELECT bets.market_id, bets.outcome, SUM(bets.cost) AS pool FROM bets GROUP BY bets.market_id, bets.outcome
) bp ON bp.market_id = o.market_id AND bp.outcome = o.id
ORDER BY o.market_id, (CASE o.kind WHEN 'yes' THEN 1 WHEN 'no' THEN 2 WHEN 'player' THEN 3 ELSE 4 END), p.name NULLS LAST, o.id
`

type ListAllMarketOutcomesWithPoolsRow struct {
	ID         string      `json:"id"`
	MarketID   string      `json:"market_id"`
	Kind       string      `json:"kind"`
	PlayerID   *string     `json:"player_id"`
	PlayerName pgtype.Text `json:"player_name"`
	Q          float64     `json:"q"`
	Pool       float64     `json:"pool"`
}

// Same shape as ListMarketOutcomesWithPools for every market at once (used by
// the markets list endpoints), grouped client-side by market_id.
func (q *Queries) ListAllMarketOutcomesWithPools(ctx context.Context) ([]ListAllMarketOutcomesWithPoolsRow, error) {
	rows, err := q.db.Query(ctx, listAllMarketOutcomesWithPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMarketOutcomesWithPoolsRow{}
	for rows.Next() {
		var i ListAllMarketOutcomesWithPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Kind,
			&i.PlayerID,
			&i.PlayerName,
			&i.Q,
			&i.Pool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketGuarantors = `-- name: ListMarketGuarantors :many
SELECT g.player_id, p.name AS player_name
FROM market_guarantors g
JOIN players p ON p.id = g.player_id
WHERE g.market_id = $1
ORDER BY p.name
`

type ListMarketGuarantorsRow struct {
	PlayerID   string `json:"player_id"`
	PlayerName string `json:"player_name"`
}

func (q *Queries) ListMarketGuarantors(ctx context.Context, marketID string) ([]ListMarketGuarantorsRow, error) {
	rows, err := q.db.Query(ctx, listMarketGuarantors, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketGuarantorsRow{}
	for rows.Next() {
		var i ListMarketGuarantorsRow
		if err := rows.Scan(&i.PlayerID, &i.PlayerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketOutcomes = `-- name: ListMarketOutcomes :many
SELECT id, market_id, kind, player_id, q
FROM market_outcomes
WHERE market_id = $1
ORDER BY (CASE kind WHEN 'yes' THEN 1 WHEN 'no' THEN 2 WHEN 'player' THEN 3 ELSE 4 END), player_id
`

// Outcome rows in the canonical order: yes/no first (win_streak), then player
// outcomes, 'other' last. This order fixes the AMM q-vector layout.
func (q *Queries) ListMarketOutcomes(ctx context.Context, marketID string) ([]MarketOutcome, error) {
	rows, err := q.db.Query(ctx, listMarketOutcomes, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketOutcome{}
	for rows.Next() {
		var i MarketOutcome
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Kind,
			&i.PlayerID,
			&i.Q,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketOutcomesWithPools = `-- name: ListMarketOutcomesWithPools :many
SELECT o.id, o.market_id, o.kind, o.player_id, p.name AS player_name, o.q,
       COALESCE(bp.pool, 0)::float8 AS pool
FROM market_outcomes o
LEFT JOIN players p ON p.id = o.player_id
LEFT JOIN (
    SELECT bets.outcome, SUM(bets.cost) AS pool FROM bets WHERE bets.market_id = $1 GROUP BY bets.outcome
) bp ON bp.outcome = o.id
WHERE o.market_id = $1
ORDER BY (CASE o.kind WHEN 'yes' THEN 1 WHEN 'no' THEN 2 WHEN 'player' THEN 3 ELSE 4 END), p.name NULLS LAST, o.id
`

type ListMarketOutcomesWithPoolsRow struct {
	ID         string      `json:"id"`
	MarketID   string      `json:"market_id"`
	Kind       string      `json:"kind"`
	PlayerID   *string     `json:"player_id"`
	PlayerName pgtype.Text `json:"player_name"`
	Q          float64     `json:"q"`
	Pool       float64     `json:"pool"`
}

// Outcome rows with derived display name (players.name for player outcomes)
// and the elo spent per outcome, in the canonical order (see ListMarketOutcomes).
func (q *Queries) ListMarketOutcomesWithPools(ctx context.Context, marketID string) ([]ListMarketOutcomesWithPoolsRow, error) {
	rows, err := q.db.Query(ctx, listMarketOutcomesWithPools, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketOutcomesWithPoolsRow{}
	for rows.Next() {
		var i ListMarketOutcomesWithPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Kind,
			&i.PlayerID,
			&i.PlayerName,
			&i.Q,
			&i.Pool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkets = `-- name: ListMarkets :many
SELECT
    om.id, om.market_type, om.status, om.resolution_outcome, om.starts_at, om.closes_at,
    om.created_by, om.created_at, om.resolved_at, om.resolution_match_id, om.betting_closed_at,
    om.liquidity_b,
    mwp.target_player_ids,
    mwp.allow_other_players,
    mwp.game_ids AS mw_game_ids,
    wsp.target_player_id AS ws_target_player_id,
    wsp.game_ids AS ws_game_ids,
    wsp.wins_required,
    wsp.max_losses
FROM markets om
LEFT JOIN market_match_winner_params mwp ON mwp.market_id = om.id
LEFT JOIN market_win_streak_params wsp ON wsp.market_id = om.id
ORDER BY om.created_at DESC
`

type ListMarketsRow struct {
	ID                string             `json:"id"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	ResolutionOutcome *string            `json:"resolution_outcome"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID *string            `json:"resolution_match_id"`
	BettingClosedAt   pgtype.Timestamptz `json:"betting_closed_at"`
	LiquidityB        float64            `json:"liquidity_b"`
	TargetPlayerIds   []string           `json:"target_player_ids"`
	AllowOtherPlayers pgtype.Bool        `json:"allow_other_players"`
	MwGameIds         []string           `json:"mw_game_ids"`
	WsTargetPlayerID  *string            `json:"ws_target_player_id"`
	WsGameIds         []string           `json:"ws_game_ids"`
	WinsRequired      pgtype.Int4        `json:"wins_required"`
	MaxLosses         pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListMarkets(ctx context.Context) ([]ListMarketsRow, error) {
	rows, err := q.db.Query(ctx, listMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsRow{}
	for rows.Next() {
		var i ListMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketType,
			&i.Status,
			&i.ResolutionOutcome,
			&i.StartsAt,
			&i.ClosesAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolutionMatchID,
			&i.BettingClosedAt,
			&i.LiquidityB,
			&i.TargetPlayerIds,
			&i.AllowOtherPlayers,
			&i.MwGameIds,
			&i.WsTargetPlayerID,
			&i.WsGameIds,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsByResolutionMatch = `-- name: ListMarketsByResolutionMatch :many
SELECT
    om.id, om.market_type, om.status, om.resolution_outcome, om.starts_at, om.closes_at,
    om.created_by, om.created_at, om.resolved_at, om.resolution_match_id, om.betting_closed_at,
    om.liquidity_b,
    mwp.target_player_ids,
    mwp.allow_other_players,
    mwp.game_ids AS mw_game_ids,
    wsp.target_player_id AS ws_target_player_id,
    wsp.game_ids AS ws_game_ids,
    wsp.wins_required,
    wsp.max_losses
FROM markets om
LEFT JOIN market_match_winner_params mwp ON mwp.market_id = om.id
LEFT JOIN market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.resolution_match_id = $1
`

type ListMarketsByResolutionMatchRow struct {
	ID                string             `json:"id"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	ResolutionOutcome *string            `json:"resolution_outcome"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID *string            `json:"resolution_match_id"`
	BettingClosedAt   pgtype.Timestamptz `json:"betting_closed_at"`
	LiquidityB        float64            `json:"liquidity_b"`
	TargetPlayerIds   []string           `json:"target_player_ids"`
	AllowOtherPlayers pgtype.Bool        `json:"allow_other_players"`
	MwGameIds         []string           `json:"mw_game_ids"`
	WsTargetPlayerID  *string            `json:"ws_target_player_id"`
	WsGameIds         []string           `json:"ws_game_ids"`
	WinsRequired      pgtype.Int4        `json:"wins_required"`
	MaxLosses         pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListMarketsByResolutionMatch(ctx context.Context, resolutionMatchID *string) ([]ListMarketsByResolutionMatchRow, error) {
	rows, err := q.db.Query(ctx, listMarketsByResolutionMatch, resolutionMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsByResolutionMatchRow{}
	for rows.Next() {
		var i ListMarketsByResolutionMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketType,
			&i.Status,
			&i.ResolutionOutcome,
			&i.StartsAt,
			&i.ClosesAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolutionMatchID,
			&i.BettingClosedAt,
			&i.LiquidityB,
			&i.TargetPlayerIds,
			&i.AllowOtherPlayers,
			&i.MwGameIds,
			&i.WsTargetPlayerID,
			&i.WsGameIds,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMatchWinnerMarkets = `-- name: ListOpenMatchWinnerMarkets :many
SELECT om.id, om.starts_at, om.closes_at,
    mwp.target_player_ids, mwp.allow_other_players, mwp.game_ids
FROM markets om
JOIN market_match_winner_params mwp ON mwp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed')
`

type ListOpenMatchWinnerMarketsRow struct {
	ID                string             `json:"id"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	TargetPlayerIds   []string           `json:"target_player_ids"`
	AllowOtherPlayers bool               `json:"allow_other_players"`
	GameIds           []string           `json:"game_ids"`
}

func (q *Queries) ListOpenMatchWinnerMarkets(ctx context.Context) ([]ListOpenMatchWinnerMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOpenMatchWinnerMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenMatchWinnerMarketsRow{}
	for rows.Next() {
		var i ListOpenMatchWinnerMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.ClosesAt,
			&i.TargetPlayerIds,
			&i.AllowOtherPlayers,
			&i.GameIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWinStreakMarkets = `-- name: ListOpenWinStreakMarkets :many
SELECT om.id, om.starts_at, om.closes_at,
    wsp.target_player_id, wsp.game_ids, wsp.wins_required, wsp.max_losses
FROM markets om
JOIN market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed')
`

type ListOpenWinStreakMarketsRow struct {
	ID             string             `json:"id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	ClosesAt       pgtype.Timestamptz `json:"closes_at"`
	TargetPlayerID string             `json:"target_player_id"`
	GameIds        []string           `json:"game_ids"`
	WinsRequired   int32              `json:"wins_required"`
	MaxLosses      pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListOpenWinStreakMarkets(ctx context.Context) ([]ListOpenWinStreakMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOpenWinStreakMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenWinStreakMarketsRow{}
	for rows.Next() {
		var i ListOpenWinStreakMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.ClosesAt,
			&i.TargetPlayerID,
			&i.GameIds,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueMatchWinnerMarkets = `-- name: ListOverdueMatchWinnerMarkets :many
SELECT om.id, om.closes_at
FROM markets om
JOIN market_match_winner_params mwp ON mwp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed') AND om.closes_at <= NOW()
`

type ListOverdueMatchWinnerMarketsRow struct {
	ID       string             `json:"id"`
	ClosesAt pgtype.Timestamptz `json:"closes_at"`
}

func (q *Queries) ListOverdueMatchWinnerMarkets(ctx context.Context) ([]ListOverdueMatchWinnerMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueMatchWinnerMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueMatchWinnerMarketsRow{}
	for rows.Next() {
		var i ListOverdueMatchWinnerMarketsRow
		if err := rows.Scan(&i.ID, &i.ClosesAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueMatchWinnerMarketsAtDate = `-- name: ListOverdueMatchWinnerMarketsAtDate :many
SELECT om.id, om.closes_at
FROM markets om
JOIN market_match_winner_params mwp ON mwp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed') AND om.closes_at <= $1
`

type ListOverdueMatchWinnerMarketsAtDateRow struct {
	ID       string             `json:"id"`
	ClosesAt pgtype.Timestamptz `json:"closes_at"`
}

func (q *Queries) ListOverdueMatchWinnerMarketsAtDate(ctx context.Context, closesAt pgtype.Timestamptz) ([]ListOverdueMatchWinnerMarketsAtDateRow, error) {
	rows, err := q.db.Query(ctx, listOverdueMatchWinnerMarketsAtDate, closesAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueMatchWinnerMarketsAtDateRow{}
	for rows.Next() {
		var i ListOverdueMatchWinnerMarketsAtDateRow
		if err := rows.Scan(&i.ID, &i.ClosesAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueWinStreakMarkets = `-- name: ListOverdueWinStreakMarkets :many
SELECT om.id, om.closes_at, om.starts_at,
    wsp.target_player_id, wsp.game_ids, wsp.wins_required, wsp.max_losses
FROM markets om
JOIN market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed') AND om.closes_at <= NOW()
`

type ListOverdueWinStreakMarketsRow struct {
	ID             string             `json:"id"`
	ClosesAt       pgtype.Timestamptz `json:"closes_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	TargetPlayerID string             `json:"target_player_id"`
	GameIds        []string           `json:"game_ids"`
	WinsRequired   int32              `json:"wins_required"`
	MaxLosses      pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListOverdueWinStreakMarkets(ctx context.Context) ([]ListOverdueWinStreakMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueWinStreakMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueWinStreakMarketsRow{}
	for rows.Next() {
		var i ListOverdueWinStreakMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClosesAt,
			&i.StartsAt,
			&i.TargetPlayerID,
			&i.GameIds,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueWinStreakMarketsAtDate = `-- name: ListOverdueWinStreakMarketsAtDate :many
SELECT om.id, om.closes_at, om.starts_at,
    wsp.target_player_id, wsp.game_ids, wsp.wins_required, wsp.max_losses
FROM markets om
JOIN market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.status IN ('open', 'betting_closed') AND om.closes_at <= $1
`

type ListOverdueWinStreakMarketsAtDateRow struct {
	ID             string             `json:"id"`
	ClosesAt       pgtype.Timestamptz `json:"closes_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	TargetPlayerID string             `json:"target_player_id"`
	GameIds        []string           `json:"game_ids"`
	WinsRequired   int32              `json:"wins_required"`
	MaxLosses      pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListOverdueWinStreakMarketsAtDate(ctx context.Context, closesAt pgtype.Timestamptz) ([]ListOverdueWinStreakMarketsAtDateRow, error) {
	rows, err := q.db.Query(ctx, listOverdueWinStreakMarketsAtDate, closesAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueWinStreakMarketsAtDateRow{}
	for rows.Next() {
		var i ListOverdueWinStreakMarketsAtDateRow
		if err := rows.Scan(
			&i.ID,
			&i.ClosesAt,
			&i.StartsAt,
			&i.TargetPlayerID,
			&i.GameIds,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMarketBetting = `-- name: LockMarketBetting :exec
UPDATE markets
SET status = 'betting_closed',
    betting_closed_at = NOW()
WHERE id = $1 AND status = 'open'
`

// Sets status = 'betting_closed' and records the betting_closed_at timestamp (user event).
// Only succeeds if current status = 'open'; the caller must check affected rows or
// fetch the market first to return a proper domain error.
func (q *Queries) LockMarketBetting(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockMarketBetting, id)
	return err
}

const resolveMarket = `-- name: ResolveMarket :exec
UPDATE markets
SET status = $2, resolved_at = $3, resolution_match_id = $4, resolution_outcome = $5
WHERE id = $1
`

type ResolveMarketParams struct {
	ID                string             `json:"id"`
	Status            string             `json:"status"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID *string            `json:"resolution_match_id"`
	ResolutionOutcome *string            `json:"resolution_outcome"`
}

// resolution_outcome is the winning outcome id; NULL for cancelled markets
// (cancellation is carried by the status column).
func (q *Queries) ResolveMarket(ctx context.Context, arg ResolveMarketParams) error {
	_, err := q.db.Exec(ctx, resolveMarket,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolutionMatchID,
		arg.ResolutionOutcome,
	)
	return err
}

const unsettleMarket = `-- name: UnsettleMarket :exec
UPDATE markets
SET status = CASE WHEN betting_closed_at IS NOT NULL THEN 'betting_closed' ELSE 'open' END,
    resolved_at = NULL,
    resolution_match_id = NULL,
    resolution_outcome = NULL
WHERE id = $1
`

// Restores the pre-settlement status: betting_closed if the betting lock user event
// was set, otherwise open. betting_closed_at is intentionally left untouched — it is
// a user event and must never be cleared by recalculation.
func (q *Queries) UnsettleMarket(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unsettleMarket, id)
	return err
}

const updateMarketOutcomeQ = `-- name: UpdateMarketOutcomeQ :exec
UPDATE market_outcomes SET q = $3 WHERE market_id = $1 AND id = $2
`

type UpdateMarketOutcomeQParams struct {
	MarketID string  `json:"market_id"`
	ID       string  `json:"id"`
	Q        float64 `json:"q"`
}

// Persists one component of the LMSR state vector after a bet shifts the
// outstanding shares of an outcome.
func (q *Queries) UpdateMarketOutcomeQ(ctx context.Context, arg UpdateMarketOutcomeQParams) error {
	_, err := q.db.Exec(ctx, updateMarketOutcomeQ, arg.MarketID, arg.ID, arg.Q)
	return err
}

const updatePlayerBetLimit = `-- name: UpdatePlayerBetLimit :exec
UPDATE players SET bet_limit = $2 WHERE id = $1
`

type UpdatePlayerBetLimitParams struct {
	ID       string  `json:"id"`
	BetLimit float64 `json:"bet_limit"`
}

func (q *Queries) UpdatePlayerBetLimit(ctx context.Context, arg UpdatePlayerBetLimitParams) error {
	_, err := q.db.Exec(ctx, updatePlayerBetLimit, arg.ID, arg.BetLimit)
	return err
}

const upsertGlobalArenaSettlementByMarket = `-- name: UpsertGlobalArenaSettlementByMarket :exec
INSERT INTO global_arena_settlement
    (id, player_id, date, rating_after, elo_after, discriminator, market_id,
     elo_staked, elo_earned, rating_staked, rating_earned, league)
VALUES ($1, $2, $3, $4, $5, $12, $6, $7, $8, $9, $10, $11)
ON CONFLICT (market_id, player_id, discriminator) WHERE market_id IS NOT NULL
DO UPDATE SET rating_after  = EXCLUDED.rating_after,
              elo_after     = EXCLUDED.elo_after,
              date          = EXCLUDED.date,
              elo_staked    = EXCLUDED.elo_staked,
              elo_earned    = EXCLUDED.elo_earned,
              rating_staked = EXCLUDED.rating_staked,
              rating_earned = EXCLUDED.rating_earned,
              league        = EXCLUDED.league
`

type UpsertGlobalArenaSettlementByMarketParams struct {
	ID            string             `json:"id"`
	PlayerID      string             `json:"player_id"`
	Date          pgtype.Timestamptz `json:"date"`
	RatingAfter   float64            `json:"rating_after"`
	EloAfter      float64            `json:"elo_after"`
	MarketID      *string            `json:"market_id"`
	EloStaked     float64            `json:"elo_staked"`
	EloEarned     float64            `json:"elo_earned"`
	RatingStaked  float64            `json:"rating_staked"`
	RatingEarned  float64            `json:"rating_earned"`
	League        string             `json:"league"`
	Discriminator string             `json:"discriminator"`
}

// One row per role per player (buyer 'market' / guarantor 'market_guarantor'):
// a player who is both gets two rows, hence the discriminator in the conflict
// target.
func (q *Queries) UpsertGlobalArenaSettlementByMarket(ctx context.Context, arg UpsertGlobalArenaSettlementByMarketParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalArenaSettlementByMarket,
		arg.ID,
		arg.PlayerID,
		arg.Date,
		arg.RatingAfter,
		arg.EloAfter,
		arg.MarketID,
		arg.EloStaked,
		arg.EloEarned,
		arg.RatingStaked,
		arg.RatingEarned,
		arg.League,
		arg.Discriminator,
	)
	return err
}
