// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMarket = `-- name: CreateMarket :one
INSERT INTO outcome_markets (title, market_type, starts_at, closes_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, market_type, status, starts_at, closes_at, created_by, created_at, resolved_at, resolution_match_id
`

type CreateMarketParams struct {
	Title      string             `json:"title"`
	MarketType string             `json:"market_type"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	ClosesAt   pgtype.Timestamptz `json:"closes_at"`
	CreatedBy  int32              `json:"created_by"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (OutcomeMarket, error) {
	row := q.db.QueryRow(ctx, createMarket,
		arg.Title,
		arg.MarketType,
		arg.StartsAt,
		arg.ClosesAt,
		arg.CreatedBy,
	)
	var i OutcomeMarket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MarketType,
		&i.Status,
		&i.StartsAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolutionMatchID,
	)
	return i, err
}

const createMatchWinnerParams = `-- name: CreateMatchWinnerParams :exec
INSERT INTO outcome_market_match_winner_params (market_id, target_player_id, required_player_ids, game_id)
VALUES ($1, $2, $3, $4)
`

type CreateMatchWinnerParamsParams struct {
	MarketID          int32       `json:"market_id"`
	TargetPlayerID    int32       `json:"target_player_id"`
	RequiredPlayerIds []int32     `json:"required_player_ids"`
	GameID            pgtype.Int4 `json:"game_id"`
}

func (q *Queries) CreateMatchWinnerParams(ctx context.Context, arg CreateMatchWinnerParamsParams) error {
	_, err := q.db.Exec(ctx, createMatchWinnerParams,
		arg.MarketID,
		arg.TargetPlayerID,
		arg.RequiredPlayerIds,
		arg.GameID,
	)
	return err
}

const createWinStreakParams = `-- name: CreateWinStreakParams :exec
INSERT INTO outcome_market_win_streak_params (market_id, target_player_id, game_id, wins_required, max_losses)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWinStreakParamsParams struct {
	MarketID       int32       `json:"market_id"`
	TargetPlayerID int32       `json:"target_player_id"`
	GameID         int32       `json:"game_id"`
	WinsRequired   int32       `json:"wins_required"`
	MaxLosses      pgtype.Int4 `json:"max_losses"`
}

func (q *Queries) CreateWinStreakParams(ctx context.Context, arg CreateWinStreakParamsParams) error {
	_, err := q.db.Exec(ctx, createWinStreakParams,
		arg.MarketID,
		arg.TargetPlayerID,
		arg.GameID,
		arg.WinsRequired,
		arg.MaxLosses,
	)
	return err
}

const deleteBetSettlementDetails = `-- name: DeleteBetSettlementDetails :exec
DELETE FROM bet_settlement_details WHERE market_id = $1
`

func (q *Queries) DeleteBetSettlementDetails(ctx context.Context, marketID int32) error {
	_, err := q.db.Exec(ctx, deleteBetSettlementDetails, marketID)
	return err
}

const deletePlayerRatingsByMarket = `-- name: DeletePlayerRatingsByMarket :exec
DELETE FROM player_ratings WHERE market_id = $1
`

func (q *Queries) DeletePlayerRatingsByMarket(ctx context.Context, marketID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deletePlayerRatingsByMarket, marketID)
	return err
}

const getBetsAggregatedByOutcome = `-- name: GetBetsAggregatedByOutcome :many
SELECT player_id, outcome, SUM(amount)::float8 AS total_amount
FROM outcome_bets
WHERE market_id = $1
GROUP BY player_id, outcome
ORDER BY player_id, outcome
`

type GetBetsAggregatedByOutcomeRow struct {
	PlayerID    int32   `json:"player_id"`
	Outcome     string  `json:"outcome"`
	TotalAmount float64 `json:"total_amount"`
}

func (q *Queries) GetBetsAggregatedByOutcome(ctx context.Context, marketID int32) ([]GetBetsAggregatedByOutcomeRow, error) {
	rows, err := q.db.Query(ctx, getBetsAggregatedByOutcome, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBetsAggregatedByOutcomeRow{}
	for rows.Next() {
		var i GetBetsAggregatedByOutcomeRow
		if err := rows.Scan(&i.PlayerID, &i.Outcome, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketWithPools = `-- name: GetMarketWithPools :one
SELECT
    om.id, om.title, om.market_type, om.status, om.starts_at, om.closes_at, om.created_by, om.created_at, om.resolved_at, om.resolution_match_id,
    COALESCE(SUM(CASE WHEN ob.outcome = 'yes' THEN ob.amount ELSE 0 END), 0)::float8 AS yes_pool,
    COALESCE(SUM(CASE WHEN ob.outcome = 'no'  THEN ob.amount ELSE 0 END), 0)::float8 AS no_pool
FROM outcome_markets om
LEFT JOIN outcome_bets ob ON ob.market_id = om.id
WHERE om.id = $1
GROUP BY om.id
`

type GetMarketWithPoolsRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
	YesPool           float64            `json:"yes_pool"`
	NoPool            float64            `json:"no_pool"`
}

func (q *Queries) GetMarketWithPools(ctx context.Context, id int32) (GetMarketWithPoolsRow, error) {
	row := q.db.QueryRow(ctx, getMarketWithPools, id)
	var i GetMarketWithPoolsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MarketType,
		&i.Status,
		&i.StartsAt,
		&i.ClosesAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolutionMatchID,
		&i.YesPool,
		&i.NoPool,
	)
	return i, err
}

const getMarketsForUnsettle = `-- name: GetMarketsForUnsettle :many
SELECT DISTINCT om.id
FROM outcome_markets om
WHERE om.status != 'open'
  AND om.resolved_at >= $1
`

func (q *Queries) GetMarketsForUnsettle(ctx context.Context, resolvedAt pgtype.Timestamptz) ([]int32, error) {
	rows, err := q.db.Query(ctx, getMarketsForUnsettle, resolvedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchWinnerParams = `-- name: GetMatchWinnerParams :one
SELECT market_id, target_player_id, required_player_ids, game_id FROM outcome_market_match_winner_params WHERE market_id = $1
`

func (q *Queries) GetMatchWinnerParams(ctx context.Context, marketID int32) (OutcomeMarketMatchWinnerParam, error) {
	row := q.db.QueryRow(ctx, getMatchWinnerParams, marketID)
	var i OutcomeMarketMatchWinnerParam
	err := row.Scan(
		&i.MarketID,
		&i.TargetPlayerID,
		&i.RequiredPlayerIds,
		&i.GameID,
	)
	return i, err
}

const getNearestMarketExpiry = `-- name: GetNearestMarketExpiry :one
SELECT closes_at FROM outcome_markets
WHERE status = 'open'
ORDER BY closes_at ASC
LIMIT 1
`

func (q *Queries) GetNearestMarketExpiry(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNearestMarketExpiry)
	var closes_at pgtype.Timestamptz
	err := row.Scan(&closes_at)
	return closes_at, err
}

const getPlayerBetLimit = `-- name: GetPlayerBetLimit :one
SELECT bet_limit FROM players WHERE id = $1
`

func (q *Queries) GetPlayerBetLimit(ctx context.Context, id int32) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerBetLimit, id)
	var bet_limit float64
	err := row.Scan(&bet_limit)
	return bet_limit, err
}

const getPlayerBetsAggregatedForMarket = `-- name: GetPlayerBetsAggregatedForMarket :many
SELECT outcome, SUM(amount)::float8 AS total_amount
FROM outcome_bets
WHERE market_id = $1 AND player_id = $2
GROUP BY outcome
`

type GetPlayerBetsAggregatedForMarketParams struct {
	MarketID int32 `json:"market_id"`
	PlayerID int32 `json:"player_id"`
}

type GetPlayerBetsAggregatedForMarketRow struct {
	Outcome     string  `json:"outcome"`
	TotalAmount float64 `json:"total_amount"`
}

func (q *Queries) GetPlayerBetsAggregatedForMarket(ctx context.Context, arg GetPlayerBetsAggregatedForMarketParams) ([]GetPlayerBetsAggregatedForMarketRow, error) {
	rows, err := q.db.Query(ctx, getPlayerBetsAggregatedForMarket, arg.MarketID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerBetsAggregatedForMarketRow{}
	for rows.Next() {
		var i GetPlayerBetsAggregatedForMarketRow
		if err := rows.Scan(&i.Outcome, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerReservedAmount = `-- name: GetPlayerReservedAmount :one
SELECT COALESCE(SUM(ob.amount), 0)::float8 AS reserved
FROM outcome_bets ob
JOIN outcome_markets om ON om.id = ob.market_id
WHERE ob.player_id = $1 AND om.status = 'open'
`

func (q *Queries) GetPlayerReservedAmount(ctx context.Context, playerID int32) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerReservedAmount, playerID)
	var reserved float64
	err := row.Scan(&reserved)
	return reserved, err
}

const getPlayerStreakStats = `-- name: GetPlayerStreakStats :one
SELECT
    COUNT(CASE WHEN ms.score = max_scores.max_score THEN 1 END)::int AS wins,
    COUNT(CASE WHEN ms.score < max_scores.max_score THEN 1 END)::int AS losses
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
JOIN (
    SELECT match_id, MAX(score) AS max_score
    FROM match_scores
    GROUP BY match_id
) max_scores ON max_scores.match_id = ms.match_id
WHERE ms.player_id = $1
    AND m.game_id = $2
    AND m.date >= $3
    AND m.date <= $4
`

type GetPlayerStreakStatsParams struct {
	PlayerID int32              `json:"player_id"`
	GameID   int32              `json:"game_id"`
	Date     pgtype.Timestamptz `json:"date"`
	Date_2   pgtype.Timestamptz `json:"date_2"`
}

type GetPlayerStreakStatsRow struct {
	Wins   int32 `json:"wins"`
	Losses int32 `json:"losses"`
}

func (q *Queries) GetPlayerStreakStats(ctx context.Context, arg GetPlayerStreakStatsParams) (GetPlayerStreakStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStreakStats,
		arg.PlayerID,
		arg.GameID,
		arg.Date,
		arg.Date_2,
	)
	var i GetPlayerStreakStatsRow
	err := row.Scan(&i.Wins, &i.Losses)
	return i, err
}

const getSettlementDetails = `-- name: GetSettlementDetails :many
SELECT bsd.player_id, p.name AS player_name, bsd.staked, bsd.earned
FROM bet_settlement_details bsd
JOIN players p ON p.id = bsd.player_id
WHERE bsd.market_id = $1
ORDER BY (bsd.earned - bsd.staked) DESC
`

type GetSettlementDetailsRow struct {
	PlayerID   int32   `json:"player_id"`
	PlayerName string  `json:"player_name"`
	Staked     float64 `json:"staked"`
	Earned     float64 `json:"earned"`
}

func (q *Queries) GetSettlementDetails(ctx context.Context, marketID int32) ([]GetSettlementDetailsRow, error) {
	rows, err := q.db.Query(ctx, getSettlementDetails, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSettlementDetailsRow{}
	for rows.Next() {
		var i GetSettlementDetailsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Staked,
			&i.Earned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWinStreakParams = `-- name: GetWinStreakParams :one
SELECT market_id, target_player_id, game_id, wins_required, max_losses FROM outcome_market_win_streak_params WHERE market_id = $1
`

func (q *Queries) GetWinStreakParams(ctx context.Context, marketID int32) (OutcomeMarketWinStreakParam, error) {
	row := q.db.QueryRow(ctx, getWinStreakParams, marketID)
	var i OutcomeMarketWinStreakParam
	err := row.Scan(
		&i.MarketID,
		&i.TargetPlayerID,
		&i.GameID,
		&i.WinsRequired,
		&i.MaxLosses,
	)
	return i, err
}

const insertBet = `-- name: InsertBet :one
INSERT INTO outcome_bets (market_id, player_id, outcome, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, placed_at
`

type InsertBetParams struct {
	MarketID int32   `json:"market_id"`
	PlayerID int32   `json:"player_id"`
	Outcome  string  `json:"outcome"`
	Amount   float64 `json:"amount"`
}

type InsertBetRow struct {
	ID       int32              `json:"id"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (InsertBetRow, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.MarketID,
		arg.PlayerID,
		arg.Outcome,
		arg.Amount,
	)
	var i InsertBetRow
	err := row.Scan(&i.ID, &i.PlacedAt)
	return i, err
}

const insertBetSettlementDetail = `-- name: InsertBetSettlementDetail :exec
INSERT INTO bet_settlement_details (market_id, player_id, staked, earned)
VALUES ($1, $2, $3, $4)
`

type InsertBetSettlementDetailParams struct {
	MarketID int32   `json:"market_id"`
	PlayerID int32   `json:"player_id"`
	Staked   float64 `json:"staked"`
	Earned   float64 `json:"earned"`
}

func (q *Queries) InsertBetSettlementDetail(ctx context.Context, arg InsertBetSettlementDetailParams) error {
	_, err := q.db.Exec(ctx, insertBetSettlementDetail,
		arg.MarketID,
		arg.PlayerID,
		arg.Staked,
		arg.Earned,
	)
	return err
}

const listMarketsByResolutionMatch = `-- name: ListMarketsByResolutionMatch :many
SELECT
    om.id, om.title, om.market_type, om.status, om.starts_at, om.closes_at, om.created_by, om.created_at, om.resolved_at, om.resolution_match_id,
    COALESCE(SUM(CASE WHEN ob.outcome = 'yes' THEN ob.amount ELSE 0 END), 0)::float8 AS yes_pool,
    COALESCE(SUM(CASE WHEN ob.outcome = 'no'  THEN ob.amount ELSE 0 END), 0)::float8 AS no_pool
FROM outcome_markets om
LEFT JOIN outcome_bets ob ON ob.market_id = om.id
WHERE om.resolution_match_id = $1
GROUP BY om.id
`

type ListMarketsByResolutionMatchRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
	YesPool           float64            `json:"yes_pool"`
	NoPool            float64            `json:"no_pool"`
}

func (q *Queries) ListMarketsByResolutionMatch(ctx context.Context, resolutionMatchID pgtype.Int4) ([]ListMarketsByResolutionMatchRow, error) {
	rows, err := q.db.Query(ctx, listMarketsByResolutionMatch, resolutionMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsByResolutionMatchRow{}
	for rows.Next() {
		var i ListMarketsByResolutionMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MarketType,
			&i.Status,
			&i.StartsAt,
			&i.ClosesAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolutionMatchID,
			&i.YesPool,
			&i.NoPool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketsWithPools = `-- name: ListMarketsWithPools :many
SELECT
    om.id, om.title, om.market_type, om.status, om.starts_at, om.closes_at, om.created_by, om.created_at, om.resolved_at, om.resolution_match_id,
    COALESCE(SUM(CASE WHEN ob.outcome = 'yes' THEN ob.amount ELSE 0 END), 0)::float8 AS yes_pool,
    COALESCE(SUM(CASE WHEN ob.outcome = 'no'  THEN ob.amount ELSE 0 END), 0)::float8 AS no_pool
FROM outcome_markets om
LEFT JOIN outcome_bets ob ON ob.market_id = om.id
GROUP BY om.id
ORDER BY om.created_at DESC
`

type ListMarketsWithPoolsRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
	YesPool           float64            `json:"yes_pool"`
	NoPool            float64            `json:"no_pool"`
}

func (q *Queries) ListMarketsWithPools(ctx context.Context) ([]ListMarketsWithPoolsRow, error) {
	rows, err := q.db.Query(ctx, listMarketsWithPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsWithPoolsRow{}
	for rows.Next() {
		var i ListMarketsWithPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MarketType,
			&i.Status,
			&i.StartsAt,
			&i.ClosesAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolutionMatchID,
			&i.YesPool,
			&i.NoPool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMatchWinnerMarkets = `-- name: ListOpenMatchWinnerMarkets :many
SELECT om.id, om.starts_at, om.closes_at,
    mwp.target_player_id, mwp.required_player_ids, mwp.game_id
FROM outcome_markets om
JOIN outcome_market_match_winner_params mwp ON mwp.market_id = om.id
WHERE om.status = 'open'
`

type ListOpenMatchWinnerMarketsRow struct {
	ID                int32              `json:"id"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	TargetPlayerID    int32              `json:"target_player_id"`
	RequiredPlayerIds []int32            `json:"required_player_ids"`
	GameID            pgtype.Int4        `json:"game_id"`
}

func (q *Queries) ListOpenMatchWinnerMarkets(ctx context.Context) ([]ListOpenMatchWinnerMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOpenMatchWinnerMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenMatchWinnerMarketsRow{}
	for rows.Next() {
		var i ListOpenMatchWinnerMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.ClosesAt,
			&i.TargetPlayerID,
			&i.RequiredPlayerIds,
			&i.GameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWinStreakMarkets = `-- name: ListOpenWinStreakMarkets :many
SELECT om.id, om.starts_at, om.closes_at,
    wsp.target_player_id, wsp.game_id, wsp.wins_required, wsp.max_losses
FROM outcome_markets om
JOIN outcome_market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.status = 'open'
`

type ListOpenWinStreakMarketsRow struct {
	ID             int32              `json:"id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	ClosesAt       pgtype.Timestamptz `json:"closes_at"`
	TargetPlayerID int32              `json:"target_player_id"`
	GameID         int32              `json:"game_id"`
	WinsRequired   int32              `json:"wins_required"`
	MaxLosses      pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListOpenWinStreakMarkets(ctx context.Context) ([]ListOpenWinStreakMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOpenWinStreakMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenWinStreakMarketsRow{}
	for rows.Next() {
		var i ListOpenWinStreakMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.ClosesAt,
			&i.TargetPlayerID,
			&i.GameID,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueMatchWinnerMarkets = `-- name: ListOverdueMatchWinnerMarkets :many
SELECT om.id, om.closes_at
FROM outcome_markets om
JOIN outcome_market_match_winner_params mwp ON mwp.market_id = om.id
WHERE om.status = 'open' AND om.closes_at <= NOW()
`

type ListOverdueMatchWinnerMarketsRow struct {
	ID       int32              `json:"id"`
	ClosesAt pgtype.Timestamptz `json:"closes_at"`
}

func (q *Queries) ListOverdueMatchWinnerMarkets(ctx context.Context) ([]ListOverdueMatchWinnerMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueMatchWinnerMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueMatchWinnerMarketsRow{}
	for rows.Next() {
		var i ListOverdueMatchWinnerMarketsRow
		if err := rows.Scan(&i.ID, &i.ClosesAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueWinStreakMarkets = `-- name: ListOverdueWinStreakMarkets :many
SELECT om.id, om.closes_at, om.starts_at,
    wsp.target_player_id, wsp.game_id, wsp.wins_required, wsp.max_losses
FROM outcome_markets om
JOIN outcome_market_win_streak_params wsp ON wsp.market_id = om.id
WHERE om.status = 'open' AND om.closes_at <= NOW()
`

type ListOverdueWinStreakMarketsRow struct {
	ID             int32              `json:"id"`
	ClosesAt       pgtype.Timestamptz `json:"closes_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	TargetPlayerID int32              `json:"target_player_id"`
	GameID         int32              `json:"game_id"`
	WinsRequired   int32              `json:"wins_required"`
	MaxLosses      pgtype.Int4        `json:"max_losses"`
}

func (q *Queries) ListOverdueWinStreakMarkets(ctx context.Context) ([]ListOverdueWinStreakMarketsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueWinStreakMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueWinStreakMarketsRow{}
	for rows.Next() {
		var i ListOverdueWinStreakMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClosesAt,
			&i.StartsAt,
			&i.TargetPlayerID,
			&i.GameID,
			&i.WinsRequired,
			&i.MaxLosses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMarket = `-- name: ResolveMarket :exec
UPDATE outcome_markets
SET status = $2, resolved_at = $3, resolution_match_id = $4
WHERE id = $1
`

type ResolveMarketParams struct {
	ID                int32              `json:"id"`
	Status            string             `json:"status"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
}

func (q *Queries) ResolveMarket(ctx context.Context, arg ResolveMarketParams) error {
	_, err := q.db.Exec(ctx, resolveMarket,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolutionMatchID,
	)
	return err
}

const unsettleMarket = `-- name: UnsettleMarket :exec
UPDATE outcome_markets
SET status = 'open', resolved_at = NULL, resolution_match_id = NULL
WHERE id = $1
`

func (q *Queries) UnsettleMarket(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unsettleMarket, id)
	return err
}

const updatePlayerBetLimit = `-- name: UpdatePlayerBetLimit :exec
UPDATE players SET bet_limit = $2 WHERE id = $1
`

type UpdatePlayerBetLimitParams struct {
	ID       int32   `json:"id"`
	BetLimit float64 `json:"bet_limit"`
}

func (q *Queries) UpdatePlayerBetLimit(ctx context.Context, arg UpdatePlayerBetLimitParams) error {
	_, err := q.db.Exec(ctx, updatePlayerBetLimit, arg.ID, arg.BetLimit)
	return err
}

const upsertPlayerRatingByMarket = `-- name: UpsertPlayerRatingByMarket :exec
INSERT INTO player_ratings (date, player_id, rating, source_type, market_id)
VALUES ($1, $2, $3, 'bet_settlement', $4)
ON CONFLICT (market_id, player_id) WHERE market_id IS NOT NULL
DO UPDATE SET rating = EXCLUDED.rating, date = EXCLUDED.date
`

type UpsertPlayerRatingByMarketParams struct {
	Date     pgtype.Timestamptz `json:"date"`
	PlayerID int32              `json:"player_id"`
	Rating   float64            `json:"rating"`
	MarketID pgtype.Int4        `json:"market_id"`
}

func (q *Queries) UpsertPlayerRatingByMarket(ctx context.Context, arg UpsertPlayerRatingByMarketParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerRatingByMarket,
		arg.Date,
		arg.PlayerID,
		arg.Rating,
		arg.MarketID,
	)
	return err
}
