// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (date, game_id)
VALUES ($1, $2)
RETURNING id, date, game_id
`

type CreateMatchParams struct {
	Date   pgtype.Timestamptz `json:"date"`
	GameID int32              `json:"game_id"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.Date, arg.GameID)
	var i Match
	err := row.Scan(&i.ID, &i.Date, &i.GameID)
	return i, err
}

const deleteAllMatchScores = `-- name: DeleteAllMatchScores :exec
DELETE FROM match_scores
`

func (q *Queries) DeleteAllMatchScores(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllMatchScores)
	return err
}

const deleteAllMatches = `-- name: DeleteAllMatches :exec
DELETE FROM matches
`

func (q *Queries) DeleteAllMatches(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllMatches)
	return err
}

const deleteMatchScores = `-- name: DeleteMatchScores :exec
DELETE FROM match_scores
WHERE match_id = $1
`

func (q *Queries) DeleteMatchScores(ctx context.Context, matchID int32) error {
	_, err := q.db.Exec(ctx, deleteMatchScores, matchID)
	return err
}

const getCountMatchesByGame = `-- name: GetCountMatchesByGame :one
SELECT COUNT(DISTINCT m.id) AS total_matches
FROM matches m
WHERE m.game_id = $1
`

func (q *Queries) GetCountMatchesByGame(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getCountMatchesByGame, gameID)
	var total_matches int64
	err := row.Scan(&total_matches)
	return total_matches, err
}

const getMatch = `-- name: GetMatch :one
SELECT id, date, game_id FROM matches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetMatch(ctx context.Context, id int32) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(&i.ID, &i.Date, &i.GameID)
	return i, err
}

const getMatchScoresForMatch = `-- name: GetMatchScoresForMatch :many
SELECT player_id, score
FROM match_scores
WHERE match_id = $1
`

type GetMatchScoresForMatchRow struct {
	PlayerID int32   `json:"player_id"`
	Score    float64 `json:"score"`
}

func (q *Queries) GetMatchScoresForMatch(ctx context.Context, matchID int32) ([]GetMatchScoresForMatchRow, error) {
	rows, err := q.db.Query(ctx, getMatchScoresForMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchScoresForMatchRow{}
	for rows.Next() {
		var i GetMatchScoresForMatchRow
		if err := rows.Scan(&i.PlayerID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchWithPlayers = `-- name: GetMatchWithPlayers :many
SELECT
    m.id AS match_id,
    m.date,
    g.id AS game_id,
    g.name AS game_name,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.global_elo_pay,
    s.global_elo_earn,
    s.global_new_elo,
    CASE WHEN prev_match_score.global_new_elo IS NULL THEN NULL
    ELSE prev_match_score.global_new_elo END AS prev_rating
FROM matches m
JOIN games g ON g.id = m.game_id
JOIN match_scores s ON s.match_id = m.id
JOIN players p ON p.id = s.player_id
LEFT JOIN LATERAL (
    SELECT ms.global_new_elo
    FROM match_scores ms
    JOIN matches prev_m ON prev_m.id = ms.match_id
    WHERE ms.player_id = p.id AND prev_m.date < m.date
    ORDER BY prev_m.date DESC, prev_m.id DESC
    LIMIT 1
) prev_match_score ON true
WHERE m.id = $1
ORDER BY s.score DESC
`

type GetMatchWithPlayersRow struct {
	MatchID       int32              `json:"match_id"`
	Date          pgtype.Timestamptz `json:"date"`
	GameID        int32              `json:"game_id"`
	GameName      string             `json:"game_name"`
	PlayerID      int32              `json:"player_id"`
	PlayerName    string             `json:"player_name"`
	Score         float64            `json:"score"`
	GlobalEloPay  float64            `json:"global_elo_pay"`
	GlobalEloEarn float64            `json:"global_elo_earn"`
	GlobalNewElo  float64            `json:"global_new_elo"`
	PrevRating    interface{}        `json:"prev_rating"`
}

func (q *Queries) GetMatchWithPlayers(ctx context.Context, id int32) ([]GetMatchWithPlayersRow, error) {
	rows, err := q.db.Query(ctx, getMatchWithPlayers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchWithPlayersRow{}
	for rows.Next() {
		var i GetMatchWithPlayersRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameID,
			&i.GameName,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GlobalEloPay,
			&i.GlobalEloEarn,
			&i.GlobalNewElo,
			&i.PrevRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchesFromDate = `-- name: GetMatchesFromDate :many
SELECT m.id, m.date, m.game_id
FROM matches m
WHERE m.date >= $1
ORDER BY m.date ASC, m.id ASC
`

func (q *Queries) GetMatchesFromDate(ctx context.Context, date pgtype.Timestamptz) ([]Match, error) {
	rows, err := q.db.Query(ctx, getMatchesFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(&i.ID, &i.Date, &i.GameID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerLatestGameElo = `-- name: GetPlayerLatestGameElo :one
SELECT ms.game_new_elo
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
WHERE ms.player_id = $1
  AND m.game_id = $2
  AND ms.game_new_elo IS NOT NULL
ORDER BY m.date DESC, m.id DESC
LIMIT 1
`

type GetPlayerLatestGameEloParams struct {
	PlayerID int32 `json:"player_id"`
	GameID   int32 `json:"game_id"`
}

func (q *Queries) GetPlayerLatestGameElo(ctx context.Context, arg GetPlayerLatestGameEloParams) (pgtype.Float8, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestGameElo, arg.PlayerID, arg.GameID)
	var game_new_elo pgtype.Float8
	err := row.Scan(&game_new_elo)
	return game_new_elo, err
}

const getPlayerLatestGameEloBeforeMatch = `-- name: GetPlayerLatestGameEloBeforeMatch :one
SELECT ms.game_new_elo
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
WHERE ms.player_id = $1
  AND m.game_id = $2
  AND (m.date < $3 OR (m.date = $3 AND m.id < $4))
  AND ms.game_new_elo IS NOT NULL
ORDER BY m.date DESC, m.id DESC
LIMIT 1
`

type GetPlayerLatestGameEloBeforeMatchParams struct {
	PlayerID int32              `json:"player_id"`
	GameID   int32              `json:"game_id"`
	Date     pgtype.Timestamptz `json:"date"`
	ID       int32              `json:"id"`
}

func (q *Queries) GetPlayerLatestGameEloBeforeMatch(ctx context.Context, arg GetPlayerLatestGameEloBeforeMatchParams) (pgtype.Float8, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestGameEloBeforeMatch,
		arg.PlayerID,
		arg.GameID,
		arg.Date,
		arg.ID,
	)
	var game_new_elo pgtype.Float8
	err := row.Scan(&game_new_elo)
	return game_new_elo, err
}

const getPlayerLatestGlobalElo = `-- name: GetPlayerLatestGlobalElo :one
SELECT ms.global_new_elo
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
WHERE ms.player_id = $1
ORDER BY m.date DESC, m.id DESC
LIMIT 1
`

func (q *Queries) GetPlayerLatestGlobalElo(ctx context.Context, playerID int32) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestGlobalElo, playerID)
	var global_new_elo float64
	err := row.Scan(&global_new_elo)
	return global_new_elo, err
}

const getPlayerLatestGlobalEloBeforeMatch = `-- name: GetPlayerLatestGlobalEloBeforeMatch :one
SELECT ms.global_new_elo
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
WHERE ms.player_id = $1
  AND (m.date < $2 OR (m.date = $2 AND m.id < $3))
ORDER BY m.date DESC, m.id DESC
LIMIT 1
`

type GetPlayerLatestGlobalEloBeforeMatchParams struct {
	PlayerID int32              `json:"player_id"`
	Date     pgtype.Timestamptz `json:"date"`
	ID       int32              `json:"id"`
}

func (q *Queries) GetPlayerLatestGlobalEloBeforeMatch(ctx context.Context, arg GetPlayerLatestGlobalEloBeforeMatchParams) (float64, error) {
	row := q.db.QueryRow(ctx, getPlayerLatestGlobalEloBeforeMatch, arg.PlayerID, arg.Date, arg.ID)
	var global_new_elo float64
	err := row.Scan(&global_new_elo)
	return global_new_elo, err
}

const listLatestGameEloPerPlayer = `-- name: ListLatestGameEloPerPlayer :many
SELECT DISTINCT ON (ms.player_id) ms.player_id, ms.game_new_elo
FROM match_scores ms
JOIN matches m ON m.id = ms.match_id
WHERE m.game_id = $1
  AND ms.game_new_elo IS NOT NULL
ORDER BY ms.player_id, m.date DESC, m.id DESC
`

type ListLatestGameEloPerPlayerRow struct {
	PlayerID   int32         `json:"player_id"`
	GameNewElo pgtype.Float8 `json:"game_new_elo"`
}

func (q *Queries) ListLatestGameEloPerPlayer(ctx context.Context, gameID int32) ([]ListLatestGameEloPerPlayerRow, error) {
	rows, err := q.db.Query(ctx, listLatestGameEloPerPlayer, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestGameEloPerPlayerRow{}
	for rows.Next() {
		var i ListLatestGameEloPerPlayerRow
		if err := rows.Scan(&i.PlayerID, &i.GameNewElo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchResults = `-- name: ListMatchResults :many
SELECT
    m.id AS match_id,
    m.date,
    g.name AS game_name,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.global_elo_pay,
    s.global_elo_earn,
    s.global_new_elo
FROM match_scores s
JOIN players p ON p.id = s.player_id
JOIN matches m ON m.id = s.match_id
JOIN games g ON g.id = m.game_id
WHERE m.id = $1
ORDER BY s.score DESC
`

type ListMatchResultsRow struct {
	MatchID       int32              `json:"match_id"`
	Date          pgtype.Timestamptz `json:"date"`
	GameName      string             `json:"game_name"`
	PlayerID      int32              `json:"player_id"`
	PlayerName    string             `json:"player_name"`
	Score         float64            `json:"score"`
	GlobalEloPay  float64            `json:"global_elo_pay"`
	GlobalEloEarn float64            `json:"global_elo_earn"`
	GlobalNewElo  float64            `json:"global_new_elo"`
}

func (q *Queries) ListMatchResults(ctx context.Context, id int32) ([]ListMatchResultsRow, error) {
	rows, err := q.db.Query(ctx, listMatchResults, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchResultsRow{}
	for rows.Next() {
		var i ListMatchResultsRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameName,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GlobalEloPay,
			&i.GlobalEloEarn,
			&i.GlobalNewElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesWithPlayers = `-- name: ListMatchesWithPlayers :many
SELECT
    m.id AS match_id,
    m.date,
    g.id AS game_id,
    g.name AS game_name,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.global_elo_pay,
    s.global_elo_earn,
    s.global_new_elo,
    CASE WHEN prev_match_score.global_new_elo IS NULL THEN NULL
    ELSE prev_match_score.global_new_elo END AS prev_rating

FROM matches m
JOIN games g ON g.id = m.game_id
JOIN match_scores s ON s.match_id = m.id
JOIN players p ON p.id = s.player_id
LEFT JOIN LATERAL (
    SELECT ms.global_new_elo
    FROM match_scores ms
    JOIN matches prev_m ON prev_m.id = ms.match_id
    WHERE ms.player_id = p.id AND prev_m.date < m.date
    ORDER BY prev_m.date DESC, prev_m.id DESC
    LIMIT 1
) prev_match_score ON true
ORDER BY m.date DESC, s.score DESC
`

type ListMatchesWithPlayersRow struct {
	MatchID       int32              `json:"match_id"`
	Date          pgtype.Timestamptz `json:"date"`
	GameID        int32              `json:"game_id"`
	GameName      string             `json:"game_name"`
	PlayerID      int32              `json:"player_id"`
	PlayerName    string             `json:"player_name"`
	Score         float64            `json:"score"`
	GlobalEloPay  float64            `json:"global_elo_pay"`
	GlobalEloEarn float64            `json:"global_elo_earn"`
	GlobalNewElo  float64            `json:"global_new_elo"`
	PrevRating    interface{}        `json:"prev_rating"`
}

func (q *Queries) ListMatchesWithPlayers(ctx context.Context) ([]ListMatchesWithPlayersRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesWithPlayersRow{}
	for rows.Next() {
		var i ListMatchesWithPlayersRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameID,
			&i.GameName,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GlobalEloPay,
			&i.GlobalEloEarn,
			&i.GlobalNewElo,
			&i.PrevRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesWithPlayersByGame = `-- name: ListMatchesWithPlayersByGame :many
SELECT
    m.id AS match_id,
    m.date,
    g.id AS game_id,
    g.name AS game_name,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.global_elo_pay,
    s.global_elo_earn,
    s.global_new_elo,
    CASE WHEN prev_match_score.global_new_elo IS NULL THEN NULL
    ELSE prev_match_score.global_new_elo END AS prev_rating,
    elo_settings.elo_const_k,
    elo_settings.elo_const_d,
    elo_settings.starting_elo,
    elo_settings.win_reward

FROM matches m
JOIN games g ON g.id = m.game_id
JOIN match_scores s ON s.match_id = m.id
JOIN players p ON p.id = s.player_id
LEFT JOIN LATERAL (
    SELECT ms.global_new_elo
    FROM match_scores ms
    JOIN matches prev_m ON prev_m.id = ms.match_id
    WHERE ms.player_id = p.id AND prev_m.date < m.date
    ORDER BY prev_m.date DESC, prev_m.id DESC
    LIMIT 1
) prev_match_score ON true
LEFT JOIN LATERAL (
    SELECT elo_const_k, elo_const_d, starting_elo, win_reward
    FROM elo_settings
    WHERE effective_date <= m.date
    ORDER BY effective_date DESC
    LIMIT 1
) elo_settings ON true
WHERE g.id = $1
ORDER BY m.date ASC, m.id ASC, s.score DESC
`

type ListMatchesWithPlayersByGameRow struct {
	MatchID       int32              `json:"match_id"`
	Date          pgtype.Timestamptz `json:"date"`
	GameID        int32              `json:"game_id"`
	GameName      string             `json:"game_name"`
	PlayerID      int32              `json:"player_id"`
	PlayerName    string             `json:"player_name"`
	Score         float64            `json:"score"`
	GlobalEloPay  float64            `json:"global_elo_pay"`
	GlobalEloEarn float64            `json:"global_elo_earn"`
	GlobalNewElo  float64            `json:"global_new_elo"`
	PrevRating    interface{}        `json:"prev_rating"`
	EloConstK     float64            `json:"elo_const_k"`
	EloConstD     float64            `json:"elo_const_d"`
	StartingElo   float64            `json:"starting_elo"`
	WinReward     float64            `json:"win_reward"`
}

func (q *Queries) ListMatchesWithPlayersByGame(ctx context.Context, id int32) ([]ListMatchesWithPlayersByGameRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithPlayersByGame, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesWithPlayersByGameRow{}
	for rows.Next() {
		var i ListMatchesWithPlayersByGameRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameID,
			&i.GameName,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GlobalEloPay,
			&i.GlobalEloEarn,
			&i.GlobalNewElo,
			&i.PrevRating,
			&i.EloConstK,
			&i.EloConstD,
			&i.StartingElo,
			&i.WinReward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesWithPlayersByGameFromDB = `-- name: ListMatchesWithPlayersByGameFromDB :many
SELECT
    m.id AS match_id,
    m.date,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.game_elo_pay,
    s.game_elo_earn,
    s.game_new_elo
FROM matches m
JOIN match_scores s ON s.match_id = m.id
JOIN players p ON p.id = s.player_id
WHERE m.game_id = $1
  AND s.game_new_elo IS NOT NULL
ORDER BY m.date ASC, m.id ASC, s.score DESC
`

type ListMatchesWithPlayersByGameFromDBRow struct {
	MatchID     int32              `json:"match_id"`
	Date        pgtype.Timestamptz `json:"date"`
	PlayerID    int32              `json:"player_id"`
	PlayerName  string             `json:"player_name"`
	Score       float64            `json:"score"`
	GameEloPay  pgtype.Float8      `json:"game_elo_pay"`
	GameEloEarn pgtype.Float8      `json:"game_elo_earn"`
	GameNewElo  pgtype.Float8      `json:"game_new_elo"`
}

func (q *Queries) ListMatchesWithPlayersByGameFromDB(ctx context.Context, gameID int32) ([]ListMatchesWithPlayersByGameFromDBRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithPlayersByGameFromDB, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesWithPlayersByGameFromDBRow{}
	for rows.Next() {
		var i ListMatchesWithPlayersByGameFromDBRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GameEloPay,
			&i.GameEloEarn,
			&i.GameNewElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesWithPlayersPaginated = `-- name: ListMatchesWithPlayersPaginated :many
WITH paginated_matches AS (
    SELECT DISTINCT m.id, m.date, m.game_id
    FROM matches m
    JOIN match_scores ms ON ms.match_id = m.id
    WHERE
        ($1::int4 IS NULL OR m.game_id = $1::int4)
        AND ($2::int4 IS NULL OR ms.player_id = $2::int4)
        AND (
            $3::timestamptz IS NULL
            OR m.date < $3::timestamptz
        )
    ORDER BY m.date DESC, m.id DESC
    LIMIT $4::int4
)
SELECT
    pm.id AS match_id,
    pm.date,
    g.id AS game_id,
    g.name AS game_name,
    p.id AS player_id,
    p.name AS player_name,
    s.score,
    s.global_elo_pay,
    s.global_elo_earn,
    s.global_new_elo,
    CASE WHEN prev_match_score.global_new_elo IS NULL THEN NULL
    ELSE prev_match_score.global_new_elo END AS prev_rating
FROM paginated_matches pm
JOIN games g ON g.id = pm.game_id
JOIN match_scores s ON s.match_id = pm.id
JOIN players p ON p.id = s.player_id
LEFT JOIN LATERAL (
    SELECT ms.global_new_elo
    FROM match_scores ms
    JOIN matches prev_m ON prev_m.id = ms.match_id
    WHERE ms.player_id = p.id AND prev_m.date < pm.date
    ORDER BY prev_m.date DESC, prev_m.id DESC
    LIMIT 1
) prev_match_score ON true
ORDER BY pm.date DESC, pm.id DESC, s.score DESC
`

type ListMatchesWithPlayersPaginatedParams struct {
	GameID     pgtype.Int4        `json:"game_id"`
	PlayerID   pgtype.Int4        `json:"player_id"`
	CursorDate pgtype.Timestamptz `json:"cursor_date"`
	Limit      int32              `json:"limit"`
}

type ListMatchesWithPlayersPaginatedRow struct {
	MatchID       int32              `json:"match_id"`
	Date          pgtype.Timestamptz `json:"date"`
	GameID        int32              `json:"game_id"`
	GameName      string             `json:"game_name"`
	PlayerID      int32              `json:"player_id"`
	PlayerName    string             `json:"player_name"`
	Score         float64            `json:"score"`
	GlobalEloPay  float64            `json:"global_elo_pay"`
	GlobalEloEarn float64            `json:"global_elo_earn"`
	GlobalNewElo  float64            `json:"global_new_elo"`
	PrevRating    interface{}        `json:"prev_rating"`
}

func (q *Queries) ListMatchesWithPlayersPaginated(ctx context.Context, arg ListMatchesWithPlayersPaginatedParams) ([]ListMatchesWithPlayersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithPlayersPaginated,
		arg.GameID,
		arg.PlayerID,
		arg.CursorDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesWithPlayersPaginatedRow{}
	for rows.Next() {
		var i ListMatchesWithPlayersPaginatedRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.GameID,
			&i.GameName,
			&i.PlayerID,
			&i.PlayerName,
			&i.Score,
			&i.GlobalEloPay,
			&i.GlobalEloEarn,
			&i.GlobalNewElo,
			&i.PrevRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatch = `-- name: UpdateMatch :exec
UPDATE matches
SET date = $2, game_id = $3
WHERE id = $1
`

type UpdateMatchParams struct {
	ID     int32              `json:"id"`
	Date   pgtype.Timestamptz `json:"date"`
	GameID int32              `json:"game_id"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) error {
	_, err := q.db.Exec(ctx, updateMatch, arg.ID, arg.Date, arg.GameID)
	return err
}

const updateMatchScoreGameElo = `-- name: UpdateMatchScoreGameElo :exec
UPDATE match_scores
SET game_elo_pay = $3, game_elo_earn = $4, game_new_elo = $5
WHERE match_id = $1 AND player_id = $2
`

type UpdateMatchScoreGameEloParams struct {
	MatchID     int32         `json:"match_id"`
	PlayerID    int32         `json:"player_id"`
	GameEloPay  pgtype.Float8 `json:"game_elo_pay"`
	GameEloEarn pgtype.Float8 `json:"game_elo_earn"`
	GameNewElo  pgtype.Float8 `json:"game_new_elo"`
}

func (q *Queries) UpdateMatchScoreGameElo(ctx context.Context, arg UpdateMatchScoreGameEloParams) error {
	_, err := q.db.Exec(ctx, updateMatchScoreGameElo,
		arg.MatchID,
		arg.PlayerID,
		arg.GameEloPay,
		arg.GameEloEarn,
		arg.GameNewElo,
	)
	return err
}

const updateMatchScoreGlobalElo = `-- name: UpdateMatchScoreGlobalElo :exec
UPDATE match_scores
SET global_elo_pay = $3, global_elo_earn = $4, global_new_elo = $5
WHERE match_id = $1 AND player_id = $2
`

type UpdateMatchScoreGlobalEloParams struct {
	MatchID       int32   `json:"match_id"`
	PlayerID      int32   `json:"player_id"`
	GlobalEloPay  float64 `json:"global_elo_pay"`
	GlobalEloEarn float64 `json:"global_elo_earn"`
	GlobalNewElo  float64 `json:"global_new_elo"`
}

func (q *Queries) UpdateMatchScoreGlobalElo(ctx context.Context, arg UpdateMatchScoreGlobalEloParams) error {
	_, err := q.db.Exec(ctx, updateMatchScoreGlobalElo,
		arg.MatchID,
		arg.PlayerID,
		arg.GlobalEloPay,
		arg.GlobalEloEarn,
		arg.GlobalNewElo,
	)
	return err
}

const upsertMatchScore = `-- name: UpsertMatchScore :exec
INSERT INTO match_scores (match_id, player_id, score, global_elo_pay, global_elo_earn, global_new_elo, game_elo_pay, game_elo_earn, game_new_elo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (match_id, player_id)
DO UPDATE SET
    score = EXCLUDED.score,
    global_elo_pay = EXCLUDED.global_elo_pay,
    global_elo_earn = EXCLUDED.global_elo_earn,
    global_new_elo = EXCLUDED.global_new_elo,
    game_elo_pay = EXCLUDED.game_elo_pay,
    game_elo_earn = EXCLUDED.game_elo_earn,
    game_new_elo = EXCLUDED.game_new_elo
`

type UpsertMatchScoreParams struct {
	MatchID       int32         `json:"match_id"`
	PlayerID      int32         `json:"player_id"`
	Score         float64       `json:"score"`
	GlobalEloPay  float64       `json:"global_elo_pay"`
	GlobalEloEarn float64       `json:"global_elo_earn"`
	GlobalNewElo  float64       `json:"global_new_elo"`
	GameEloPay    pgtype.Float8 `json:"game_elo_pay"`
	GameEloEarn   pgtype.Float8 `json:"game_elo_earn"`
	GameNewElo    pgtype.Float8 `json:"game_new_elo"`
}

func (q *Queries) UpsertMatchScore(ctx context.Context, arg UpsertMatchScoreParams) error {
	_, err := q.db.Exec(ctx, upsertMatchScore,
		arg.MatchID,
		arg.PlayerID,
		arg.Score,
		arg.GlobalEloPay,
		arg.GlobalEloEarn,
		arg.GlobalNewElo,
		arg.GameEloPay,
		arg.GameEloEarn,
		arg.GameNewElo,
	)
	return err
}
