// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bet struct {
	ID       int32              `json:"id"`
	MarketID int32              `json:"market_id"`
	PlayerID int32              `json:"player_id"`
	Outcome  string             `json:"outcome"`
	Amount   float64            `json:"amount"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

type Club struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	GeologistName pgtype.Text `json:"geologist_name"`
}

type Correction struct {
	ID            int32              `json:"id"`
	PlayerID      int32              `json:"player_id"`
	Discriminator string             `json:"discriminator"`
	Diff          float64            `json:"diff"`
	Date          pgtype.Timestamptz `json:"date"`
}

type EloSetting struct {
	EffectiveDate             pgtype.Timestamptz `json:"effective_date"`
	EloConstK                 float64            `json:"elo_const_k"`
	EloConstD                 float64            `json:"elo_const_d"`
	StartingElo               float64            `json:"starting_elo"`
	WinReward                 float64            `json:"win_reward"`
	StartingRating            float64            `json:"starting_rating"`
	NewbieLeagueGoal          float64            `json:"newbie_league_goal"`
	EliteLeagueMatches6months int32              `json:"elite_league_matches_6months"`
	EliteLeagueMatches2months int32              `json:"elite_league_matches_2months"`
	RatingMaxK                float64            `json:"rating_max_k"`
	RatingKTau                float64            `json:"rating_k_tau"`
}

type Game struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type GameArenaSettlement struct {
	ID            int32              `json:"id"`
	GameID        int32              `json:"game_id"`
	PlayerID      int32              `json:"player_id"`
	Date          pgtype.Timestamptz `json:"date"`
	RatingAfter   float64            `json:"rating_after"`
	EloAfter      float64            `json:"elo_after"`
	Discriminator string             `json:"discriminator"`
	MatchID       pgtype.Int4        `json:"match_id"`
	EloStaked     float64            `json:"elo_staked"`
	EloEarned     float64            `json:"elo_earned"`
	RatingStaked  float64            `json:"rating_staked"`
	RatingEarned  float64            `json:"rating_earned"`
	League        string             `json:"league"`
}

type GlobalArenaSettlement struct {
	ID            int32              `json:"id"`
	PlayerID      int32              `json:"player_id"`
	Date          pgtype.Timestamptz `json:"date"`
	RatingAfter   float64            `json:"rating_after"`
	EloAfter      float64            `json:"elo_after"`
	Discriminator string             `json:"discriminator"`
	MatchID       pgtype.Int4        `json:"match_id"`
	MarketID      pgtype.Int4        `json:"market_id"`
	CorrectionID  pgtype.Int4        `json:"correction_id"`
	EloStaked     float64            `json:"elo_staked"`
	EloEarned     float64            `json:"elo_earned"`
	RatingStaked  float64            `json:"rating_staked"`
	RatingEarned  float64            `json:"rating_earned"`
	League        string             `json:"league"`
}

type Market struct {
	ID                int32              `json:"id"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
	ResolutionOutcome pgtype.Text        `json:"resolution_outcome"`
	BettingClosedAt   pgtype.Timestamptz `json:"betting_closed_at"`
}

type MarketMatchWinnerParam struct {
	MarketID          int32   `json:"market_id"`
	TargetPlayerID    int32   `json:"target_player_id"`
	RequiredPlayerIds []int32 `json:"required_player_ids"`
	GameIds           []int32 `json:"game_ids"`
}

type MarketWinStreakParam struct {
	MarketID       int32       `json:"market_id"`
	TargetPlayerID int32       `json:"target_player_id"`
	WinsRequired   int32       `json:"wins_required"`
	MaxLosses      pgtype.Int4 `json:"max_losses"`
	GameIds        []int32     `json:"game_ids"`
}

type Match struct {
	ID     int32              `json:"id"`
	Date   pgtype.Timestamptz `json:"date"`
	GameID int32              `json:"game_id"`
}

type MatchScore struct {
	MatchID  int32   `json:"match_id"`
	PlayerID int32   `json:"player_id"`
	Score    float64 `json:"score"`
}

type Player struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	GeologistName pgtype.Text `json:"geologist_name"`
	BetLimit      float64     `json:"bet_limit"`
}

type PlayerClubMembership struct {
	ClubID   int32 `json:"club_id"`
	PlayerID int32 `json:"player_id"`
}

type SkullKingTable struct {
	ID                 pgtype.UUID `json:"id"`
	HostUserID         int32       `json:"host_user_id"`
	GameState          []byte      `json:"game_state"`
	ConnectedPlayerIds []int32     `json:"connected_player_ids"`
	CreatedAt          time.Time   `json:"created_at"`
	ExpiresAt          time.Time   `json:"expires_at"`
}

type User struct {
	ID                  int32       `json:"id"`
	AllowEditing        bool        `json:"allow_editing"`
	GoogleOauthUserID   string      `json:"google_oauth_user_id"`
	GoogleOauthUserName string      `json:"google_oauth_user_name"`
	PlayerID            pgtype.Int4 `json:"player_id"`
}
