// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bet struct {
	ID       int32              `json:"id"`
	MarketID int32              `json:"market_id"`
	PlayerID int32              `json:"player_id"`
	Outcome  string             `json:"outcome"`
	Amount   float64            `json:"amount"`
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
}

type BetSettlementDetail struct {
	MarketID int32   `json:"market_id"`
	PlayerID int32   `json:"player_id"`
	Staked   float64 `json:"staked"`
	Earned   float64 `json:"earned"`
}

type Club struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	GeologistName pgtype.Text `json:"geologist_name"`
}

type EloSetting struct {
	EffectiveDate pgtype.Timestamptz `json:"effective_date"`
	EloConstK     float64            `json:"elo_const_k"`
	EloConstD     float64            `json:"elo_const_d"`
	StartingElo   float64            `json:"starting_elo"`
	WinReward     float64            `json:"win_reward"`
}

type Game struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Market struct {
	ID                int32              `json:"id"`
	MarketType        string             `json:"market_type"`
	Status            string             `json:"status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ClosesAt          pgtype.Timestamptz `json:"closes_at"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ResolutionMatchID pgtype.Int4        `json:"resolution_match_id"`
	ResolutionOutcome pgtype.Text        `json:"resolution_outcome"`
}

type MarketMatchWinnerParam struct {
	MarketID          int32       `json:"market_id"`
	TargetPlayerID    int32       `json:"target_player_id"`
	RequiredPlayerIds []int32     `json:"required_player_ids"`
	GameID            pgtype.Int4 `json:"game_id"`
}

type MarketWinStreakParam struct {
	MarketID       int32       `json:"market_id"`
	TargetPlayerID int32       `json:"target_player_id"`
	GameID         int32       `json:"game_id"`
	WinsRequired   int32       `json:"wins_required"`
	MaxLosses      pgtype.Int4 `json:"max_losses"`
}

type Match struct {
	ID     int32              `json:"id"`
	Date   pgtype.Timestamptz `json:"date"`
	GameID int32              `json:"game_id"`
}

type MatchScore struct {
	MatchID     int32   `json:"match_id"`
	PlayerID    int32   `json:"player_id"`
	Score       float64 `json:"score"`
	RatingPay   float64 `json:"rating_pay"`
	RatingEarn  float64 `json:"rating_earn"`
	GameEloPay  float64 `json:"game_elo_pay"`
	GameEloEarn float64 `json:"game_elo_earn"`
	GameNewElo  float64 `json:"game_new_elo"`
}

type Player struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	GeologistName pgtype.Text `json:"geologist_name"`
	BetLimit      float64     `json:"bet_limit"`
}

type PlayerClubMembership struct {
	ClubID   int32 `json:"club_id"`
	PlayerID int32 `json:"player_id"`
}

type PlayerRating struct {
	ID         int32              `json:"id"`
	Date       pgtype.Timestamptz `json:"date"`
	PlayerID   int32              `json:"player_id"`
	Rating     float64            `json:"rating"`
	SourceType string             `json:"source_type"`
	MatchID    pgtype.Int4        `json:"match_id"`
	MarketID   pgtype.Int4        `json:"market_id"`
}

type User struct {
	ID                  int32       `json:"id"`
	AllowEditing        bool        `json:"allow_editing"`
	GoogleOauthUserID   string      `json:"google_oauth_user_id"`
	GoogleOauthUserName string      `json:"google_oauth_user_name"`
	PlayerID            pgtype.Int4 `json:"player_id"`
}
