// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayersIfNotExists = `-- name: AddPlayersIfNotExists :many
INSERT INTO players (id, name)
SELECT unnest($1::uuid[]) AS id, unnest($2::text[]) AS name
ON CONFLICT (name) DO NOTHING
RETURNING id, name
`

type AddPlayersIfNotExistsParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
}

type AddPlayersIfNotExistsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) AddPlayersIfNotExists(ctx context.Context, arg AddPlayersIfNotExistsParams) ([]AddPlayersIfNotExistsRow, error) {
	rows, err := q.db.Query(ctx, addPlayersIfNotExists, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddPlayersIfNotExistsRow{}
	for rows.Next() {
		var i AddPlayersIfNotExistsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, name, geologist_name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, name, geologist_name, bet_limit
`

type CreatePlayerParams struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	GeologistName pgtype.Text `json:"geologist_name"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.ID, arg.Name, arg.GeologistName)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.BetLimit,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, geologist_name, bet_limit FROM players
WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.BetLimit,
	)
	return i, err
}

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name, geologist_name, bet_limit FROM players
WHERE name = $1
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.BetLimit,
	)
	return i, err
}

const getPlayerGameEloStats = `-- name: GetPlayerGameEloStats :many
SELECT
  g.id::text AS game_id,
  g.name     AS game_name,
  SUM(gas.elo_earned + gas.elo_staked)::float8 AS elo_earned
FROM match_scores ms
JOIN matches m ON ms.match_id = m.id
JOIN games g ON m.game_id = g.id
JOIN global_arena_settlement gas ON gas.match_id = ms.match_id AND gas.player_id = ms.player_id AND gas.discriminator = 'match'
WHERE ms.player_id = $1
GROUP BY g.id, g.name
ORDER BY elo_earned DESC
`

type GetPlayerGameEloStatsRow struct {
	GameID    string  `json:"game_id"`
	GameName  string  `json:"game_name"`
	EloEarned float64 `json:"elo_earned"`
}

func (q *Queries) GetPlayerGameEloStats(ctx context.Context, playerID string) ([]GetPlayerGameEloStatsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerGameEloStats, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerGameEloStatsRow{}
	for rows.Next() {
		var i GetPlayerGameEloStatsRow
		if err := rows.Scan(&i.GameID, &i.GameName, &i.EloEarned); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerGameStats = `-- name: GetPlayerGameStats :many
SELECT
  g.id::text AS game_id,
  g.name     AS game_name,
  COUNT(ms.match_id)::int AS matches_count,
  COUNT(CASE WHEN ms.score = max_scores.max_score THEN 1 END)::int AS wins
FROM match_scores ms
JOIN matches m ON ms.match_id = m.id
JOIN games g ON m.game_id = g.id
JOIN (
  SELECT match_id, MAX(score) AS max_score
  FROM match_scores
  GROUP BY match_id
) max_scores ON max_scores.match_id = ms.match_id
WHERE ms.player_id = $1
GROUP BY g.id, g.name
ORDER BY matches_count DESC
LIMIT 10
`

type GetPlayerGameStatsRow struct {
	GameID       string `json:"game_id"`
	GameName     string `json:"game_name"`
	MatchesCount int32  `json:"matches_count"`
	Wins         int32  `json:"wins"`
}

func (q *Queries) GetPlayerGameStats(ctx context.Context, playerID string) ([]GetPlayerGameStatsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerGameStats, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerGameStatsRow{}
	for rows.Next() {
		var i GetPlayerGameStatsRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameName,
			&i.MatchesCount,
			&i.Wins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerUserLinks = `-- name: ListPlayerUserLinks :many
SELECT player_id, id AS user_id FROM users WHERE player_id IS NOT NULL
`

type ListPlayerUserLinksRow struct {
	PlayerID *string `json:"player_id"`
	UserID   string  `json:"user_id"`
}

func (q *Queries) ListPlayerUserLinks(ctx context.Context) ([]ListPlayerUserLinksRow, error) {
	rows, err := q.db.Query(ctx, listPlayerUserLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerUserLinksRow{}
	for rows.Next() {
		var i ListPlayerUserLinksRow
		if err := rows.Scan(&i.PlayerID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, geologist_name, bet_limit FROM players
ORDER BY name
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GeologistName,
			&i.BetLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerForEloCalculation = `-- name: LockPlayerForEloCalculation :one
SELECT id FROM players WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPlayerForEloCalculation(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockPlayerForEloCalculation, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET name = $2
WHERE id = $1
RETURNING id, name, geologist_name, bet_limit
`

type UpdatePlayerParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer, arg.ID, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GeologistName,
		&i.BetLimit,
	)
	return i, err
}
