// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_ranks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPlayersWithStats = `-- name: ListPlayersWithStats :many
SELECT p.id, p.name,
  CASE WHEN latest_elo.rating_after IS NULL THEN NULL ELSE latest_elo.rating_after END AS rating,
  CASE WHEN latest_elo.elo_after IS NULL THEN NULL ELSE latest_elo.elo_after END AS elo,
  COALESCE(latest_elo.league, 'newbie') AS league,
  COALESCE(cnt_60.cnt, 0) AS cnt_60,
  COALESCE(cnt_180.cnt, 0) AS cnt_180
FROM players p
LEFT JOIN LATERAL (
  SELECT gas.rating_after, gas.elo_after, gas.league
  FROM global_arena_settlement gas
  WHERE gas.player_id = p.id AND gas.date <= $1
  ORDER BY gas.date DESC, gas.id DESC
  LIMIT 1
) latest_elo ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS cnt FROM matches m
  JOIN match_scores ms ON ms.match_id = m.id
  WHERE ms.player_id = p.id AND m.date >= ($1 - interval '60 days') AND m.date <= $1
) cnt_60 ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS cnt FROM matches m
  JOIN match_scores ms ON ms.match_id = m.id
  WHERE ms.player_id = p.id AND m.date >= ($1 - interval '180 days') AND m.date <= $1
) cnt_180 ON true
ORDER BY latest_elo.rating_after DESC NULLS LAST, p.name
`

type ListPlayersWithStatsRow struct {
	ID     int32       `json:"id"`
	Name   string      `json:"name"`
	Rating interface{} `json:"rating"`
	Elo    interface{} `json:"elo"`
	League string      `json:"league"`
	Cnt60  int64       `json:"cnt_60"`
	Cnt180 int64       `json:"cnt_180"`
}

func (q *Queries) ListPlayersWithStats(ctx context.Context, date pgtype.Timestamptz) ([]ListPlayersWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listPlayersWithStats, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersWithStatsRow{}
	for rows.Next() {
		var i ListPlayersWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rating,
			&i.Elo,
			&i.League,
			&i.Cnt60,
			&i.Cnt180,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
