// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

type Querier interface {
	// Arena match link queries (ADR-27, ADR-28 amendment): one arena_matches
	// table serves both link-only arena flavors — camp arenas (organizer-managed
	// checkboxes) and tournament arenas (written by the bracket slot mechanics).
	// Camp membership is written when a match is created with camp_arena_ids and
	// never altered afterwards except by the edit-form desired-set diff; the
	// tournament flavor attaches at slot-link time and detaches/voids with it.
	AddArenaMatch(ctx context.Context, arg AddArenaMatchParams) error
	// Opens a membership stint at now() (ADR-36). A still-active stint for the
	// same (club, player) makes this a no-op via the partial unique index
	// player_club_membership_active_uniq.
	AddClubMember(ctx context.Context, arg AddClubMemberParams) error
	AddGame(ctx context.Context, arg AddGameParams) (Game, error)
	AddGameTablePlayer(ctx context.Context, arg AddGameTablePlayerParams) (GameTable, error)
	AddGameTag(ctx context.Context, arg AddGameTagParams) error
	AddPlayersIfNotExists(ctx context.Context, arg AddPlayersIfNotExistsParams) ([]AddPlayersIfNotExistsRow, error)
	AddSlotAdvance(ctx context.Context, arg AddSlotAdvanceParams) error
	AddSlotMatch(ctx context.Context, arg AddSlotMatchParams) error
	// The tournament-membership row: the tournament's auto-created arena is
	// resolved in-SQL (every running tournament has one; acceptance and attach
	// only write membership for running tournaments).
	AddTournamentArenaMatch(ctx context.Context, arg AddTournamentArenaMatchParams) error
	// ---------------------------------------------------------------------------
	// Game pool
	// ---------------------------------------------------------------------------
	AddTournamentGame(ctx context.Context, arg AddTournamentGameParams) error
	// ---------------------------------------------------------------------------
	// Participants
	// ---------------------------------------------------------------------------
	AddTournamentParticipant(ctx context.Context, arg AddTournamentParticipantParams) error
	// Uniqueness guard for the user-facing arena CRUD (case-insensitive).
	// @exclude_id skips the arena being updated; NULL on create.
	ArenaNameExists(ctx context.Context, arg ArenaNameExistsParams) (bool, error)
	// Returns rating_after and elo_after ordered by date for the player graph.
	ArenaRatingHistory(ctx context.Context, arg ArenaRatingHistoryParams) ([]ArenaRatingHistoryRow, error)
	// Conditional clear: stale_at must still be the mark the recalculation
	// started from; a re-mark during the run leaves the arena stale (staleness
	// cancellation, ADR-24).
	ClearArenaStale(ctx context.Context, arg ClearArenaStaleParams) error
	// Invalidate the seat caches fed by a source slot whose advancement set was
	// rewritten or voided (the downstream slot re-derives on its next completion).
	ClearSlotSeatCaches(ctx context.Context, sourceSlotID id.ID) error
	// The champion is invalidated by a post-completion bracket change (an edit
	// cascade); the tournament re-runs its final and completes again.
	ClearTournamentWinner(ctx context.Context, argID id.ID) error
	CountMatchesFromDate(ctx context.Context, date pgtype.Timestamptz) (int64, error)
	// Matches of one player inside the arena (per the membership function) within
	// [date_from, date_to] — the elite promotion counters. Camp arenas have no
	// leagues, so the counters are never consulted for them.
	CountPlayerMatchesInArenaInPeriod(ctx context.Context, arg CountPlayerMatchesInArenaInPeriodParams) (int32, error)
	CountTournamentParticipants(ctx context.Context, tournamentID id.ID) (int32, error)
	// Seats still waiting for their source slot (player_id IS NULL by design for
	// source seats).
	CountUnresolvedSeats(ctx context.Context, slotID id.ID) (int32, error)
	CreateArena(ctx context.Context, arg CreateArenaParams) (Arena, error)
	// A new club is a plain group (ADR-36): no tenant.
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateEloSettings(ctx context.Context, arg CreateEloSettingsParams) error
	CreateGameTable(ctx context.Context, arg CreateGameTableParams) (GameTable, error)
	// Every market belongs to a tenant (ADR-36): the create path is
	// POST /tenants/{id}/markets and the auto-created tournament_winner market
	// inherits the tournament's tenant.
	CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMatchFilter(ctx context.Context, arg CreateMatchFilterParams) (id.ID, error)
	CreateMatchWinnerParams(ctx context.Context, arg CreateMatchWinnerParamsParams) error
	// The "other" outcome of a match_winner market: tie at first place or a
	// non-target winner.
	CreateOtherOutcome(ctx context.Context, marketID id.ID) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	// Bulk-inserts the per-target "player wins" outcomes of a match_winner market.
	CreatePlayerOutcomes(ctx context.Context, arg CreatePlayerOutcomesParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Tournament queries (ADR-26). The bracket materialization has its own file
	// (tournament_brackets.sql); this one covers the entity itself: lifecycle
	// state, registration-time config, participants, and the game pool.
	// Client-supplied id (ADR-06): the insert is an idempotent create — a replay
	// with the same id inserts nothing and the service fetches the stored row.
	// elimination stays NULL until start stamps the chosen plan's family.
	// Every tournament belongs to a tenant (ADR-36): the create path is
	// POST /tenants/{id}/tournaments.
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error)
	CreateTournamentRound(ctx context.Context, arg CreateTournamentRoundParams) (TournamentRound, error)
	CreateTournamentSeat(ctx context.Context, arg CreateTournamentSeatParams) error
	CreateTournamentSlot(ctx context.Context, arg CreateTournamentSlotParams) (TournamentSlot, error)
	CreateTournamentWinnerParams(ctx context.Context, arg CreateTournamentWinnerParamsParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (id.ID, error)
	CreateWinStreakParams(ctx context.Context, arg CreateWinStreakParamsParams) error
	// The two fixed Да/Нет outcomes of a win_streak market.
	CreateYesNoOutcomes(ctx context.Context, marketID id.ID) error
	DeleteAllMatchScores(ctx context.Context) error
	DeleteAllMatches(ctx context.Context) error
	// Returns the deleted row so the audit trail can capture the name.
	DeleteArena(ctx context.Context, argID id.ID) (DeleteArenaRow, error)
	// Detach a match from a camp arena (the edit-form desired-set diff, ADR-27):
	// the camp is stale-marked by the caller and the replay rewrites its
	// settlements and medal stats.
	DeleteArenaMatch(ctx context.Context, arg DeleteArenaMatchParams) error
	// Removes both buyer ('market') and guarantor ('market_guarantor') settlement
	// rows for a market (used by unsettle/recalculation).
	DeleteArenaSettlementByMarket(ctx context.Context, arg DeleteArenaSettlementByMarketParams) error
	// Replay support for the arena updater: removes the arena's MATCH settlement
	// rows from the date on — the replay re-settles matches only. Market rows
	// belong to their own lifecycle (they re-settle via the unsettle/re-resolve
	// sweep in RecalculateFrom, per-market in the owning tenant's arena) and must
	// survive an arena replay.
	DeleteArenaSettlementsFromDate(ctx context.Context, arg DeleteArenaSettlementsFromDateParams) error
	// ---------------------------------------------------------------------------
	// Precalculated stats
	// ---------------------------------------------------------------------------
	DeleteArenaStats(ctx context.Context, arenaID id.ID) error
	DeleteClub(ctx context.Context, argID id.ID) (Club, error)
	DeleteEloSettings(ctx context.Context, effectiveDate pgtype.Timestamptz) error
	DeleteExpiredGameTables(ctx context.Context) error
	DeleteGame(ctx context.Context, argID id.ID) (Game, error)
	DeleteGameTable(ctx context.Context, argID id.ID) error
	DeleteMarket(ctx context.Context, argID id.ID) error
	DeleteMatchScores(ctx context.Context, matchID id.ID) error
	// Returns the deleted row so the audit trail can capture the player's name.
	DeletePlayer(ctx context.Context, argID id.ID) (Player, error)
	DeleteSlotAdvances(ctx context.Context, slotID id.ID) error
	DeleteSlotMatch(ctx context.Context, arg DeleteSlotMatchParams) error
	DeleteSlotMatches(ctx context.Context, slotID id.ID) error
	// Cascade invalidation: a slot whose outcome was voided loses its seat rows
	// and is re-seated from its sources once the upstream replays.
	DeleteSlotSeats(ctx context.Context, slotID id.ID) error
	// Single delete covering match AND market settlements of «Синие люди»'s main
	// arena (the settlement sweep's anchor — ADR-36). Other clubs' market rows are
	// removed by the per-market deletes in UnsettleMarketsFromDate, in each
	// market's own arena. Called at the start of RecalculateFrom.
	DeleteSweepArenaSettlementsFromDate(ctx context.Context, date pgtype.Timestamptz) error
	DeleteTag(ctx context.Context, argID id.ID) (Tag, error)
	// The match left its slot (detach or void, ADR-26): it leaves the tournament
	// arena too.
	DeleteTournamentArenaMatch(ctx context.Context, arg DeleteTournamentArenaMatchParams) error
	// The pool is small; the PUT handler rewrites it wholesale inside its tx.
	DeleteTournamentGames(ctx context.Context, tournamentID id.ID) error
	// The editor's desired-set semantics (PUT /tournaments): drop everyone absent
	// from the submitted set. An empty array removes everyone.
	DeleteTournamentParticipantsNotIn(ctx context.Context, arg DeleteTournamentParticipantsNotInParams) error
	DeleteUser(ctx context.Context, argID id.ID) error
	// Arena queries (ADR-24, ADR-27, ADR-26). The "does this match belong to this
	// arena" condition has ONE canonical structure, dispatched per flavor:
	//
	//   * tenant arenas (arenas.tenant_id, ADR-36): tenant_arena_contains_match() —
	//     openness evaluated at the match date against the player_club_membership
	//     stints of the tenant's clubs, per the tenant's CURRENT mode. It probes
	//     tables, so it is a separate STABLE function — the explicit exception to
	//     the ADR-28 pure-expression rule — and the queries dispatch with
	//     CASE WHEN a.tenant_id IS NOT NULL. It only ever runs for tenant arenas,
	//     whose count stays proportional to the number of tenants.
	//   * every other flavor: the arena_contains_match() function created by
	//     migrations 054–056 (see adr/28-arena-membership-function.md). The
	//     queries below call it; never inline the condition back.
	//
	// The function is a pure expression: callers pass the columns they already
	// joined PLUS the probes it cannot express without sub-SELECTs — the camp-link
	// EXISTS, the tournament-link EXISTS and the filtered-tag EXISTS (written
	// right in the call). Never bury a sub-SELECT in the function body: bodies
	// with sub-SELECTs are never inlined, and an opaque call re-runs its subplans
	// per (arena, match) pair — measured 24s (id args) and 3.3s (column args)
	// against 350ms for the inlined form on the arenas list at 2026-09 data scale.
	// The read queries share one 16-column projection (arena row + its filter
	// columns). Keep the column list identical across them: pkg/elo/arena_rows_test.go
	// asserts the generated row structs stay field-identical.
	GetArena(ctx context.Context, argID id.ID) (GetArenaRow, error)
	GetArenaByGame(ctx context.Context, gameID *id.ID) (GetArenaByGameRow, error)
	// A tenant's main arena (ADR-36); empty when the tenant has none.
	GetArenaByTenant(ctx context.Context, tenantID *id.ID) (GetArenaByTenantRow, error)
	// Auto-managed bracket-tournament arenas (ADR-24 anchor, reused by ADR-26);
	// empty until ADR-26 creates them.
	GetArenaByTournament(ctx context.Context, tournamentID *id.ID) (GetArenaByTournamentRow, error)
	// Row-locked variant used by the recalculation updater: concurrent dirty marks
	// queue behind the lock and apply after the recalculation commits.
	GetArenaForUpdate(ctx context.Context, argID id.ID) (GetArenaForUpdateRow, error)
	GetBetsAggregatedByOutcome(ctx context.Context, marketID id.ID) ([]GetBetsAggregatedByOutcomeRow, error)
	// Per-buy rows (each carries the shares bought and the maker fee charged) used
	// by share settlement.
	GetBetsForSettlement(ctx context.Context, marketID id.ID) ([]GetBetsForSettlementRow, error)
	GetBetsOnMarketPlacedBetween(ctx context.Context, arg GetBetsOnMarketPlacedBetweenParams) ([]GetBetsOnMarketPlacedBetweenRow, error)
	// HAVING guards the aggregate: with no linked matches it returns zero rows
	// (ErrNoRows) instead of a (NULL, NULL) row that can't scan into the
	// non-nullable time.Time. The camp date-narrowing guard reads this.
	GetCampMatchDateRange(ctx context.Context, arenaID id.ID) (GetCampMatchDateRangeRow, error)
	GetClub(ctx context.Context, argID id.ID) ([]GetClubRow, error)
	// Old-name read for the rename audit trail (ADR-14).
	GetClubByID(ctx context.Context, argID id.ID) (Club, error)
	GetCountMatchesByGame(ctx context.Context, gameID id.ID) (int64, error)
	GetEloSettingsForDate(ctx context.Context, effectiveDate pgtype.Timestamptz) (GetEloSettingsForDateRow, error)
	GetGameByID(ctx context.Context, argID id.ID) (Game, error)
	GetGameByName(ctx context.Context, name string) (Game, error)
	GetGameTable(ctx context.Context, argID id.ID) (GameTable, error)
	GetGameTableForUpdate(ctx context.Context, argID id.ID) (GameTable, error)
	GetLatestEloSettings(ctx context.Context) (GetLatestEloSettingsRow, error)
	GetMarket(ctx context.Context, argID id.ID) (GetMarketRow, error)
	// Ordered bet stream used to reconstruct the market's price history by
	// replaying the LMSR from its creation state q=0.
	GetMarketBetsForPriceHistory(ctx context.Context, marketID id.ID) ([]GetMarketBetsForPriceHistoryRow, error)
	// Total maker fees the market generated (the commission rollup of ADR-20).
	GetMarketFeeCollected(ctx context.Context, marketID id.ID) (float64, error)
	// Guarantor-role settlement rows (discriminator 'market_guarantor') — the
	// per-guarantor payout rollup. A player who is both buyer and guarantor has a
	// separate buyer row (discriminator 'market'), so their entry here carries only
	// the house result (ADR-10). DISTINCT because a player may hold several
	// guarantee wagers but settles as one guarantor row; the sort key is selected
	// so DISTINCT accepts the ORDER BY. A market's rows live in exactly one arena
	// (its tenant's main arena, ADR-36), so market_id alone identifies them.
	GetMarketGuarantorPayouts(ctx context.Context, marketID id.ID) ([]GetMarketGuarantorPayoutsRow, error)
	GetMarketResolvedAt(ctx context.Context, argID id.ID) (pgtype.Timestamptz, error)
	GetMarketsForUnsettle(ctx context.Context, resolvedAt pgtype.Timestamptz) ([]GetMarketsForUnsettleRow, error)
	// Returns resolved_at and betting_closed_at for the history conflict validation.
	// betting_closed_at is a user event timestamp — preserved even after unsettling.
	GetMarketsForUnsettleWithResolvedAt(ctx context.Context, resolvedAt pgtype.Timestamptz) ([]GetMarketsForUnsettleWithResolvedAtRow, error)
	GetMatch(ctx context.Context, argID id.ID) (Match, error)
	// Current player→score rows of a match. Read before an edit rewrites them so
	// the audit diff can describe what changed.
	GetMatchScores(ctx context.Context, matchID id.ID) ([]GetMatchScoresRow, error)
	GetMatchScoresForMatch(ctx context.Context, matchID id.ID) ([]GetMatchScoresForMatchRow, error)
	GetMatchWinnerParams(ctx context.Context, marketID id.ID) (MarketMatchWinnerParam, error)
	// Single-match payload; rating columns scoped to @arena_id (see
	// ListMatchesWithPlayersPaginated).
	GetMatchWithPlayers(ctx context.Context, arg GetMatchWithPlayersParams) ([]GetMatchWithPlayersRow, error)
	GetMatchesFromDate(ctx context.Context, date pgtype.Timestamptz) ([]Match, error)
	GetNearestGameTableExpiry(ctx context.Context) (time.Time, error)
	GetNearestMarketExpiry(ctx context.Context) (pgtype.Timestamptz, error)
	GetPlayer(ctx context.Context, argID id.ID) (Player, error)
	GetPlayerBetsAggregatedForMarket(ctx context.Context, arg GetPlayerBetsAggregatedForMarketParams) ([]GetPlayerBetsAggregatedForMarketRow, error)
	// Per-buy rows for one player, used to show shares held / elo spent (cost +
	// maker fee) on the detail page.
	GetPlayerBetsForMarket(ctx context.Context, arg GetPlayerBetsForMarketParams) ([]GetPlayerBetsForMarketRow, error)
	GetPlayerByName(ctx context.Context, name string) (Player, error)
	GetPlayerGameEloStats(ctx context.Context, arg GetPlayerGameEloStatsParams) ([]GetPlayerGameEloStatsRow, error)
	// Per-game stats for the player profile "Частые игры" table: match count plus
	//   gold/silver/bronze counts from ranking players by score within each match.
	//   Tenant-independent (ADR-36 phase 4): computed from match_scores over every
	//   stored COMPETITIVE match of the player, whatever arena (if any) settled
	//   it — coop matches affect no rating and stay out, as before. NOTE: the
	//   rank must be computed over ALL players in a match, so the CTE ranks every
	//   player in each of the target player's matches and the outer query then
	//   filters down to the target player's own rows.
	GetPlayerGameStats(ctx context.Context, playerID id.ID) ([]GetPlayerGameStatsRow, error)
	// Returns the true Elo value (elo_after) for Elo calculations.
	GetPlayerLatestArenaElo(ctx context.Context, arg GetPlayerLatestArenaEloParams) (float64, error)
	GetPlayerLatestArenaEloAtDate(ctx context.Context, arg GetPlayerLatestArenaEloAtDateParams) (float64, error)
	GetPlayerLatestArenaEloBeforeMatch(ctx context.Context, arg GetPlayerLatestArenaEloBeforeMatchParams) (float64, error)
	// Returns the display rating (rating_after) and current league for
	// rating-track calculations.
	GetPlayerLatestArenaRating(ctx context.Context, arg GetPlayerLatestArenaRatingParams) (GetPlayerLatestArenaRatingRow, error)
	GetPlayerLatestArenaRatingAtDate(ctx context.Context, arg GetPlayerLatestArenaRatingAtDateParams) (GetPlayerLatestArenaRatingAtDateRow, error)
	GetPlayerLatestArenaRatingBeforeMatch(ctx context.Context, arg GetPlayerLatestArenaRatingBeforeMatchParams) (GetPlayerLatestArenaRatingBeforeMatchRow, error)
	// The player's outstanding exposure: bet costs + maker fees on open/betting-closed
	// markets plus the risk of their guarantee wagers (ADR-20 reserves guarantor
	// exposure against the betting limit).
	GetPlayerReservedAmount(ctx context.Context, argID id.ID) (float64, error)
	// An empty game-id list counts matches from every game (the market's "any
	// game" setting, same convention as match_winner's game_ids).
	GetPlayerStreakStats(ctx context.Context, arg GetPlayerStreakStatsParams) (GetPlayerStreakStatsRow, error)
	// A market settles exactly once into its owning tenant's main arena (ADR-36),
	// so market_id alone identifies its rows (index arena_settlements_market_id_idx).
	GetSettlementDetails(ctx context.Context, marketID *id.ID) ([]GetSettlementDetailsRow, error)
	GetTagByID(ctx context.Context, argID id.ID) (Tag, error)
	GetTagGameCount(ctx context.Context, tagID id.ID) (int64, error)
	GetTenant(ctx context.Context, argID id.ID) ([]GetTenantRow, error)
	// Bare row for existence checks and settings recalculation.
	GetTenantByID(ctx context.Context, argID id.ID) (Tenant, error)
	GetTournament(ctx context.Context, argID id.ID) (Tournament, error)
	// The champion slot: the final-track slot advancing exactly one player
	// (a bracket has exactly one; a tournament-winner market resolves against it).
	GetTournamentFinalSlot(ctx context.Context, tournamentID id.ID) (GetTournamentFinalSlotRow, error)
	// Row-locked variant for the lifecycle mutations (start/cancel/config): a
	// concurrent start and cancel queue behind the lock instead of racing.
	GetTournamentForUpdate(ctx context.Context, argID id.ID) (Tournament, error)
	GetTournamentOfSlot(ctx context.Context, argID id.ID) (Tournament, error)
	GetTournamentPlan(ctx context.Context, argID id.ID) (GetTournamentPlanRow, error)
	// Bracket materialization queries (ADR-26, ADR-30): rounds, slots, seats, the
	// slot match series, and the recorded advancements. Standings are never
	// stored — they are derived from the linked matches' scores at
	// read/completion time.
	// The slot plus its round coordinates (the (tournament, track, index,
	// position) address used for deterministic ordering and display) and its
	// seat count.
	GetTournamentSlot(ctx context.Context, argID id.ID) (GetTournamentSlotRow, error)
	GetUser(ctx context.Context, argID id.ID) (User, error)
	GetUserByGoogleOAuthUserID(ctx context.Context, googleOauthUserID string) (User, error)
	// JWT fallback: resolves a user by the old SERIAL int id (ADR-08). Used when the
	// JWT "sub" claim is a bare int (pre-migration token) that isn't a valid UUID.
	GetUserByLegacyIntID(ctx context.Context, legacyIntID pgtype.Int4) (User, error)
	GetWinStreakParams(ctx context.Context, marketID id.ID) (MarketWinStreakParam, error)
	// Recompute places 1..4 per match (RANK over the match's scores) for every
	// match belonging to the arena: via arena_matches links for the link-only
	// flavors (camps, tournaments), via the filter for every other kind.
	InsertArenaStats(ctx context.Context, arenaID id.ID) error
	// Appends one audit_log row. Called inside the same transaction as the write
	// it describes (ADR-14). details_* are all NULL together for events without
	// details (e.g. match "created").
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertBet(ctx context.Context, arg InsertBetParams) (InsertBetRow, error)
	// A guarantee is a player's immutable guarantor wager: risk amount (their
	// maximum loss) and maker fee rate (ADR-20). The client-generated id doubles
	// as the idempotency key.
	InsertMarketGuarantee(ctx context.Context, arg InsertMarketGuaranteeParams) (InsertMarketGuaranteeRow, error)
	// The slot's determining match: the latest linked match in event order
	// (date, then id — the same order the standings are derived in).
	LatestSlotMatchID(ctx context.Context, slotID id.ID) (id.ID, error)
	// Playing slots of running tournaments hosting the given game, in the
	// deterministic acceptance order (track, round index, table position). The
	// seated-set equality is checked by the caller (small candidate lists).
	ListAcceptanceCandidates(ctx context.Context, gameID id.ID) ([]ListAcceptanceCandidatesRow, error)
	// Ids of the active (open or betting-closed) markets, newest created first.
	// The active list is small and bounded; payloads come from ListMarketsByIDs.
	ListActiveMarketIDs(ctx context.Context) ([]id.ID, error)
	// One page of the arena feed (ADR-32): a merged, date-ordered stream of match
	// and market events. A market enters at its creation moment while
	// it is active (open/betting_closed) and re-enters at its resolution moment
	// once settled, so a match-triggered resolution sits right after its match.
	// Market events settle only into the global arena (ADR-24), so that branch
	// joins the union only when the caller passes include_settlements. The
	// player/club/game filters apply to both branches. The cursor is the last
	// returned (sort_date, event_type, id)
	// tuple; the token carries the filters, so continuation requests pass only
	// the token.
	ListArenaFeedEvents(ctx context.Context, arg ListArenaFeedEventsParams) ([]ListArenaFeedEventsRow, error)
	// ---------------------------------------------------------------------------
	// Arena page reads
	// ---------------------------------------------------------------------------
	// Latest settlement state joined with the precalculated stats, plus the
	// arena-filtered recent match counts the elite promotion hint needs (same
	// counts as ListArenaPlayersAt, anchored at now). Final ranking (league
	// priority, then rating) is applied by the service.
	ListArenaPlayers(ctx context.Context, arenaID id.ID) ([]ListArenaPlayersRow, error)
	// Point-in-time standings of one arena (for rank-change history): the latest
	// settlement at or before @at, plus the arena-filtered match counts the elite
	// staleness check needs. Lists players with at least one settlement.
	ListArenaPlayersAt(ctx context.Context, arg ListArenaPlayersAtParams) ([]ListArenaPlayersAtRow, error)
	// kind narrows the list for the /arenas page tabs: 'games' returns every
	// user-managed arena except camps and the global one (the main page, not a
	// list entry); 'camps' returns only camp arenas; 'tournaments' returns only
	// the tournament arenas (empty until ADR-26 creates them).
	ListArenas(ctx context.Context, kind pgtype.Text) ([]ListArenasRow, error)
	// Arenas whose filter includes game @game_id or one of its tags, plus
	// unconditional (global) arenas — the /games page arena list. Camp and
	// tournament arenas are link-only (no filter) and never appear here: their
	// membership is the explicit arena_matches link, not the game.
	ListArenasForGame(ctx context.Context, gameID *id.ID) ([]ListArenasForGameRow, error)
	// Arena ids containing the given match per the membership function — part of
	// the synchronous-drain affected set on match writes. Camps are included via
	// their arena_matches links (the match must already be linked when this runs).
	ListArenasMatchingMatch(ctx context.Context, matchID id.ID) ([]id.ID, error)
	// Latest-first audit feed. Optional entity filter (one or more entity types)
	// and entity_id filter serve both the per-entity history (match view) and the
	// per-type feed (admin tabs — the games tab mixes game and tag events). The
	// cursor is the (created_at, id) row of the last returned event. The user
	// join is LEFT since ADR-26: system events (the grand-final-deadline
	// auto-cancel) carry a NULL actor.
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
	// The camps of a set of matches — the [{id, name}] payload of the match
	// response (the old match.tournaments shape).
	ListCampArenasByMatchIDs(ctx context.Context, matchIds []id.ID) ([]ListCampArenasByMatchIDsRow, error)
	// One keyset page of closed (resolved or cancelled) markets, newest resolution
	// first. resolved_at is stamped for both statuses (cancellation rides only on
	// the status column), so (resolved_at, id) is a total order and the
	// continuation cursor.
	ListClosedMarketKeys(ctx context.Context, arg ListClosedMarketKeysParams) ([]ListClosedMarketKeysRow, error)
	// ---------------------------------------------------------------------------
	// "Недавние" player-picker candidates (GET /players/recent)
	// ---------------------------------------------------------------------------
	// Active club memberships only (ADR-36 stint history): a former member's
	// club disappears from the picker tabs.
	ListClubIDsByPlayerID(ctx context.Context, playerID id.ID) ([]id.ID, error)
	// Users whose linked player is an active member of any of the given clubs —
	// the "users associated with the current user's club" for the recent list.
	ListClubMemberUserIDs(ctx context.Context, clubIds []id.ID) ([]id.ID, error)
	// The club's membership stint history (ADR-36), latest stint first: the raw
	// material of tenant membership, shown as audit-style items on the admin club
	// page. A NULL left_at is the current active stint.
	ListClubMembershipHistory(ctx context.Context, clubID id.ID) ([]ListClubMembershipHistoryRow, error)
	// Club queries (ADR-05 grouping + ADR-36 membership stints).
	// player_club_membership is stint history: joined_at / left_at, left_at NULL
	// = active stint. Reads of "the members" always filter to active stints.
	// Tenant fields (openness, main arena) live on the tenants table (tenants.sql).
	ListClubs(ctx context.Context) ([]ListClubsRow, error)
	ListEloSettings(ctx context.Context) ([]ListEloSettingsRow, error)
	// Payload rows for the feed's match events (ADR-32): per-player scores with
	// this arena's settlement data, for an explicit id set selected by
	// ListArenaFeedEvents.
	ListFeedMatchesWithPlayers(ctx context.Context, arg ListFeedMatchesWithPlayersParams) ([]ListFeedMatchesWithPlayersRow, error)
	// The tenant's lobby (ADR-36 phase 7): only tables created under the tenant,
	// still live.
	ListGameTables(ctx context.Context, tenantID id.ID) ([]GameTable, error)
	ListGameTags(ctx context.Context) ([]ListGameTagsRow, error)
	// Games carrying a BGG reference whose box art has not been fetched yet.
	// The both-NULL predicate means a row enriched with only one URL (BGG has a
	// thumbnail but no full image) leaves the enrichment set for good.
	ListGamesForBggEnrich(ctx context.Context) ([]Game, error)
	ListGamesOrderedByLastPlayed(ctx context.Context) ([]ListGamesOrderedByLastPlayedRow, error)
	ListGamesWithoutTeseraRef(ctx context.Context) ([]Game, error)
	// The current state (latest settlement row) of every player in the arena.
	// Used to diff the state before and after a full recalculation replay.
	ListLatestArenaStatePerPlayer(ctx context.Context, arenaID id.ID) ([]ListLatestArenaStatePerPlayerRow, error)
	// Raw wager rows (no join) used by settlement and the price-history replay.
	ListMarketGuaranteeWagers(ctx context.Context, marketID id.ID) ([]ListMarketGuaranteeWagersRow, error)
	// The market's guarantee wagers with player names, in join order.
	ListMarketGuarantees(ctx context.Context, marketID id.ID) ([]ListMarketGuaranteesRow, error)
	// Outcome rows in the canonical order: yes/no first (win_streak), then player
	// outcomes, 'other' last. This order fixes the AMM q-vector layout.
	ListMarketOutcomes(ctx context.Context, marketID id.ID) ([]MarketOutcome, error)
	// Outcome rows with derived display name (players.name for player outcomes)
	// and the elo spent per outcome (cost + maker fee), in the canonical order
	// (see ListMarketOutcomes).
	ListMarketOutcomesWithPools(ctx context.Context, marketID id.ID) ([]ListMarketOutcomesWithPoolsRow, error)
	// Same shape as ListMarketOutcomesWithPools for an explicit market id set
	// (used by the markets list and the arena feed), grouped client-side by
	// market_id.
	ListMarketOutcomesWithPoolsByIDs(ctx context.Context, marketIds []id.ID) ([]ListMarketOutcomesWithPoolsByIDsRow, error)
	// Full market rows for an explicit id set — payload fetch for the markets
	// lobby page and the arena feed (ADR-32).
	ListMarketsByIDs(ctx context.Context, ids []id.ID) ([]ListMarketsByIDsRow, error)
	ListMarketsByResolutionMatch(ctx context.Context, resolutionMatchID *id.ID) ([]ListMarketsByResolutionMatchRow, error)
	// Live markets whose AMM state vector diverged from the outstanding shares
	// stored in bets — the signature of the removed price-preserving rescale
	// (ADR-22). Resolved markets get the same q repair but need no settlement.
	ListMarketsWithDivergedQ(ctx context.Context) ([]id.ID, error)
	// Matches of the arena from @from_date on, in event order — the updater's
	// replay input. The membership function selects camp-linked matches for camp
	// arenas and filter matches for every other kind (one replay source, ADR-28).
	ListMatchesForArenaReplay(ctx context.Context, arg ListMatchesForArenaReplayParams) ([]Match, error)
	// The rating columns are the display arena's (@arena_id — the caller's current
	// tenant main arena, ADR-36; the global arena until the frontend carries
	// ?tenant=). The club_id / no_club filters stay club-level grouping filters.
	ListMatchesWithPlayersPaginated(ctx context.Context, arg ListMatchesWithPlayersPaginatedParams) ([]ListMatchesWithPlayersPaginatedRow, error)
	ListOpenMatchWinnerMarkets(ctx context.Context) ([]ListOpenMatchWinnerMarketsRow, error)
	// Open tournament_winner markets of one tournament — the completion hook's
	// settle input.
	ListOpenTournamentWinnerMarkets(ctx context.Context, tournamentID id.ID) ([]id.ID, error)
	// The sweep's input: open markets joined with their tournament's current
	// lifecycle state (the tournament tables are live state — they are not part
	// of the settlement replay, so the sweep settles from what they say now).
	ListOpenTournamentWinnerMarketsWithState(ctx context.Context) ([]ListOpenTournamentWinnerMarketsWithStateRow, error)
	ListOpenWinStreakMarkets(ctx context.Context) ([]ListOpenWinStreakMarketsRow, error)
	ListOverdueMatchWinnerMarkets(ctx context.Context) ([]ListOverdueMatchWinnerMarketsRow, error)
	ListOverdueMatchWinnerMarketsAtDate(ctx context.Context, closesAt pgtype.Timestamptz) ([]ListOverdueMatchWinnerMarketsAtDateRow, error)
	ListOverdueWinStreakMarkets(ctx context.Context) ([]ListOverdueWinStreakMarketsRow, error)
	ListOverdueWinStreakMarketsAtDate(ctx context.Context, closesAt pgtype.Timestamptz) ([]ListOverdueWinStreakMarketsAtDateRow, error)
	// Participants of several tournaments in registration order (the list read).
	ListParticipantsOfTournaments(ctx context.Context, tournamentIds []id.ID) ([]ListParticipantsOfTournamentsRow, error)
	ListPlayerUserLinks(ctx context.Context) ([]ListPlayerUserLinksRow, error)
	ListPlayers(ctx context.Context) ([]Player, error)
	// Players created by any of the given users, per the audit log (ADR-14 — the
	// creator lives only in audit_log.actor_user_id), with the creation date.
	// Joined to players so deleted ones drop out.
	ListPlayersCreatedByUsers(ctx context.Context, arg ListPlayersCreatedByUsersParams) ([]ListPlayersCreatedByUsersRow, error)
	// Every player with their latest state in the display arena (@arena_id — the
	// caller's current club main arena, ADR-36; the global arena until the
	// frontend carries ?club=). The site-wide catalog lists all players, members
	// or not; a members_only arena hides former members only on its own listing
	// (ListArenaPlayers).
	ListPlayersWithStats(ctx context.Context, arg ListPlayersWithStatsParams) ([]ListPlayersWithStatsRow, error)
	// Games most played by members of the given clubs — the recency/popularity
	// pair of the game picker's «Популярные» section. A match counts once when at
	// least one club member took part in it; last_match_at breaks count ties.
	ListPopularClubGames(ctx context.Context, arg ListPopularClubGamesParams) ([]ListPopularClubGamesRow, error)
	// Globally most played games — the «Популярные» fallback for users whose
	// player belongs to no club.
	ListPopularGamesGlobal(ctx context.Context, limit int32) ([]ListPopularGamesGlobalRow, error)
	// Players who shared a match with the current user's player or with a member
	// of any of the user's clubs, with the date of their most recent such match.
	// my_player_id is NULL when the user has no linked player.
	ListRecentCoPlayers(ctx context.Context, arg ListRecentCoPlayersParams) ([]ListRecentCoPlayersRow, error)
	// Games played recently by the current user's player or by a member of any of
	// their clubs, with the date of the most recent such match — the recency key
	// of the game picker's «Недавние» section. my_player_id is NULL when the user
	// has no linked player.
	ListRecentGames(ctx context.Context, arg ListRecentGamesParams) ([]ListRecentGamesRow, error)
	// Resolved tournament_winner markets of one tournament — the revert hook's
	// input (a completed tournament whose bracket changed reopens them).
	ListResolvedTournamentWinnerMarketsByTournament(ctx context.Context, tournamentID id.ID) ([]id.ID, error)
	// Running tournaments whose grand-final deadline has passed — the lazy
	// auto-cancel input. Completion flips status='completed' in the same tx as
	// the final promotion, so a completed tournament never appears here.
	ListRunningTournamentsPastDeadline(ctx context.Context) ([]Tournament, error)
	ListSeatsBySlots(ctx context.Context, slotIds []id.ID) ([]TournamentSeat, error)
	ListSeatsBySourceSlot(ctx context.Context, sourceSlotID id.ID) ([]TournamentSeat, error)
	ListSlotAdvances(ctx context.Context, slotID id.ID) ([]TournamentSlotAdvance, error)
	// The slot's match series with derived inputs for the standings: scores of
	// every linked match, in event order (date, then id — same as the arena
	// replay order).
	ListSlotMatchResults(ctx context.Context, slotID id.ID) ([]ListSlotMatchResultsRow, error)
	// Which tournament/slot (if any) each match is counted for — the match DTO's
	// tournament badge (ADR-26).
	ListSlotMatchesForMatchIDs(ctx context.Context, matchIds []id.ID) ([]ListSlotMatchesForMatchIDsRow, error)
	// Slots whose seats are fed by the given slot (downstream neighbours for the
	// seat refill / cascade invalidation).
	ListSlotsBySource(ctx context.Context, sourceSlotID id.ID) ([]ListSlotsBySourceRow, error)
	ListSlotsOfTournamentByAddress(ctx context.Context, tournamentID id.ID) ([]ListSlotsOfTournamentByAddressRow, error)
	ListStaleArenas(ctx context.Context, dueBefore time.Time) ([]ListStaleArenasRow, error)
	// Arenas whose filter has a game-tag condition — the conservative mark set
	// when any game's tags change (a tag toggle can flip any of them).
	ListTagFilteredArenaIds(ctx context.Context) ([]id.ID, error)
	ListTags(ctx context.Context) ([]ListTagsRow, error)
	// One page of the tenant feed (GET /tenants/{id}/feed, ADR-36): the
	// community's activity, membership-scoped — deliberately NOT
	// arena-attribution-scoped, so a tournament match appears even when it does
	// not count into the tenant's main arena rating. Under arena_membership_mode
	// 'all' the match branch widens to every match; under 'members_only' it
	// tightens to matches whose WHOLE roster are current members — the openness
	// rule the creation and edit guards enforce, applied to the feed too, so a
	// guest-carrying (historical) match stays out (ADR-36 phase 7). Match events
	// otherwise go to any current member's matches — of any club of the tenant
	// (coop included: community life, not just rating); market events to the
	// markets the tenant OWNS (a member's bet on another tenant's market is that
	// tenant's news). The player/club/game filters apply to both branches (the
	// arena feed's matching rule). Parameters and cursor are the arena feed's
	// minus the arena and the include flags; the tenant itself is the feed's
	// identity.
	ListTenantFeedEvents(ctx context.Context, arg ListTenantFeedEventsParams) ([]ListTenantFeedEventsRow, error)
	// Tenant queries (ADR-36). A tenant is a separate community entity: name,
	// openness settings, one main arena (arenas.tenant_id), and one or many
	// clubs (clubs.tenant_id). Tenant membership is derived from club membership
	// stints: an active stint in any club of the tenant.
	ListTenants(ctx context.Context) ([]ListTenantsRow, error)
	ListTournamentGames(ctx context.Context, tournamentID id.ID) ([]TournamentGame, error)
	ListTournamentParticipants(ctx context.Context, tournamentID id.ID) ([]ListTournamentParticipantsRow, error)
	ListTournamentRounds(ctx context.Context, tournamentID id.ID) ([]TournamentRound, error)
	ListTournamentSlots(ctx context.Context, tournamentID id.ID) ([]ListTournamentSlotsRow, error)
	// The /tournaments list: live tournaments first, then finished ones.
	ListTournaments(ctx context.Context) ([]Tournament, error)
	// Resolves the (unique) controlling user for each linked player; used to route
	// per-user SSE events (table invites, match notifications).
	ListUserIDsByPlayerIDs(ctx context.Context, dollar_1 []id.ID) ([]ListUserIDsByPlayerIDsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Serializes market mutations (bets and guarantee joins) on the market row so
	// concurrent writers cannot compute the AMM state from stale b/q.
	LockMarket(ctx context.Context, argID id.ID) error
	// Sets status = 'betting_closed' and records the betting_closed_at timestamp (user event).
	// Only succeeds if current status = 'open'; the caller must check affected rows or
	// fetch the market first to return a proper domain error.
	LockMarketBetting(ctx context.Context, argID id.ID) error
	LockPlayerForEloCalculation(ctx context.Context, argID id.ID) (id.ID, error)
	// Incremental mark: widen the pending replay window to include @from_date.
	// A pending full recalc (recalc_from IS NULL while stale) wins over dates.
	MarkArenasStaleFromDate(ctx context.Context, arg MarkArenasStaleFromDateParams) error
	// ---------------------------------------------------------------------------
	// Dirty queue
	// ---------------------------------------------------------------------------
	MarkArenasStaleFull(ctx context.Context, arenaIds []id.ID) error
	// Current-member check (active stint in any club of the tenant, ADR-36) —
	// the members_only gates: tournament registration and bets/guarantees on a
	// members_only tenant's market.
	PlayerIsTenantMember(ctx context.Context, arg PlayerIsTenantMemberParams) (bool, error)
	// Restores the q = Σ bets.shares invariant across every market.
	RecomputeOutcomeQFromBets(ctx context.Context) error
	// Closes the active stint; closed stints stay as history (ADR-36).
	RemoveClubMember(ctx context.Context, arg RemoveClubMemberParams) error
	RemoveGameTag(ctx context.Context, arg RemoveGameTagParams) error
	RemoveTournamentParticipant(ctx context.Context, arg RemoveTournamentParticipantParams) error
	// resolution_outcome is the winning outcome id; NULL for cancelled markets
	// (cancellation is carried by the status column).
	ResolveMarket(ctx context.Context, arg ResolveMarketParams) error
	SetGameTableHost(ctx context.Context, arg SetGameTableHostParams) (GameTable, error)
	// Organizer adjustment (ADR-26, ADR-30): only for slots with zero linked
	// matches. A NULL argument leaves the current value in place.
	SetSlotAdjustment(ctx context.Context, arg SetSlotAdjustmentParams) error
	SetSlotRuling(ctx context.Context, arg SetSlotRulingParams) error
	// Refill the seat caches fed by a completed source slot: place i of the
	// source seats the i-th advanced player.
	SetSlotSeatsFromAdvances(ctx context.Context, slotID id.ID) error
	SetSlotStatus(ctx context.Context, arg SetSlotStatusParams) error
	SetSlotStatusAndRuling(ctx context.Context, arg SetSlotStatusAndRulingParams) error
	// Wholesale composition replacement (ADR-36): attach the given clubs to the
	// tenant and detach every other club currently attached to it. Callers
	// validate existence and "no other tenant" first.
	SetTenantClubs(ctx context.Context, arg SetTenantClubsParams) error
	// The grand final advanced exactly one player (ADR-26): read-only from here.
	SetTournamentCompleted(ctx context.Context, arg SetTournamentCompletedParams) error
	// The single start action (ADR-26): snapshot the chosen plan + seed, stamp
	// its elimination family, close registration. The bracket materialization
	// happens in the same transaction.
	SetTournamentRunning(ctx context.Context, arg SetTournamentRunningParams) error
	// Plain transitions: cancel (organizer or grand-final deadline).
	SetTournamentStatus(ctx context.Context, arg SetTournamentStatusParams) error
	SlotHasAdvances(ctx context.Context, slotID id.ID) (bool, error)
	SlotHasMatches(ctx context.Context, slotID id.ID) (bool, error)
	// Whether the participants count into the tenant's main arena under its
	// CURRENT openness mode, evaluated at @date against stint history (ADR-36):
	// all — every match (membership irrelevant); any_member — at least one
	// participant was a member of any club of the tenant at @date; members_only —
	// all were. The Go settlement gate consults this before settling a match into
	// the tenant's arena (the SQL-side twin, tenant_arena_contains_match, probes
	// match_scores itself and lives in migration 069).
	TenantContainsPlayers(ctx context.Context, arg TenantContainsPlayersParams) (bool, error)
	// Whether ANY of the players currently has an active stint in any club of
	// the tenant (ADR-36) — the tenant-feed membership predicate: a match lands
	// in the tenant's feed iff at least one participant is a current member.
	// The match update path rejects edits that would drop the last one. A row
	// comes from tenants, so an unknown tenant is no rows (ErrTenantNotFound).
	TenantHasActiveMemberAmong(ctx context.Context, arg TenantHasActiveMemberAmongParams) (bool, error)
	// Uniqueness guard for tenant create/rename (case-insensitive, mirroring
	// clubs). @exclude_id skips the tenant being updated; NULL on create.
	TenantNameExists(ctx context.Context, arg TenantNameExistsParams) (bool, error)
	// Restores the pre-settlement status: betting_closed if the betting lock user event
	// was set, otherwise open. betting_closed_at is intentionally left untouched — it is
	// a user event and must never be cleared by recalculation.
	UnsettleMarket(ctx context.Context, argID id.ID) error
	UpdateArena(ctx context.Context, arg UpdateArenaParams) (Arena, error)
	// Name sync for auto-managed arenas when their game is renamed.
	UpdateArenaName(ctx context.Context, arg UpdateArenaNameParams) error
	// Settings-only update for the system-managed main arenas: the tenant's main
	// arena settings document is edited through the tenant (ADR-36 phase 5) —
	// arena PATCH on it is a 409.
	UpdateArenaSettings(ctx context.Context, arg UpdateArenaSettingsParams) error
	UpdateClubIcon(ctx context.Context, arg UpdateClubIconParams) (Club, error)
	UpdateClubName(ctx context.Context, arg UpdateClubNameParams) (Club, error)
	// `name` is generated (migration 063) and follows the three source names.
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdateGameBggImages(ctx context.Context, arg UpdateGameBggImagesParams) (Game, error)
	UpdateGameTableState(ctx context.Context, arg UpdateGameTableStateParams) (GameTable, error)
	UpdateMarketLiquidityB(ctx context.Context, arg UpdateMarketLiquidityBParams) error
	// Persists one component of the LMSR state vector after a bet shifts the
	// outstanding shares of an outcome.
	UpdateMarketOutcomeQ(ctx context.Context, arg UpdateMarketOutcomeQParams) error
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) error
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	// Fills one seat cache from the source slot's derived placing.
	UpdateSeatPlayer(ctx context.Context, arg UpdateSeatPlayerParams) error
	UpdateTagName(ctx context.Context, arg UpdateTagNameParams) (Tag, error)
	// Icon update: an empty string clears the icon (the same convention as club
	// icons). Validation (lowercase kebab-case, a known frontend key) happens in
	// the handler.
	UpdateTenantIcon(ctx context.Context, arg UpdateTenantIconParams) (Tenant, error)
	UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (Tenant, error)
	// Openness settings of an existing tenant (ADR-36); no rows when the tenant
	// is missing.
	UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error)
	// Registration-time config (ADR-26): name and the optional grand-final
	// deadline. The pool and participants are managed by their own queries.
	UpdateTournamentConfig(ctx context.Context, arg UpdateTournamentConfigParams) error
	UpdateUserAllowEditing(ctx context.Context, arg UpdateUserAllowEditingParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpdateUserPlayerID(ctx context.Context, arg UpdateUserPlayerIDParams) error
	// One row per role per player (buyer 'market' / guarantor 'market_guarantor'):
	// a player who is both gets two rows, hence the discriminator in the conflict
	// target. Markets settle into the owning tenant's main arena (ADR-36); the
	// caller resolves it from markets.tenant_id.
	UpsertArenaSettlementByMarket(ctx context.Context, arg UpsertArenaSettlementByMarketParams) error
	// Arena settlement queries (ADR-24). Every query is arena-scoped; callers
	// working with «Синие люди»'s main arena pass elo.BlueMenArenaID. The arena
	// is seeded by migration 051 with the well-known id below; since ADR-36 phase
	// 2 the display reads in matches.sql, players.sql and player_ranks.sql take
	// the arena as a parameter, and since migration 068 the arena itself is
	// «Синие люди»'s main arena.
	UpsertArenaSettlementByMatch(ctx context.Context, arg UpsertArenaSettlementByMatchParams) error
	UpsertMatchScore(ctx context.Context, arg UpsertMatchScoreParams) error
}

var _ Querier = (*Queries)(nil)
