// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddClubMember(ctx context.Context, arg AddClubMemberParams) error
	AddGame(ctx context.Context, name string) (Game, error)
	AddGamesIfNotExists(ctx context.Context, dollar_1 []string) ([]Game, error)
	AddPlayersIfNotExists(ctx context.Context, dollar_1 []string) ([]AddPlayersIfNotExistsRow, error)
	CreateClub(ctx context.Context, name string) (Club, error)
	CreateEloSettings(ctx context.Context, arg CreateEloSettingsParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteAllMatchScores(ctx context.Context) error
	DeleteAllMatches(ctx context.Context) error
	DeleteClub(ctx context.Context, id int32) (Club, error)
	DeleteEloSettings(ctx context.Context, effectiveDate pgtype.Timestamptz) error
	DeleteGame(ctx context.Context, id int32) (Game, error)
	DeleteMatchScores(ctx context.Context, matchID int32) error
	DeletePlayer(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetClub(ctx context.Context, id int32) ([]GetClubRow, error)
	GetCountMatchesByGame(ctx context.Context, gameID int32) (int64, error)
	GetEloSettingsForDate(ctx context.Context, effectiveDate pgtype.Timestamptz) (GetEloSettingsForDateRow, error)
	GetGameByName(ctx context.Context, name string) (Game, error)
	GetLatestEloSettings(ctx context.Context) (GetLatestEloSettingsRow, error)
	GetMatch(ctx context.Context, id int32) (Match, error)
	GetMatchScoresForMatch(ctx context.Context, matchID int32) ([]GetMatchScoresForMatchRow, error)
	GetMatchWithPlayers(ctx context.Context, id int32) ([]GetMatchWithPlayersRow, error)
	GetMatchesFromDate(ctx context.Context, date pgtype.Timestamptz) ([]Match, error)
	GetPlayer(ctx context.Context, id int32) (Player, error)
	GetPlayerByName(ctx context.Context, name string) (Player, error)
	GetPlayerGameEloStats(ctx context.Context, playerID int32) ([]GetPlayerGameEloStatsRow, error)
	GetPlayerGameStats(ctx context.Context, playerID int32) ([]GetPlayerGameStatsRow, error)
	GetPlayerLatestGameElo(ctx context.Context, arg GetPlayerLatestGameEloParams) (float64, error)
	GetPlayerLatestGameEloBeforeMatch(ctx context.Context, arg GetPlayerLatestGameEloBeforeMatchParams) (float64, error)
	GetPlayerLatestGlobalElo(ctx context.Context, playerID int32) (float64, error)
	GetPlayerLatestGlobalEloBeforeMatch(ctx context.Context, arg GetPlayerLatestGlobalEloBeforeMatchParams) (float64, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByGoogleOAuthUserID(ctx context.Context, googleOauthUserID string) (User, error)
	ListClubs(ctx context.Context) ([]ListClubsRow, error)
	ListEloSettings(ctx context.Context) ([]EloSetting, error)
	ListGamesOrderedByLastPlayed(ctx context.Context) ([]ListGamesOrderedByLastPlayedRow, error)
	ListLatestGameEloPerPlayer(ctx context.Context, gameID int32) ([]ListLatestGameEloPerPlayerRow, error)
	ListMatchResults(ctx context.Context, id int32) ([]ListMatchResultsRow, error)
	ListMatchesWithPlayers(ctx context.Context) ([]ListMatchesWithPlayersRow, error)
	ListMatchesWithPlayersByGame(ctx context.Context, id int32) ([]ListMatchesWithPlayersByGameRow, error)
	ListMatchesWithPlayersByGameFromDB(ctx context.Context, gameID int32) ([]ListMatchesWithPlayersByGameFromDBRow, error)
	ListMatchesWithPlayersPaginated(ctx context.Context, arg ListMatchesWithPlayersPaginatedParams) ([]ListMatchesWithPlayersPaginatedRow, error)
	ListPlayers(ctx context.Context) ([]Player, error)
	ListPlayersWithStats(ctx context.Context, date pgtype.Timestamptz) ([]ListPlayersWithStatsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	LockPlayerForEloCalculation(ctx context.Context, id int32) (int32, error)
	RatingHistory(ctx context.Context, playerID int32) ([]RatingHistoryRow, error)
	RemoveClubMember(ctx context.Context, arg RemoveClubMemberParams) error
	UpdateClubName(ctx context.Context, arg UpdateClubNameParams) (Club, error)
	UpdateGameName(ctx context.Context, arg UpdateGameNameParams) (Game, error)
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) error
	UpdateMatchScoreGameElo(ctx context.Context, arg UpdateMatchScoreGameEloParams) error
	UpdateMatchScoreGlobalElo(ctx context.Context, arg UpdateMatchScoreGlobalEloParams) error
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdateUserAllowEditing(ctx context.Context, arg UpdateUserAllowEditingParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpsertMatchScore(ctx context.Context, arg UpsertMatchScoreParams) error
	UpsertPlayerRatingByMatch(ctx context.Context, arg UpsertPlayerRatingByMatchParams) error
}

var _ Querier = (*Queries)(nil)
