// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rating.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ratingHistory = `-- name: RatingHistory :many
SELECT pr.date, pr.rating
FROM player_ratings pr
WHERE pr.player_id = $1
ORDER BY pr.date
`

type RatingHistoryRow struct {
	Date   pgtype.Timestamptz `json:"date"`
	Rating float64            `json:"rating"`
}

func (q *Queries) RatingHistory(ctx context.Context, playerID int32) ([]RatingHistoryRow, error) {
	rows, err := q.db.Query(ctx, ratingHistory, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RatingHistoryRow{}
	for rows.Next() {
		var i RatingHistoryRow
		if err := rows.Scan(&i.Date, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerRatingByMatch = `-- name: UpsertPlayerRatingByMatch :exec
INSERT INTO player_ratings (date, player_id, rating, source_type, match_id)
SELECT m.date, $2, $3, 'match', $1
FROM matches m WHERE m.id = $1
ON CONFLICT (match_id, player_id) WHERE match_id IS NOT NULL
DO UPDATE SET rating = EXCLUDED.rating, date = EXCLUDED.date
`

type UpsertPlayerRatingByMatchParams struct {
	MatchID  pgtype.Int4 `json:"match_id"`
	PlayerID int32       `json:"player_id"`
	Rating   float64     `json:"rating"`
}

func (q *Queries) UpsertPlayerRatingByMatch(ctx context.Context, arg UpsertPlayerRatingByMatchParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerRatingByMatch, arg.MatchID, arg.PlayerID, arg.Rating)
	return err
}
