// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skull_king.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSkullKingTablePlayer = `-- name: AddSkullKingTablePlayer :one
UPDATE skull_king_tables
SET connected_player_ids = array_append(connected_player_ids, $2)
WHERE id = $1 AND NOT ($2 = ANY(connected_player_ids))
RETURNING id, host_user_id, game_state, connected_player_ids, created_at, expires_at
`

type AddSkullKingTablePlayerParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddSkullKingTablePlayer(ctx context.Context, arg AddSkullKingTablePlayerParams) (SkullKingTable, error) {
	row := q.db.QueryRow(ctx, addSkullKingTablePlayer, arg.ID, arg.ArrayAppend)
	var i SkullKingTable
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GameState,
		&i.ConnectedPlayerIds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createSkullKingTable = `-- name: CreateSkullKingTable :one
INSERT INTO skull_king_tables (host_user_id, game_state)
VALUES ($1, $2)
RETURNING id, host_user_id, game_state, connected_player_ids, created_at, expires_at
`

type CreateSkullKingTableParams struct {
	HostUserID int32  `json:"host_user_id"`
	GameState  []byte `json:"game_state"`
}

func (q *Queries) CreateSkullKingTable(ctx context.Context, arg CreateSkullKingTableParams) (SkullKingTable, error) {
	row := q.db.QueryRow(ctx, createSkullKingTable, arg.HostUserID, arg.GameState)
	var i SkullKingTable
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GameState,
		&i.ConnectedPlayerIds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSkullKingTables = `-- name: DeleteExpiredSkullKingTables :exec
DELETE FROM skull_king_tables WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSkullKingTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSkullKingTables)
	return err
}

const deleteSkullKingTable = `-- name: DeleteSkullKingTable :exec
DELETE FROM skull_king_tables WHERE id = $1
`

func (q *Queries) DeleteSkullKingTable(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkullKingTable, id)
	return err
}

const getNearestSkullKingTableExpiry = `-- name: GetNearestSkullKingTableExpiry :one
SELECT expires_at FROM skull_king_tables WHERE expires_at > NOW() ORDER BY expires_at ASC LIMIT 1
`

func (q *Queries) GetNearestSkullKingTableExpiry(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getNearestSkullKingTableExpiry)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getSkullKingTable = `-- name: GetSkullKingTable :one
SELECT id, host_user_id, game_state, connected_player_ids, created_at, expires_at FROM skull_king_tables WHERE id = $1
`

func (q *Queries) GetSkullKingTable(ctx context.Context, id pgtype.UUID) (SkullKingTable, error) {
	row := q.db.QueryRow(ctx, getSkullKingTable, id)
	var i SkullKingTable
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GameState,
		&i.ConnectedPlayerIds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSkullKingTableForUpdate = `-- name: GetSkullKingTableForUpdate :one
SELECT id, host_user_id, game_state, connected_player_ids, created_at, expires_at FROM skull_king_tables WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSkullKingTableForUpdate(ctx context.Context, id pgtype.UUID) (SkullKingTable, error) {
	row := q.db.QueryRow(ctx, getSkullKingTableForUpdate, id)
	var i SkullKingTable
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GameState,
		&i.ConnectedPlayerIds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSkullKingTables = `-- name: ListSkullKingTables :many
SELECT id, host_user_id, game_state, connected_player_ids, created_at, expires_at FROM skull_king_tables WHERE expires_at > NOW() ORDER BY created_at DESC
`

func (q *Queries) ListSkullKingTables(ctx context.Context) ([]SkullKingTable, error) {
	rows, err := q.db.Query(ctx, listSkullKingTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkullKingTable{}
	for rows.Next() {
		var i SkullKingTable
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.GameState,
			&i.ConnectedPlayerIds,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkullKingTableState = `-- name: UpdateSkullKingTableState :one
UPDATE skull_king_tables SET game_state = $2 WHERE id = $1 RETURNING id, host_user_id, game_state, connected_player_ids, created_at, expires_at
`

type UpdateSkullKingTableStateParams struct {
	ID        pgtype.UUID `json:"id"`
	GameState []byte      `json:"game_state"`
}

func (q *Queries) UpdateSkullKingTableState(ctx context.Context, arg UpdateSkullKingTableStateParams) (SkullKingTable, error) {
	row := q.db.QueryRow(ctx, updateSkullKingTableState, arg.ID, arg.GameState)
	var i SkullKingTable
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.GameState,
		&i.ConnectedPlayerIds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
