// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tolyandre/elo-web-service/pkg/id"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, arena_membership_mode, tournaments_openness)
VALUES ($1, $2, $3, $4)
RETURNING id, name, arena_membership_mode, tournaments_openness, icon
`

type CreateTenantParams struct {
	ID                  id.ID  `json:"id"`
	Name                string `json:"name"`
	ArenaMembershipMode string `json:"arena_membership_mode"`
	TournamentsOpenness string `json:"tournaments_openness"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.ArenaMembershipMode,
		arg.TournamentsOpenness,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArenaMembershipMode,
		&i.TournamentsOpenness,
		&i.Icon,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :many
SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    t.icon AS tenant_icon,
    t.arena_membership_mode AS tenant_arena_membership_mode,
    t.tournaments_openness AS tenant_tournaments_openness,
    ma.id AS main_arena_id,
    c.id AS club_id
FROM tenants t
LEFT JOIN arenas ma ON ma.tenant_id = t.id
LEFT JOIN clubs c ON c.tenant_id = t.id
WHERE t.id = $1
`

type GetTenantRow struct {
	TenantID                  id.ID       `json:"tenant_id"`
	TenantName                string      `json:"tenant_name"`
	TenantIcon                pgtype.Text `json:"tenant_icon"`
	TenantArenaMembershipMode string      `json:"tenant_arena_membership_mode"`
	TenantTournamentsOpenness string      `json:"tenant_tournaments_openness"`
	MainArenaID               *id.ID      `json:"main_arena_id"`
	ClubID                    *id.ID      `json:"club_id"`
}

func (q *Queries) GetTenant(ctx context.Context, argID id.ID) ([]GetTenantRow, error) {
	rows, err := q.db.Query(ctx, getTenant, argID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTenantRow{}
	for rows.Next() {
		var i GetTenantRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.TenantIcon,
			&i.TenantArenaMembershipMode,
			&i.TenantTournamentsOpenness,
			&i.MainArenaID,
			&i.ClubID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, arena_membership_mode, tournaments_openness, icon FROM tenants WHERE id = $1
`

// Bare row for existence checks and settings recalculation.
func (q *Queries) GetTenantByID(ctx context.Context, argID id.ID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, argID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArenaMembershipMode,
		&i.TournamentsOpenness,
		&i.Icon,
	)
	return i, err
}

const listTenantFeedEvents = `-- name: ListTenantFeedEvents :many
WITH events AS (
    SELECT DISTINCT m.id, m.date AS sort_date, 'match'::text AS event_type
    FROM matches m
    JOIN match_scores ms ON ms.match_id = m.id
    WHERE EXISTS (
              SELECT 1
              FROM clubs c
              JOIN player_club_membership pcm ON pcm.club_id = c.id
              WHERE c.tenant_id = $5::uuid
                AND pcm.left_at IS NULL
                AND pcm.player_id = ms.player_id
          )
      AND (
          $6::uuid IS NULL OR ms.player_id = $6::uuid
      )
      AND (
          $7::uuid IS NULL
          OR EXISTS (
              SELECT 1 FROM player_club_membership pcm
              WHERE pcm.club_id = $7::uuid
                AND pcm.left_at IS NULL
                AND pcm.player_id = ms.player_id
          )
      )
      AND (
          $8::uuid IS NULL OR m.game_id = $8::uuid
      )
    UNION ALL
    -- The tenant's markets: an active market (open or betting-locked) sorts
    -- at its creation moment, a settled one (resolved or cancelled) at its
    -- resolution moment — the arena feed's ordering, with the owning tenant
    -- as the membership condition.
    SELECT om.id,
           CASE WHEN om.status IN ('open', 'betting_closed') THEN om.created_at
                ELSE om.resolved_at
           END AS sort_date,
           'market'::text
    FROM markets om
    WHERE om.tenant_id = $5::uuid
      AND (
          (om.status IN ('open', 'betting_closed') AND om.created_at IS NOT NULL)
          OR (om.status IN ('resolved', 'cancelled') AND om.resolved_at IS NOT NULL)
      )
      AND (
          $6::uuid IS NULL
          OR EXISTS (SELECT 1 FROM market_match_winner_params mwp
                     WHERE mwp.market_id = om.id
                       AND $6::uuid = ANY(mwp.target_player_ids))
          OR EXISTS (SELECT 1 FROM market_win_streak_params wsp
                     WHERE wsp.market_id = om.id
                       AND wsp.target_player_id = $6::uuid)
          OR EXISTS (SELECT 1 FROM market_outcomes mo
                     WHERE mo.market_id = om.id
                       AND mo.player_id = $6::uuid)
          OR EXISTS (SELECT 1 FROM market_guarantees mg
                     WHERE mg.market_id = om.id
                       AND mg.player_id = $6::uuid)
          OR EXISTS (SELECT 1 FROM arena_settlements ars
                     WHERE ars.market_id = om.id
                       AND ars.player_id = $6::uuid)
      )
      AND (
          $7::uuid IS NULL
          OR EXISTS (
              SELECT 1 FROM player_club_membership pcm
              WHERE pcm.club_id = $7::uuid
                AND pcm.left_at IS NULL
                AND (
                    EXISTS (SELECT 1 FROM market_match_winner_params mwp
                            WHERE mwp.market_id = om.id
                              AND pcm.player_id = ANY(mwp.target_player_ids))
                    OR EXISTS (SELECT 1 FROM market_win_streak_params wsp
                               WHERE wsp.market_id = om.id
                                 AND wsp.target_player_id = pcm.player_id)
                    OR EXISTS (SELECT 1 FROM market_outcomes mo
                               WHERE mo.market_id = om.id
                                 AND mo.player_id = pcm.player_id)
                    OR EXISTS (SELECT 1 FROM market_guarantees mg
                               WHERE mg.market_id = om.id
                                 AND mg.player_id = pcm.player_id)
                    OR EXISTS (SELECT 1 FROM arena_settlements ars
                               WHERE ars.market_id = om.id
                                 AND ars.player_id = pcm.player_id)
                )
          )
      )
      AND (
          $8::uuid IS NULL
          OR EXISTS (SELECT 1 FROM market_match_winner_params mwp
                     WHERE mwp.market_id = om.id
                       AND $8::uuid = ANY(mwp.game_ids))
          OR EXISTS (SELECT 1 FROM market_win_streak_params wsp
                     WHERE wsp.market_id = om.id
                       AND $8::uuid = ANY(wsp.game_ids))
          OR EXISTS (SELECT 1 FROM matches rm
                     WHERE rm.id = om.resolution_match_id
                       AND rm.game_id = $8::uuid)
      )
)
SELECT id, sort_date, event_type
FROM events
WHERE
    $1::timestamptz IS NULL
    OR sort_date < $1::timestamptz
    OR (
        sort_date = $1::timestamptz
        AND (
            event_type < $2::text
            OR (event_type = $2::text AND id < $3::uuid)
        )
    )
ORDER BY sort_date DESC, event_type DESC, id DESC
LIMIT $4::int4
`

type ListTenantFeedEventsParams struct {
	CursorDate pgtype.Timestamptz `json:"cursor_date"`
	CursorType pgtype.Text        `json:"cursor_type"`
	CursorID   *id.ID             `json:"cursor_id"`
	Limit      int32              `json:"limit"`
	TenantID   id.ID              `json:"tenant_id"`
	PlayerID   *id.ID             `json:"player_id"`
	ClubID     *id.ID             `json:"club_id"`
	GameID     *id.ID             `json:"game_id"`
}

type ListTenantFeedEventsRow struct {
	ID        id.ID              `json:"id"`
	SortDate  pgtype.Timestamptz `json:"sort_date"`
	EventType string             `json:"event_type"`
}

// One page of the tenant feed (GET /tenants/{id}/feed, ADR-36): the
// community's activity, membership-scoped — deliberately NOT
// arena-attribution-scoped, so a tournament match appears even when it does
// not count into the tenant's main arena rating. Match events go to any
// current member's matches — of any club of the tenant (coop included:
// community life, not just rating); market events to the markets the tenant
// OWNS (a member's bet on another tenant's market is that tenant's news).
// The player/club/game filters apply to both branches (the arena feed's
// matching rule). Parameters and cursor are the arena
// feed's minus the arena and the include flags; the tenant itself is the
// feed's identity.
func (q *Queries) ListTenantFeedEvents(ctx context.Context, arg ListTenantFeedEventsParams) ([]ListTenantFeedEventsRow, error) {
	rows, err := q.db.Query(ctx, listTenantFeedEvents,
		arg.CursorDate,
		arg.CursorType,
		arg.CursorID,
		arg.Limit,
		arg.TenantID,
		arg.PlayerID,
		arg.ClubID,
		arg.GameID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantFeedEventsRow{}
	for rows.Next() {
		var i ListTenantFeedEventsRow
		if err := rows.Scan(&i.ID, &i.SortDate, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many

SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    t.icon AS tenant_icon,
    t.arena_membership_mode AS tenant_arena_membership_mode,
    t.tournaments_openness AS tenant_tournaments_openness,
    ma.id AS main_arena_id,
    c.id AS club_id
FROM tenants t
LEFT JOIN arenas ma ON ma.tenant_id = t.id
LEFT JOIN clubs c ON c.tenant_id = t.id
ORDER BY t.name
`

type ListTenantsRow struct {
	TenantID                  id.ID       `json:"tenant_id"`
	TenantName                string      `json:"tenant_name"`
	TenantIcon                pgtype.Text `json:"tenant_icon"`
	TenantArenaMembershipMode string      `json:"tenant_arena_membership_mode"`
	TenantTournamentsOpenness string      `json:"tenant_tournaments_openness"`
	MainArenaID               *id.ID      `json:"main_arena_id"`
	ClubID                    *id.ID      `json:"club_id"`
}

// Tenant queries (ADR-36). A tenant is a separate community entity: name,
// openness settings, one main arena (arenas.tenant_id), and one or many
// clubs (clubs.tenant_id). Tenant membership is derived from club membership
// stints: an active stint in any club of the tenant.
func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.TenantIcon,
			&i.TenantArenaMembershipMode,
			&i.TenantTournamentsOpenness,
			&i.MainArenaID,
			&i.ClubID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerIsTenantMember = `-- name: PlayerIsTenantMember :one
SELECT EXISTS (
    SELECT 1
    FROM clubs c
    JOIN player_club_membership pcm ON pcm.club_id = c.id
    WHERE c.tenant_id = $1
      AND pcm.player_id = $2
      AND pcm.left_at IS NULL
) AS is_member
`

type PlayerIsTenantMemberParams struct {
	TenantID *id.ID `json:"tenant_id"`
	PlayerID id.ID  `json:"player_id"`
}

// Current-member check (active stint in any club of the tenant, ADR-36) —
// the members_only gates: tournament registration and bets/guarantees on a
// members_only tenant's market.
func (q *Queries) PlayerIsTenantMember(ctx context.Context, arg PlayerIsTenantMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, playerIsTenantMember, arg.TenantID, arg.PlayerID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const setTenantClubs = `-- name: SetTenantClubs :exec
UPDATE clubs
SET tenant_id = CASE WHEN id = ANY($1::uuid[])
                     THEN $2::uuid
                     ELSE NULL END
WHERE tenant_id = $2::uuid
   OR id = ANY($1::uuid[])
`

type SetTenantClubsParams struct {
	ClubIds  []id.ID `json:"club_ids"`
	TenantID id.ID   `json:"tenant_id"`
}

// Wholesale composition replacement (ADR-36): attach the given clubs to the
// tenant and detach every other club currently attached to it. Callers
// validate existence and "no other tenant" first.
func (q *Queries) SetTenantClubs(ctx context.Context, arg SetTenantClubsParams) error {
	_, err := q.db.Exec(ctx, setTenantClubs, arg.ClubIds, arg.TenantID)
	return err
}

const tenantContainsPlayers = `-- name: TenantContainsPlayers :one
SELECT CASE t.arena_membership_mode
           WHEN 'any_member' THEN EXISTS (
               SELECT 1
               FROM clubs c
               JOIN player_club_membership pcm ON pcm.club_id = c.id
               WHERE c.tenant_id = t.id
                 AND pcm.player_id = ANY($1::uuid[])
                 AND pcm.joined_at <= $2::timestamptz
                 AND (pcm.left_at IS NULL OR pcm.left_at > $2::timestamptz)
           )
           WHEN 'members_only' THEN NOT EXISTS (
               SELECT 1
               FROM unnest($1::uuid[]) AS pid
               WHERE NOT EXISTS (
                   SELECT 1
                   FROM clubs c2
                   JOIN player_club_membership pcm2 ON pcm2.club_id = c2.id
                   WHERE c2.tenant_id = t.id
                     AND pcm2.player_id = pid
                     AND pcm2.joined_at <= $2::timestamptz
                     AND (pcm2.left_at IS NULL OR pcm2.left_at > $2::timestamptz)
               )
           )
           ELSE false
       END AS contains
FROM tenants t
WHERE t.id = $3
`

type TenantContainsPlayersParams struct {
	PlayerIds []id.ID   `json:"player_ids"`
	Date      time.Time `json:"date"`
	TenantID  id.ID     `json:"tenant_id"`
}

// Whether the participants count into the tenant's main arena under its
// CURRENT openness mode, evaluated at @date against stint history (ADR-36):
// any_member — at least one participant was a member of any club of the
// tenant at @date; members_only — all were. The Go settlement gate consults
// this before settling a match into the tenant's arena (the SQL-side twin,
// tenant_arena_contains_match, probes match_scores itself and lives in
// migration 069).
func (q *Queries) TenantContainsPlayers(ctx context.Context, arg TenantContainsPlayersParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantContainsPlayers, arg.PlayerIds, arg.Date, arg.TenantID)
	var contains bool
	err := row.Scan(&contains)
	return contains, err
}

const tenantHasActiveMemberAmong = `-- name: TenantHasActiveMemberAmong :one
SELECT EXISTS (
    SELECT 1
    FROM clubs c
    JOIN player_club_membership pcm ON pcm.club_id = c.id
    WHERE c.tenant_id = t.id
      AND pcm.player_id = ANY($1::uuid[])
      AND pcm.left_at IS NULL
) AS has_member
FROM tenants t
WHERE t.id = $2
`

type TenantHasActiveMemberAmongParams struct {
	PlayerIds []id.ID `json:"player_ids"`
	TenantID  id.ID   `json:"tenant_id"`
}

// Whether ANY of the players currently has an active stint in any club of
// the tenant (ADR-36) — the tenant-feed membership predicate: a match lands
// in the tenant's feed iff at least one participant is a current member.
// The match update path rejects edits that would drop the last one. A row
// comes from tenants, so an unknown tenant is no rows (ErrTenantNotFound).
func (q *Queries) TenantHasActiveMemberAmong(ctx context.Context, arg TenantHasActiveMemberAmongParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantHasActiveMemberAmong, arg.PlayerIds, arg.TenantID)
	var has_member bool
	err := row.Scan(&has_member)
	return has_member, err
}

const tenantNameExists = `-- name: TenantNameExists :one
SELECT EXISTS(
    SELECT 1 FROM tenants
    WHERE lower(name) = lower($1::text)
      AND ($2::uuid IS NULL OR id <> $2::uuid)
) AS exists
`

type TenantNameExistsParams struct {
	Name      string `json:"name"`
	ExcludeID *id.ID `json:"exclude_id"`
}

// Uniqueness guard for tenant create/rename (case-insensitive, mirroring
// clubs). @exclude_id skips the tenant being updated; NULL on create.
func (q *Queries) TenantNameExists(ctx context.Context, arg TenantNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantNameExists, arg.Name, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTenantIcon = `-- name: UpdateTenantIcon :one
UPDATE tenants
SET icon = NULLIF($2::text, '')
WHERE id = $1
RETURNING id, name, arena_membership_mode, tournaments_openness, icon
`

type UpdateTenantIconParams struct {
	ID   id.ID  `json:"id"`
	Icon string `json:"icon"`
}

// Icon update: an empty string clears the icon (the same convention as club
// icons). Validation (lowercase kebab-case, a known frontend key) happens in
// the handler.
func (q *Queries) UpdateTenantIcon(ctx context.Context, arg UpdateTenantIconParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantIcon, arg.ID, arg.Icon)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArenaMembershipMode,
		&i.TournamentsOpenness,
		&i.Icon,
	)
	return i, err
}

const updateTenantName = `-- name: UpdateTenantName :one
UPDATE tenants
SET name = $2
WHERE id = $1
RETURNING id, name, arena_membership_mode, tournaments_openness, icon
`

type UpdateTenantNameParams struct {
	ID   id.ID  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantName, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArenaMembershipMode,
		&i.TournamentsOpenness,
		&i.Icon,
	)
	return i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants
SET arena_membership_mode = $2, tournaments_openness = $3
WHERE id = $1
RETURNING id, name, arena_membership_mode, tournaments_openness, icon
`

type UpdateTenantSettingsParams struct {
	ID                  id.ID  `json:"id"`
	ArenaMembershipMode string `json:"arena_membership_mode"`
	TournamentsOpenness string `json:"tournaments_openness"`
}

// Openness settings of an existing tenant (ADR-36); no rows when the tenant
// is missing.
func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings, arg.ID, arg.ArenaMembershipMode, arg.TournamentsOpenness)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArenaMembershipMode,
		&i.TournamentsOpenness,
		&i.Icon,
	)
	return i, err
}
