// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, allow_editing, google_oauth_user_id, google_oauth_user_name)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	ID                  string `json:"id"`
	AllowEditing        bool   `json:"allow_editing"`
	GoogleOauthUserID   string `json:"google_oauth_user_id"`
	GoogleOauthUserName string `json:"google_oauth_user_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AllowEditing,
		arg.GoogleOauthUserID,
		arg.GoogleOauthUserName,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    allow_editing,
    google_oauth_user_id,
    google_oauth_user_name,
    player_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AllowEditing,
		&i.GoogleOauthUserID,
		&i.GoogleOauthUserName,
		&i.PlayerID,
	)
	return i, err
}

const getUserByGoogleOAuthUserID = `-- name: GetUserByGoogleOAuthUserID :one
SELECT
    id,
    allow_editing,
    google_oauth_user_id,
    google_oauth_user_name,
    player_id
FROM users
WHERE google_oauth_user_id = $1
`

func (q *Queries) GetUserByGoogleOAuthUserID(ctx context.Context, googleOauthUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleOAuthUserID, googleOauthUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AllowEditing,
		&i.GoogleOauthUserID,
		&i.GoogleOauthUserName,
		&i.PlayerID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    allow_editing,
    google_oauth_user_id,
    google_oauth_user_name,
    player_id
FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AllowEditing,
			&i.GoogleOauthUserID,
			&i.GoogleOauthUserName,
			&i.PlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAllowEditing = `-- name: UpdateUserAllowEditing :exec
UPDATE users
SET allow_editing = $2
WHERE id = $1
`

type UpdateUserAllowEditingParams struct {
	ID           string `json:"id"`
	AllowEditing bool   `json:"allow_editing"`
}

func (q *Queries) UpdateUserAllowEditing(ctx context.Context, arg UpdateUserAllowEditingParams) error {
	_, err := q.db.Exec(ctx, updateUserAllowEditing, arg.ID, arg.AllowEditing)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
SET google_oauth_user_name = $2
WHERE id = $1
`

type UpdateUserNameParams struct {
	ID                  string `json:"id"`
	GoogleOauthUserName string `json:"google_oauth_user_name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.GoogleOauthUserName)
	return err
}

const updateUserPlayerID = `-- name: UpdateUserPlayerID :exec
UPDATE users SET player_id = $2 WHERE id = $1
`

type UpdateUserPlayerIDParams struct {
	ID       string  `json:"id"`
	PlayerID *string `json:"player_id"`
}

func (q *Queries) UpdateUserPlayerID(ctx context.Context, arg UpdateUserPlayerIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPlayerID, arg.ID, arg.PlayerID)
	return err
}
