// Every exported page of the app, precached by the service worker so the app
// opens while offline. With `output: "export"` each page.tsx is exactly one
// HTML file, so a constant list is the simplest correct manifest.
//
// KEEP IN SYNC with app/**/page.tsx: add new routes here when adding pages.
export const PAGES = [
    "/",
    "/admin",
    "/admin/clubs",
    "/admin/clubs/edit",
    "/admin/formula",
    "/admin/games",
    "/admin/markets",
    "/admin/players",
    "/admin/users",
    "/calculators",
    "/calculators/chess-clock",
    "/calculators/skull-king",
    "/calculators/st-patrick",
    "/games",
    "/games/view",
    "/help",
    "/markets",
    "/markets/new",
    "/markets/view",
    "/matches",
    "/matches/edit",
    "/matches/new",
    "/matches/table/iaww",
    "/matches/table/skull-king",
    "/matches/view",
    "/oauth2-callback",
    "/players",
    "/players/view",
    "/settings",
    "/tournaments",
    "/tournaments/edit",
    "/tournaments/new",
    "/tournaments/view",
] as const;
