DROP TABLE IF EXISTS player_ratings;
DROP TABLE IF EXISTS match_scores;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS player_club_membership;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS users;