package elo

import "errors"

var (
	ErrTooFewPlayers                    = errors.New("партия требует минимум 2 игрока")
	ErrDateChangeTooLarge               = errors.New("изменение даты партии не может превышать 3 дня")
	ErrMatchDateOutOfRange              = errors.New("дата партии не может быть в будущем или старше 30 дней")
	ErrBetLimitExceeded                 = errors.New("ставка превысит лимит бронирования")
	ErrMarketNotOpen                    = errors.New("рынок не открыт")
	ErrMarketOutcomeNotFound            = errors.New("указанный исход не существует на этом рынке")
	ErrProbabilityChanged               = errors.New("цена изменилась, обновите страницу и повторите ставку")
	ErrMarketNeedsGuarantor             = errors.New("рынок ждёт поручителей: пока ставок нет, встать поручителем можно на странице рынка")
	ErrGuaranteeRiskNotPositive         = errors.New("размер риска поручителя должен быть положительным")
	ErrGuaranteeFeeOutOfRange           = errors.New("комиссия поручителя должна быть от 0% до 25%")
	ErrPlayerHasNoLinkedPlayer          = errors.New("у пользователя нет привязанного игрока")
	ErrPlayerAlreadyLinked              = errors.New("player already linked to another user")
	ErrHistoryChangeConflict            = errors.New("изменение истории невозможно: ставка была сделана до того, как рынок был разрешён в результате новой даты партии")
	ErrHistoryChangeConflictBettingLock = errors.New("изменение истории невозможно: приём ставок был закрыт до того, как рынок был разрешён в результате новой даты партии")
	ErrMatchNotFound                    = errors.New("матч не найден")

	// Camp arenas (ADR-27).
	ErrCampDatesRequired       = errors.New("кэмпу нужны дата начала и дата конца")
	ErrCampDatesInvalid        = errors.New("дата начала кэмпа должна быть раньше даты конца")
	ErrCampDatesExcludeMatch   = errors.New("даты кэмпа не охватывают уже сыгранные партии")
	ErrCampLeaguesNotAllowed   = errors.New("кэмп не может иметь лиги")
	ErrCampArenaInvalid        = errors.New("указанный кэмп не существует или дата партии вне его дат")
	ErrMatchOutsideCampWindows = errors.New("дата партии вне дат кэмпа, в котором она учтена — исключите её из кэмпа в этом же изменении")

	// Tournament brackets (ADR-26).
	ErrTournamentNameRequired           = errors.New("укажите название турнира")
	ErrTournamentPoolEntryInvalid       = errors.New("вместимость стола: минимум 2 игрока, максимум не меньше минимума")
	ErrTournamentDeadlineInvalid        = errors.New("дедлайн гранд-финала должен быть в будущем")
	ErrTournamentNotEditable            = errors.New("турнир больше не в регистрации — конфигурацию изменить нельзя")
	ErrTournamentNotOpenForRegistration = errors.New("регистрация на этот турнир закрыта")
	ErrTournamentNotRunning             = errors.New("турнир не идёт")
	ErrTournamentTooFewParticipants     = errors.New("для сетки нужно минимум 2 участника")
	ErrTournamentPoolEmpty              = errors.New("добавьте в пул хотя бы одну игру")
	ErrTournamentPlanInvalid            = errors.New("этот план сетки не входит в допустимые для текущего состава участников и пула")
	ErrTournamentAlreadyStarted         = errors.New("турнир уже начат")
	ErrTournamentNotStarted             = errors.New("турнир ещё не начат")
	ErrTournamentLifecycleInvalid       = errors.New("действие недоступно в текущем состоянии турнира")
	ErrSlotAssociationLocked            = errors.New("партия учтена в турнирной сетке — состав игроков и игру менять нельзя, сначала открепите её от стола")
	ErrTournamentSlotNotFound           = errors.New("стол не найден в этой сетке")
	ErrTournamentSlotNotPlaying         = errors.New("стол не принимает партии")
	ErrTournamentRulingInvalid          = errors.New("решение организатора: нужен упорядоченный список ровно из promote игроков за этим столом")
	ErrTournamentRulingUnsafe           = errors.New("решение изменит результат кругов, где уже сыграны партии или записаны решения, — сначала разберите их от последнего круга к этому")
	ErrTournamentSlotAdjustInvalid      = errors.New("стол уже сыгран — менять игру или вместимость нельзя")
	ErrMatchAlreadyLinked               = errors.New("партия уже учтена за другим столом")
	ErrTournamentMatchNotLinked         = errors.New("партия не учтена за этим столом")
	ErrTournamentMatchFitsNoSlot        = errors.New("партия не подходит ни под один стол: нужна та же игра и ровно тот же состав игроков")
	ErrTournamentLinkChangeUnsafe       = errors.New("изменение учёта партии затронет уже сыгранные матчи следующих кругов — используйте инструменты организатора")
	ErrGrandFinalDeadlinePassed         = errors.New("дедлайн гранд-финала истёк")

	ErrGlobalArenaIsPermanent = errors.New("глобальную арену нельзя изменить или удалить")
	ErrArenaIsAutoManaged     = errors.New("арена игры или турнира управляется автоматически и не может быть изменена")
	ErrArenaNameTaken         = errors.New("арена с таким названием уже существует")
)
