schema = 3

[mod]
  [mod.'dario.cat/mergo']
    version = 'v1.0.2'
    hash = 'sha256-p6jdiHlLEfZES8vJnDywG4aVzIe16p0CU6iglglIweA='

  [mod.'github.com/Azure/go-ansiterm']
    version = 'v0.0.0-20210617225240-d185dfc1b5a1'
    hash = 'sha256-rOhb0GMLPdnh1302vaxFjO20fM69hCT29hQD1F1YpPg='

  [mod.'github.com/Microsoft/go-winio']
    version = 'v0.6.2'
    hash = 'sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU='

  [mod.'github.com/apapsch/go-jsonmerge/v2']
    version = 'v2.0.0'
    hash = 'sha256-xp/1B6XUN2EbddBfoUkTV3oTk+34m4kOZP+66HhfLg4='

  [mod.'github.com/bytedance/sonic']
    version = 'v1.13.3'
    hash = 'sha256-Nnt5b2NkIvSXhGERQmyI0ka28hbWi7A7Zn3dsAjPcEA='

  [mod.'github.com/bytedance/sonic/loader']
    version = 'v0.2.4'
    hash = 'sha256-rv9LnePpm4OspSVbfSoVbohXzhu+dxE1BH1gm3mTmTc='

  [mod.'github.com/cenkalti/backoff/v4']
    version = 'v4.3.0'
    hash = 'sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/cloudwego/base64x']
    version = 'v0.1.5'
    hash = 'sha256-MyUYTveN48DhnL8mwAgCRuMExLct98uzSPsmYlfaa4I='

  [mod.'github.com/containerd/errdefs']
    version = 'v1.0.0'
    hash = 'sha256-wMZGoeqvRhuovYCJx0Js4P3qFCNTZ/6Atea/kNYoPMI='

  [mod.'github.com/containerd/errdefs/pkg']
    version = 'v0.3.0'
    hash = 'sha256-BILJ0Be4cc8xfvLPylc/Pvwwa+w88+Hd0njzetUCeTg='

  [mod.'github.com/containerd/log']
    version = 'v0.1.0'
    hash = 'sha256-vuE6Mie2gSxiN3jTKTZovjcbdBd1YEExb7IBe3GM+9s='

  [mod.'github.com/containerd/platforms']
    version = 'v0.2.1'
    hash = 'sha256-XQdg/tnn5uKNzUc/dMmoIS9wgarx7SxaqZ5uJ9ZglA0='

  [mod.'github.com/cpuguy83/dockercfg']
    version = 'v0.3.2'
    hash = 'sha256-Jm0B99cXSJwMT53P0C6rhqDnZUykZXMVTdlvDrDvrxQ='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/distribution/reference']
    version = 'v0.6.0'
    hash = 'sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4='

  [mod.'github.com/docker/docker']
    version = 'v28.5.1+incompatible'
    hash = 'sha256-ZjpcnpbNyb8m5cqv8VcgzMFXwtV14tefoowvrYwyrAA='

  [mod.'github.com/docker/go-connections']
    version = 'v0.6.0'
    hash = 'sha256-RoK/DIT7Q1Yxzbr0xcgYP7ORJgH894tjlKDp+voznGM='

  [mod.'github.com/docker/go-units']
    version = 'v0.5.0'
    hash = 'sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE='

  [mod.'github.com/dprotaso/go-yit']
    version = 'v0.0.0-20220510233725-9ba8df137936'
    hash = 'sha256-fswb9R29XT7W2mdZyyF5WOnSmPEyyH+mG36tbsgT89w='

  [mod.'github.com/ebitengine/purego']
    version = 'v0.8.4'
    hash = 'sha256-cMdZ3DhlGGldRsHRxkslAEwKgQnlbUMvDpt3boplxWs='

  [mod.'github.com/felixge/httpsnoop']
    version = 'v1.0.4'
    hash = 'sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.9.0'
    hash = 'sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g='

  [mod.'github.com/gabriel-vasile/mimetype']
    version = 'v1.4.9'
    hash = 'sha256-75uELLqb01djHTe7KdXvUidBK7SuejarYouEUuxaj8Q='

  [mod.'github.com/getkin/kin-openapi']
    version = 'v0.133.0'
    hash = 'sha256-0evs4iWdHhn+nIy+Lyy25DV75dKXrdh4OnibNF9lDqg='

  [mod.'github.com/gin-contrib/cors']
    version = 'v1.7.6'
    hash = 'sha256-REK1xHR5pN/uh9BEAvDZ+P1+9L6Zg/tvylcrZ5umBqQ='

  [mod.'github.com/gin-contrib/sse']
    version = 'v1.1.0'
    hash = 'sha256-2VP6zHEsPi0u2ZYpOTcLulwj1Gsmb6oA19qcP2/AzVM='

  [mod.'github.com/gin-gonic/gin']
    version = 'v1.10.1'
    hash = 'sha256-D98+chAdjb6JcLPkscOr8TgTW87UqA4h3cnY0XIr16c='

  [mod.'github.com/go-logr/logr']
    version = 'v1.4.3'
    hash = 'sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA='

  [mod.'github.com/go-logr/stdr']
    version = 'v1.2.2'
    hash = 'sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE='

  [mod.'github.com/go-ole/go-ole']
    version = 'v1.2.6'
    hash = 'sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs='

  [mod.'github.com/go-openapi/jsonpointer']
    version = 'v0.21.0'
    hash = 'sha256-bB8XTzo4hzXemi8Ey3tIXia3mfn38bvwIzKYLJYC650='

  [mod.'github.com/go-openapi/swag']
    version = 'v0.23.0'
    hash = 'sha256-D5CzsSQ3SYJLwXT6BDahnG66LI8du59Dy1mY4KutA7A='

  [mod.'github.com/go-playground/locales']
    version = 'v0.14.1'
    hash = 'sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ='

  [mod.'github.com/go-playground/universal-translator']
    version = 'v0.18.1'
    hash = 'sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E='

  [mod.'github.com/go-playground/validator/v10']
    version = 'v10.26.0'
    hash = 'sha256-/jMKICp8LTcJVt+b4YRTnJM84r7HK6aT0oqO7Q8SRs8='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.4.0'
    hash = 'sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE='

  [mod.'github.com/goccy/go-json']
    version = 'v0.10.5'
    hash = 'sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw='

  [mod.'github.com/golang-jwt/jwt']
    version = 'v3.2.2+incompatible'
    hash = 'sha256-LOkpuXhWrFayvVf1GOaOmZI5YKEsgqVSb22aF8LnCEM='

  [mod.'github.com/golang-migrate/migrate/v4']
    version = 'v4.15.2'
    hash = 'sha256-HYg+zl8YRzkKPVy00ReHa8SfHapUWXZJ49/rzNT4Uo4='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/grpc-ecosystem/grpc-gateway/v2']
    version = 'v2.28.0'
    hash = 'sha256-QeWb6jN6noeGPCzECgpUSb9YX9LzvKGwImEuX+A03gs='

  [mod.'github.com/hashicorp/errwrap']
    version = 'v1.1.0'
    hash = 'sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw='

  [mod.'github.com/hashicorp/go-multierror']
    version = 'v1.1.1'
    hash = 'sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA='

  [mod.'github.com/jackc/pgpassfile']
    version = 'v1.0.0'
    hash = 'sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM='

  [mod.'github.com/jackc/pgservicefile']
    version = 'v0.0.0-20240606120523-5a60cdf6a761'
    hash = 'sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0='

  [mod.'github.com/jackc/pgx/v5']
    version = 'v5.8.0'
    hash = 'sha256-Mq5/A/Obcceu6kKxUv30DPC2ZaVvD8Iq/YtmLm1BVec='

  [mod.'github.com/jackc/puddle/v2']
    version = 'v2.2.2'
    hash = 'sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk='

  [mod.'github.com/josharian/intern']
    version = 'v1.0.0'
    hash = 'sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0='

  [mod.'github.com/json-iterator/go']
    version = 'v1.1.12'
    hash = 'sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM='

  [mod.'github.com/klauspost/compress']
    version = 'v1.18.0'
    hash = 'sha256-jc5pMU/HCBFOShMcngVwNMhz9wolxjOb579868LtOuk='

  [mod.'github.com/klauspost/cpuid/v2']
    version = 'v2.2.10'
    hash = 'sha256-o21Tk5sD7WhhLUoqSkymnjLbzxl0mDJCTC1ApfZJrC0='

  [mod.'github.com/leodido/go-urn']
    version = 'v1.4.0'
    hash = 'sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0='

  [mod.'github.com/lib/pq']
    version = 'v1.10.9'
    hash = 'sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs='

  [mod.'github.com/lufia/plan9stats']
    version = 'v0.0.0-20211012122336-39d0f177ccd0'
    hash = 'sha256-thb+rkDx5IeWMgw5/5jgu5gZ+6RjJAUXeMgSkJHhRlA='

  [mod.'github.com/magiconair/properties']
    version = 'v1.8.10'
    hash = 'sha256-smE+l2A9yDnDJFI7iNCjjF9NQnPySxEFFnbRUHyCq7I='

  [mod.'github.com/mailru/easyjson']
    version = 'v0.7.7'
    hash = 'sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/moby/docker-image-spec']
    version = 'v1.3.1'
    hash = 'sha256-xwSNLmMagzywdGJIuhrWl1r7cIWBYCOMNYbuDDT6Jhs='

  [mod.'github.com/moby/go-archive']
    version = 'v0.1.0'
    hash = 'sha256-RGhGAlc0AV1YuUsHl90AY2WQwjIU2GaJ48gMvbo13+8='

  [mod.'github.com/moby/patternmatcher']
    version = 'v0.6.0'
    hash = 'sha256-ny3L8ktj8cyN41CEJhaRT74Vi8HpXXsbTvlrw/Tl5+g='

  [mod.'github.com/moby/sys/sequential']
    version = 'v0.6.0'
    hash = 'sha256-ZNWZuuvn+iDYMsL08IU6wvXC4OfAa7rol4kaCvytZ64='

  [mod.'github.com/moby/sys/user']
    version = 'v0.4.0'
    hash = 'sha256-Lk9pZFh/ERYGWkcKfVKhlDW66J13FESGD0yJcBc8+ts='

  [mod.'github.com/moby/sys/userns']
    version = 'v0.1.0'
    hash = 'sha256-zwXKyEZIH/FZjSVuSGmtwThDxPutj1pY+N6Ae6oVPuc='

  [mod.'github.com/moby/term']
    version = 'v0.5.0'
    hash = 'sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8='

  [mod.'github.com/modern-go/concurrent']
    version = 'v0.0.0-20180306012644-bacd9c7ef1dd'
    hash = 'sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo='

  [mod.'github.com/modern-go/reflect2']
    version = 'v1.0.2'
    hash = 'sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU='

  [mod.'github.com/mohae/deepcopy']
    version = 'v0.0.0-20170929034955-c48cc78d4826'
    hash = 'sha256-TQMmKqIYwVhmMVh4RYQkAui97Eyj7poLmcAuDcHXsEk='

  [mod.'github.com/morikuni/aec']
    version = 'v1.0.0'
    hash = 'sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE='

  [mod.'github.com/oapi-codegen/oapi-codegen/v2']
    version = 'v2.6.0'
    hash = 'sha256-LYWYUNwRd2OyeGkXQr1n56gwt/PuLK0onPH3IiXbVpo='

  [mod.'github.com/oapi-codegen/runtime']
    version = 'v1.4.0'
    hash = 'sha256-02RFkg6tlP6DI0IlYIEjwkUbE11cXLw17H/Ey4zxA0k='

  [mod.'github.com/oasdiff/yaml']
    version = 'v0.0.0-20250309154309-f31be36b4037'
    hash = 'sha256-8K/OpDx7hwlloOaDkeOO6VmuoZs7MY7pYoJDWLNdvkw='

  [mod.'github.com/oasdiff/yaml3']
    version = 'v0.0.0-20250309153720-d2182401db90'
    hash = 'sha256-egJOh0zRxlaDhQNdDao0qV7Tpsqe1sU/868PRIrl2Ag='

  [mod.'github.com/opencontainers/go-digest']
    version = 'v1.0.0'
    hash = 'sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ='

  [mod.'github.com/opencontainers/image-spec']
    version = 'v1.1.1'
    hash = 'sha256-bxBjtl+6846Ed3QHwdssOrNvlHV6b+Dn17zPISSQGP8='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

  [mod.'github.com/perimeterx/marshmallow']
    version = 'v1.1.5'
    hash = 'sha256-fFWjg0FNohDSV0/wUjQ8fBq1g8h6yIqTrHkxqL2Tt0s='

  [mod.'github.com/pkg/errors']
    version = 'v0.9.1'
    hash = 'sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/power-devops/perfstat']
    version = 'v0.0.0-20210106213030-5aafc221ea8c'
    hash = 'sha256-ywykDYuqcMt0TvZOz1l9Z6Z2JMTYQw8cP2fT8AtpmX4='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.11.0'
    hash = 'sha256-PUX8dzJtkD8YDZFNqpHnl4qgb0tE1W/DLnL7V+/d1z4='

  [mod.'github.com/shirou/gopsutil/v4']
    version = 'v4.25.6'
    hash = 'sha256-NC57OD+e8fJLy73QBMy5cuDa2l2beZf9kKi8mGPsCVw='

  [mod.'github.com/sirupsen/logrus']
    version = 'v1.9.3'
    hash = 'sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms='

  [mod.'github.com/sourcegraph/conc']
    version = 'v0.3.1-0.20240121214520-5f936abd7ae8'
    hash = 'sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8='

  [mod.'github.com/speakeasy-api/jsonpath']
    version = 'v0.6.0'
    hash = 'sha256-VIfIDYnpBwUBM630zKrB+XuPQpU1ClopWmcZ3i30Odw='

  [mod.'github.com/speakeasy-api/openapi-overlay']
    version = 'v0.10.2'
    hash = 'sha256-7EzV8q7kEM2uQQ2iLIaKXBG5GDNyT/mlgAMg+uDLi7I='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/testcontainers/testcontainers-go']
    version = 'v0.40.0'
    hash = 'sha256-KNjFcAaAzygCPIEITCjQYwRarmfMVkQJUdSzUNE7XfM='

  [mod.'github.com/testcontainers/testcontainers-go/modules/postgres']
    version = 'v0.40.0'
    hash = 'sha256-ZQVkrlGO4PnazAJ2/Ik2UCDd7xdshpcTpYTt7H7vje0='

  [mod.'github.com/tklauser/go-sysconf']
    version = 'v0.3.12'
    hash = 'sha256-91VBZNb3L2TZkEETF1AE4wnraLoGxKeofUbC5ZiWVHk='

  [mod.'github.com/tklauser/numcpus']
    version = 'v0.6.1'
    hash = 'sha256-8eFcw4YI0w6+GPhU5xMMQjiio94q/O5PpNO3QsvXve0='

  [mod.'github.com/twitchyliquid64/golang-asm']
    version = 'v0.15.1'
    hash = 'sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY='

  [mod.'github.com/ugorji/go/codec']
    version = 'v1.3.0'
    hash = 'sha256-MlEltg+EpDa20zLzdhEpE/t6gzBOA5icM/oTEEN/7Eo='

  [mod.'github.com/vmware-labs/yaml-jsonpath']
    version = 'v0.3.2'
    hash = 'sha256-BZiEtlTVjwtLFaqYu1005t0yFc1/D1iNeabnsAtSXRY='

  [mod.'github.com/woodsbury/decimal128']
    version = 'v1.3.0'
    hash = 'sha256-F0Ooz4nyMBlpQ/E0fRYrKwHNmvkIDdcCihTBdIvHeoU='

  [mod.'github.com/yusufpapurcu/wmi']
    version = 'v1.2.4'
    hash = 'sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA='

  [mod.'go.opentelemetry.io/auto/sdk']
    version = 'v1.2.1'
    hash = 'sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE='

  [mod.'go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp']
    version = 'v0.61.0'
    hash = 'sha256-4pfXD7ErXhexSynXiEEQSAkWoPwHd7PEDE3M1Zi5gLM='

  [mod.'go.opentelemetry.io/otel']
    version = 'v1.39.0'
    hash = 'sha256-ExtTq4iRL2Hsh9CIPudao86Y1qtisRzIIzaH7QngEIU='

  [mod.'go.opentelemetry.io/otel/metric']
    version = 'v1.39.0'
    hash = 'sha256-VbkFRo307Sicjk3DKOkim8ptLZafAiK3vUMQdyusxF4='

  [mod.'go.opentelemetry.io/otel/sdk']
    version = 'v1.39.0'
    hash = 'sha256-GaLoc4oW2QLtJwA/FwSW3A4BqP7u0aX7f+MCfb8TFvw='

  [mod.'go.opentelemetry.io/otel/sdk/metric']
    version = 'v1.39.0'
    hash = 'sha256-UkdZZhcFh+JcHzeUGmvGXqM2wmj17HHaXkjw/+vpbzg='

  [mod.'go.opentelemetry.io/otel/trace']
    version = 'v1.39.0'
    hash = 'sha256-5e2yJbiJPcuXq5ldOA8Z4hHIh4Ywk0MgQ9OHNqOAiRo='

  [mod.'go.uber.org/atomic']
    version = 'v1.7.0'
    hash = 'sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/arch']
    version = 'v0.18.0'
    hash = 'sha256-tUpUPERjmRi7zldj0oPlnbnBhEkcI9iQGvP1HqlsK10='

  [mod.'golang.org/x/crypto']
    version = 'v0.47.0'
    hash = 'sha256-78iRvMmPZVTBrIk30yGpAO11kVC5TLR1zGW85gFLHk4='

  [mod.'golang.org/x/mod']
    version = 'v0.32.0'
    hash = 'sha256-4gbgIqTOo0vcYV3l4MIwmT/h8H9PXmcfrJ3z4B26Zl0='

  [mod.'golang.org/x/net']
    version = 'v0.49.0'
    hash = 'sha256-arK6PWwO9tQUJVb57QXUEXfgcB6ISI6qjVB0eC4zcnw='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.40.0'
    hash = 'sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg='

  [mod.'golang.org/x/text']
    version = 'v0.34.0'
    hash = 'sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM='

  [mod.'golang.org/x/tools']
    version = 'v0.41.0'
    hash = 'sha256-/Plnksa1jSr4jYJc2oCH9fcjGbWocM7EYposMP0tScQ='

  [mod.'google.golang.org/genproto/googleapis/api']
    version = 'v0.0.0-20260209200024-4cfbd4190f57'
    hash = 'sha256-2C7DZwLpDDdmUhVUcRDaotbtkhQFOQ9a1SsdVC8lOqc='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20260209200024-4cfbd4190f57'
    hash = 'sha256-gdgUw1LzgVOrarF1cGBUI9uoaR/d6lur2RwxUDKnOZA='

  [mod.'google.golang.org/grpc']
    version = 'v1.79.1'
    hash = 'sha256-qJzroXZYo57MBIswxVVlXQuK/ubK1k9dAkD5btKCa4Y='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.11'
    hash = 'sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE='

  [mod.'gopkg.in/yaml.v2']
    version = 'v2.4.0'
    hash = 'sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
