name: Build and test nix module

on: 
  push:
    branches: [ "main" ]
    paths: ["elo-web-service/**", "nix/**"]

  pull_request:
    branches: [ "main" ]
    paths: ["elo-web-service/**", "nix/**"]

jobs:
  nix-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nix
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check module evaluation
        run: nix-instantiate --strict test-syntax.nix

      - name: Run NixOS test
        run: nix-build test-integration.nix
